/* File generated by the BNF Converter (bnfc 2.9.4). */

//C++ Abstract Syntax Implementation.
#include <algorithm>
#include <string>
#include <vector>
#include "Absyn.H"

/********************   LEntry    ********************/
LEntry::LEntry(Ident p1, BlocoDefinicoes *p2, BlocoComando *p3)
{
  ident_ = p1;
  blocodefinicoes_ = p2;
  blococomando_ = p3;

}

LEntry::LEntry(const LEntry & other)
{
  ident_ = other.ident_;
  blocodefinicoes_ = other.blocodefinicoes_->clone();
  blococomando_ = other.blococomando_->clone();

}

LEntry &LEntry::operator=(const LEntry & other)
{
  LEntry tmp(other);
  swap(tmp);
  return *this;
}

void LEntry::swap(LEntry & other)
{
  std::swap(ident_, other.ident_);
  std::swap(blocodefinicoes_, other.blocodefinicoes_);
  std::swap(blococomando_, other.blococomando_);

}

LEntry::~LEntry()
{
  delete(blocodefinicoes_);
  delete(blococomando_);

}

void LEntry::accept(Visitor *v)
{
  v->visitLEntry(this);
}

LEntry *LEntry::clone() const
{
  return new LEntry(*this);
}



/********************   BlocoDefinicoes1    ********************/
BlocoDefinicoes1::BlocoDefinicoes1(BlocoFuncaoEProc *p1, BlocoDefinicoes *p2)
{
  blocofuncaoeproc_ = p1;
  blocodefinicoes_ = p2;

}

BlocoDefinicoes1::BlocoDefinicoes1(const BlocoDefinicoes1 & other)
{
  blocofuncaoeproc_ = other.blocofuncaoeproc_->clone();
  blocodefinicoes_ = other.blocodefinicoes_->clone();

}

BlocoDefinicoes1 &BlocoDefinicoes1::operator=(const BlocoDefinicoes1 & other)
{
  BlocoDefinicoes1 tmp(other);
  swap(tmp);
  return *this;
}

void BlocoDefinicoes1::swap(BlocoDefinicoes1 & other)
{
  std::swap(blocofuncaoeproc_, other.blocofuncaoeproc_);
  std::swap(blocodefinicoes_, other.blocodefinicoes_);

}

BlocoDefinicoes1::~BlocoDefinicoes1()
{
  delete(blocofuncaoeproc_);
  delete(blocodefinicoes_);

}

void BlocoDefinicoes1::accept(Visitor *v)
{
  v->visitBlocoDefinicoes1(this);
}

BlocoDefinicoes1 *BlocoDefinicoes1::clone() const
{
  return new BlocoDefinicoes1(*this);
}



/********************   BlocoDefinicoes2    ********************/
BlocoDefinicoes2::BlocoDefinicoes2(BlocoConstante *p1, BlocoDefinicoes *p2)
{
  blococonstante_ = p1;
  blocodefinicoes_ = p2;

}

BlocoDefinicoes2::BlocoDefinicoes2(const BlocoDefinicoes2 & other)
{
  blococonstante_ = other.blococonstante_->clone();
  blocodefinicoes_ = other.blocodefinicoes_->clone();

}

BlocoDefinicoes2 &BlocoDefinicoes2::operator=(const BlocoDefinicoes2 & other)
{
  BlocoDefinicoes2 tmp(other);
  swap(tmp);
  return *this;
}

void BlocoDefinicoes2::swap(BlocoDefinicoes2 & other)
{
  std::swap(blococonstante_, other.blococonstante_);
  std::swap(blocodefinicoes_, other.blocodefinicoes_);

}

BlocoDefinicoes2::~BlocoDefinicoes2()
{
  delete(blococonstante_);
  delete(blocodefinicoes_);

}

void BlocoDefinicoes2::accept(Visitor *v)
{
  v->visitBlocoDefinicoes2(this);
}

BlocoDefinicoes2 *BlocoDefinicoes2::clone() const
{
  return new BlocoDefinicoes2(*this);
}



/********************   BlocoDefinicoes3    ********************/
BlocoDefinicoes3::BlocoDefinicoes3(BlocoTipo *p1, BlocoDefinicoes *p2)
{
  blocotipo_ = p1;
  blocodefinicoes_ = p2;

}

BlocoDefinicoes3::BlocoDefinicoes3(const BlocoDefinicoes3 & other)
{
  blocotipo_ = other.blocotipo_->clone();
  blocodefinicoes_ = other.blocodefinicoes_->clone();

}

BlocoDefinicoes3 &BlocoDefinicoes3::operator=(const BlocoDefinicoes3 & other)
{
  BlocoDefinicoes3 tmp(other);
  swap(tmp);
  return *this;
}

void BlocoDefinicoes3::swap(BlocoDefinicoes3 & other)
{
  std::swap(blocotipo_, other.blocotipo_);
  std::swap(blocodefinicoes_, other.blocodefinicoes_);

}

BlocoDefinicoes3::~BlocoDefinicoes3()
{
  delete(blocotipo_);
  delete(blocodefinicoes_);

}

void BlocoDefinicoes3::accept(Visitor *v)
{
  v->visitBlocoDefinicoes3(this);
}

BlocoDefinicoes3 *BlocoDefinicoes3::clone() const
{
  return new BlocoDefinicoes3(*this);
}



/********************   BlocoDefinicoes4    ********************/
BlocoDefinicoes4::BlocoDefinicoes4(BlocoVar *p1, BlocoDefinicoes *p2)
{
  blocovar_ = p1;
  blocodefinicoes_ = p2;

}

BlocoDefinicoes4::BlocoDefinicoes4(const BlocoDefinicoes4 & other)
{
  blocovar_ = other.blocovar_->clone();
  blocodefinicoes_ = other.blocodefinicoes_->clone();

}

BlocoDefinicoes4 &BlocoDefinicoes4::operator=(const BlocoDefinicoes4 & other)
{
  BlocoDefinicoes4 tmp(other);
  swap(tmp);
  return *this;
}

void BlocoDefinicoes4::swap(BlocoDefinicoes4 & other)
{
  std::swap(blocovar_, other.blocovar_);
  std::swap(blocodefinicoes_, other.blocodefinicoes_);

}

BlocoDefinicoes4::~BlocoDefinicoes4()
{
  delete(blocovar_);
  delete(blocodefinicoes_);

}

void BlocoDefinicoes4::accept(Visitor *v)
{
  v->visitBlocoDefinicoes4(this);
}

BlocoDefinicoes4 *BlocoDefinicoes4::clone() const
{
  return new BlocoDefinicoes4(*this);
}



/********************   BlocoDefinicoes_    ********************/
BlocoDefinicoes_::BlocoDefinicoes_()
{

}

BlocoDefinicoes_::BlocoDefinicoes_(const BlocoDefinicoes_ & other)
{

}

BlocoDefinicoes_ &BlocoDefinicoes_::operator=(const BlocoDefinicoes_ & other)
{
  BlocoDefinicoes_ tmp(other);
  swap(tmp);
  return *this;
}

void BlocoDefinicoes_::swap(BlocoDefinicoes_ & other)
{

}

BlocoDefinicoes_::~BlocoDefinicoes_()
{

}

void BlocoDefinicoes_::accept(Visitor *v)
{
  v->visitBlocoDefinicoes_(this);
}

BlocoDefinicoes_ *BlocoDefinicoes_::clone() const
{
  return new BlocoDefinicoes_(*this);
}



/********************   BlocoFuncaoEProcFuncao    ********************/
BlocoFuncaoEProcFuncao::BlocoFuncaoEProcFuncao(Funcao *p1)
{
  funcao_ = p1;

}

BlocoFuncaoEProcFuncao::BlocoFuncaoEProcFuncao(const BlocoFuncaoEProcFuncao & other)
{
  funcao_ = other.funcao_->clone();

}

BlocoFuncaoEProcFuncao &BlocoFuncaoEProcFuncao::operator=(const BlocoFuncaoEProcFuncao & other)
{
  BlocoFuncaoEProcFuncao tmp(other);
  swap(tmp);
  return *this;
}

void BlocoFuncaoEProcFuncao::swap(BlocoFuncaoEProcFuncao & other)
{
  std::swap(funcao_, other.funcao_);

}

BlocoFuncaoEProcFuncao::~BlocoFuncaoEProcFuncao()
{
  delete(funcao_);

}

void BlocoFuncaoEProcFuncao::accept(Visitor *v)
{
  v->visitBlocoFuncaoEProcFuncao(this);
}

BlocoFuncaoEProcFuncao *BlocoFuncaoEProcFuncao::clone() const
{
  return new BlocoFuncaoEProcFuncao(*this);
}



/********************   BlocoFuncaoEProc1    ********************/
BlocoFuncaoEProc1::BlocoFuncaoEProc1(Funcao *p1, BlocoFuncaoEProc *p2)
{
  funcao_ = p1;
  blocofuncaoeproc_ = p2;

}

BlocoFuncaoEProc1::BlocoFuncaoEProc1(const BlocoFuncaoEProc1 & other)
{
  funcao_ = other.funcao_->clone();
  blocofuncaoeproc_ = other.blocofuncaoeproc_->clone();

}

BlocoFuncaoEProc1 &BlocoFuncaoEProc1::operator=(const BlocoFuncaoEProc1 & other)
{
  BlocoFuncaoEProc1 tmp(other);
  swap(tmp);
  return *this;
}

void BlocoFuncaoEProc1::swap(BlocoFuncaoEProc1 & other)
{
  std::swap(funcao_, other.funcao_);
  std::swap(blocofuncaoeproc_, other.blocofuncaoeproc_);

}

BlocoFuncaoEProc1::~BlocoFuncaoEProc1()
{
  delete(funcao_);
  delete(blocofuncaoeproc_);

}

void BlocoFuncaoEProc1::accept(Visitor *v)
{
  v->visitBlocoFuncaoEProc1(this);
}

BlocoFuncaoEProc1 *BlocoFuncaoEProc1::clone() const
{
  return new BlocoFuncaoEProc1(*this);
}



/********************   BlocoFuncaoEProcProcedimento    ********************/
BlocoFuncaoEProcProcedimento::BlocoFuncaoEProcProcedimento(Procedimento *p1)
{
  procedimento_ = p1;

}

BlocoFuncaoEProcProcedimento::BlocoFuncaoEProcProcedimento(const BlocoFuncaoEProcProcedimento & other)
{
  procedimento_ = other.procedimento_->clone();

}

BlocoFuncaoEProcProcedimento &BlocoFuncaoEProcProcedimento::operator=(const BlocoFuncaoEProcProcedimento & other)
{
  BlocoFuncaoEProcProcedimento tmp(other);
  swap(tmp);
  return *this;
}

void BlocoFuncaoEProcProcedimento::swap(BlocoFuncaoEProcProcedimento & other)
{
  std::swap(procedimento_, other.procedimento_);

}

BlocoFuncaoEProcProcedimento::~BlocoFuncaoEProcProcedimento()
{
  delete(procedimento_);

}

void BlocoFuncaoEProcProcedimento::accept(Visitor *v)
{
  v->visitBlocoFuncaoEProcProcedimento(this);
}

BlocoFuncaoEProcProcedimento *BlocoFuncaoEProcProcedimento::clone() const
{
  return new BlocoFuncaoEProcProcedimento(*this);
}



/********************   BlocoFuncaoEProc2    ********************/
BlocoFuncaoEProc2::BlocoFuncaoEProc2(Procedimento *p1, BlocoFuncaoEProc *p2)
{
  procedimento_ = p1;
  blocofuncaoeproc_ = p2;

}

BlocoFuncaoEProc2::BlocoFuncaoEProc2(const BlocoFuncaoEProc2 & other)
{
  procedimento_ = other.procedimento_->clone();
  blocofuncaoeproc_ = other.blocofuncaoeproc_->clone();

}

BlocoFuncaoEProc2 &BlocoFuncaoEProc2::operator=(const BlocoFuncaoEProc2 & other)
{
  BlocoFuncaoEProc2 tmp(other);
  swap(tmp);
  return *this;
}

void BlocoFuncaoEProc2::swap(BlocoFuncaoEProc2 & other)
{
  std::swap(procedimento_, other.procedimento_);
  std::swap(blocofuncaoeproc_, other.blocofuncaoeproc_);

}

BlocoFuncaoEProc2::~BlocoFuncaoEProc2()
{
  delete(procedimento_);
  delete(blocofuncaoeproc_);

}

void BlocoFuncaoEProc2::accept(Visitor *v)
{
  v->visitBlocoFuncaoEProc2(this);
}

BlocoFuncaoEProc2 *BlocoFuncaoEProc2::clone() const
{
  return new BlocoFuncaoEProc2(*this);
}



/********************   BlocoFuncaoEProc_    ********************/
BlocoFuncaoEProc_::BlocoFuncaoEProc_()
{

}

BlocoFuncaoEProc_::BlocoFuncaoEProc_(const BlocoFuncaoEProc_ & other)
{

}

BlocoFuncaoEProc_ &BlocoFuncaoEProc_::operator=(const BlocoFuncaoEProc_ & other)
{
  BlocoFuncaoEProc_ tmp(other);
  swap(tmp);
  return *this;
}

void BlocoFuncaoEProc_::swap(BlocoFuncaoEProc_ & other)
{

}

BlocoFuncaoEProc_::~BlocoFuncaoEProc_()
{

}

void BlocoFuncaoEProc_::accept(Visitor *v)
{
  v->visitBlocoFuncaoEProc_(this);
}

BlocoFuncaoEProc_ *BlocoFuncaoEProc_::clone() const
{
  return new BlocoFuncaoEProc_(*this);
}



/********************   BlocoConstante1    ********************/
BlocoConstante1::BlocoConstante1(RegraBlocoConstante *p1)
{
  regrablococonstante_ = p1;

}

BlocoConstante1::BlocoConstante1(const BlocoConstante1 & other)
{
  regrablococonstante_ = other.regrablococonstante_->clone();

}

BlocoConstante1 &BlocoConstante1::operator=(const BlocoConstante1 & other)
{
  BlocoConstante1 tmp(other);
  swap(tmp);
  return *this;
}

void BlocoConstante1::swap(BlocoConstante1 & other)
{
  std::swap(regrablococonstante_, other.regrablococonstante_);

}

BlocoConstante1::~BlocoConstante1()
{
  delete(regrablococonstante_);

}

void BlocoConstante1::accept(Visitor *v)
{
  v->visitBlocoConstante1(this);
}

BlocoConstante1 *BlocoConstante1::clone() const
{
  return new BlocoConstante1(*this);
}



/********************   BlocoConstante_    ********************/
BlocoConstante_::BlocoConstante_()
{

}

BlocoConstante_::BlocoConstante_(const BlocoConstante_ & other)
{

}

BlocoConstante_ &BlocoConstante_::operator=(const BlocoConstante_ & other)
{
  BlocoConstante_ tmp(other);
  swap(tmp);
  return *this;
}

void BlocoConstante_::swap(BlocoConstante_ & other)
{

}

BlocoConstante_::~BlocoConstante_()
{

}

void BlocoConstante_::accept(Visitor *v)
{
  v->visitBlocoConstante_(this);
}

BlocoConstante_ *BlocoConstante_::clone() const
{
  return new BlocoConstante_(*this);
}



/********************   RegraBlocoConstante1    ********************/
RegraBlocoConstante1::RegraBlocoConstante1(Ident p1, Valor *p2)
{
  ident_ = p1;
  valor_ = p2;

}

RegraBlocoConstante1::RegraBlocoConstante1(const RegraBlocoConstante1 & other)
{
  ident_ = other.ident_;
  valor_ = other.valor_->clone();

}

RegraBlocoConstante1 &RegraBlocoConstante1::operator=(const RegraBlocoConstante1 & other)
{
  RegraBlocoConstante1 tmp(other);
  swap(tmp);
  return *this;
}

void RegraBlocoConstante1::swap(RegraBlocoConstante1 & other)
{
  std::swap(ident_, other.ident_);
  std::swap(valor_, other.valor_);

}

RegraBlocoConstante1::~RegraBlocoConstante1()
{
  delete(valor_);

}

void RegraBlocoConstante1::accept(Visitor *v)
{
  v->visitRegraBlocoConstante1(this);
}

RegraBlocoConstante1 *RegraBlocoConstante1::clone() const
{
  return new RegraBlocoConstante1(*this);
}



/********************   RegraBlocoConstante2    ********************/
RegraBlocoConstante2::RegraBlocoConstante2(Ident p1, Valor *p2, RegraBlocoConstante *p3)
{
  ident_ = p1;
  valor_ = p2;
  regrablococonstante_ = p3;

}

RegraBlocoConstante2::RegraBlocoConstante2(const RegraBlocoConstante2 & other)
{
  ident_ = other.ident_;
  valor_ = other.valor_->clone();
  regrablococonstante_ = other.regrablococonstante_->clone();

}

RegraBlocoConstante2 &RegraBlocoConstante2::operator=(const RegraBlocoConstante2 & other)
{
  RegraBlocoConstante2 tmp(other);
  swap(tmp);
  return *this;
}

void RegraBlocoConstante2::swap(RegraBlocoConstante2 & other)
{
  std::swap(ident_, other.ident_);
  std::swap(valor_, other.valor_);
  std::swap(regrablococonstante_, other.regrablococonstante_);

}

RegraBlocoConstante2::~RegraBlocoConstante2()
{
  delete(valor_);
  delete(regrablococonstante_);

}

void RegraBlocoConstante2::accept(Visitor *v)
{
  v->visitRegraBlocoConstante2(this);
}

RegraBlocoConstante2 *RegraBlocoConstante2::clone() const
{
  return new RegraBlocoConstante2(*this);
}



/********************   BlocoTipo1    ********************/
BlocoTipo1::BlocoTipo1(RegraBlocoTipo *p1)
{
  regrablocotipo_ = p1;

}

BlocoTipo1::BlocoTipo1(const BlocoTipo1 & other)
{
  regrablocotipo_ = other.regrablocotipo_->clone();

}

BlocoTipo1 &BlocoTipo1::operator=(const BlocoTipo1 & other)
{
  BlocoTipo1 tmp(other);
  swap(tmp);
  return *this;
}

void BlocoTipo1::swap(BlocoTipo1 & other)
{
  std::swap(regrablocotipo_, other.regrablocotipo_);

}

BlocoTipo1::~BlocoTipo1()
{
  delete(regrablocotipo_);

}

void BlocoTipo1::accept(Visitor *v)
{
  v->visitBlocoTipo1(this);
}

BlocoTipo1 *BlocoTipo1::clone() const
{
  return new BlocoTipo1(*this);
}



/********************   BlocoTipo_    ********************/
BlocoTipo_::BlocoTipo_()
{

}

BlocoTipo_::BlocoTipo_(const BlocoTipo_ & other)
{

}

BlocoTipo_ &BlocoTipo_::operator=(const BlocoTipo_ & other)
{
  BlocoTipo_ tmp(other);
  swap(tmp);
  return *this;
}

void BlocoTipo_::swap(BlocoTipo_ & other)
{

}

BlocoTipo_::~BlocoTipo_()
{

}

void BlocoTipo_::accept(Visitor *v)
{
  v->visitBlocoTipo_(this);
}

BlocoTipo_ *BlocoTipo_::clone() const
{
  return new BlocoTipo_(*this);
}



/********************   RegraBlocoTipo1    ********************/
RegraBlocoTipo1::RegraBlocoTipo1(Ident p1, RegraTipo *p2)
{
  ident_ = p1;
  regratipo_ = p2;

}

RegraBlocoTipo1::RegraBlocoTipo1(const RegraBlocoTipo1 & other)
{
  ident_ = other.ident_;
  regratipo_ = other.regratipo_->clone();

}

RegraBlocoTipo1 &RegraBlocoTipo1::operator=(const RegraBlocoTipo1 & other)
{
  RegraBlocoTipo1 tmp(other);
  swap(tmp);
  return *this;
}

void RegraBlocoTipo1::swap(RegraBlocoTipo1 & other)
{
  std::swap(ident_, other.ident_);
  std::swap(regratipo_, other.regratipo_);

}

RegraBlocoTipo1::~RegraBlocoTipo1()
{
  delete(regratipo_);

}

void RegraBlocoTipo1::accept(Visitor *v)
{
  v->visitRegraBlocoTipo1(this);
}

RegraBlocoTipo1 *RegraBlocoTipo1::clone() const
{
  return new RegraBlocoTipo1(*this);
}



/********************   RegraBlocoTipo2    ********************/
RegraBlocoTipo2::RegraBlocoTipo2(Ident p1, RegraTipo *p2, RegraBlocoTipo *p3)
{
  ident_ = p1;
  regratipo_ = p2;
  regrablocotipo_ = p3;

}

RegraBlocoTipo2::RegraBlocoTipo2(const RegraBlocoTipo2 & other)
{
  ident_ = other.ident_;
  regratipo_ = other.regratipo_->clone();
  regrablocotipo_ = other.regrablocotipo_->clone();

}

RegraBlocoTipo2 &RegraBlocoTipo2::operator=(const RegraBlocoTipo2 & other)
{
  RegraBlocoTipo2 tmp(other);
  swap(tmp);
  return *this;
}

void RegraBlocoTipo2::swap(RegraBlocoTipo2 & other)
{
  std::swap(ident_, other.ident_);
  std::swap(regratipo_, other.regratipo_);
  std::swap(regrablocotipo_, other.regrablocotipo_);

}

RegraBlocoTipo2::~RegraBlocoTipo2()
{
  delete(regratipo_);
  delete(regrablocotipo_);

}

void RegraBlocoTipo2::accept(Visitor *v)
{
  v->visitRegraBlocoTipo2(this);
}

RegraBlocoTipo2 *RegraBlocoTipo2::clone() const
{
  return new RegraBlocoTipo2(*this);
}



/********************   BlocoVar1    ********************/
BlocoVar1::BlocoVar1(RegraBlocoVar *p1)
{
  regrablocovar_ = p1;

}

BlocoVar1::BlocoVar1(const BlocoVar1 & other)
{
  regrablocovar_ = other.regrablocovar_->clone();

}

BlocoVar1 &BlocoVar1::operator=(const BlocoVar1 & other)
{
  BlocoVar1 tmp(other);
  swap(tmp);
  return *this;
}

void BlocoVar1::swap(BlocoVar1 & other)
{
  std::swap(regrablocovar_, other.regrablocovar_);

}

BlocoVar1::~BlocoVar1()
{
  delete(regrablocovar_);

}

void BlocoVar1::accept(Visitor *v)
{
  v->visitBlocoVar1(this);
}

BlocoVar1 *BlocoVar1::clone() const
{
  return new BlocoVar1(*this);
}



/********************   BlocoVar_    ********************/
BlocoVar_::BlocoVar_()
{

}

BlocoVar_::BlocoVar_(const BlocoVar_ & other)
{

}

BlocoVar_ &BlocoVar_::operator=(const BlocoVar_ & other)
{
  BlocoVar_ tmp(other);
  swap(tmp);
  return *this;
}

void BlocoVar_::swap(BlocoVar_ & other)
{

}

BlocoVar_::~BlocoVar_()
{

}

void BlocoVar_::accept(Visitor *v)
{
  v->visitBlocoVar_(this);
}

BlocoVar_ *BlocoVar_::clone() const
{
  return new BlocoVar_(*this);
}



/********************   RegraBlocoVar1    ********************/
RegraBlocoVar1::RegraBlocoVar1(Ident p1, RegraTipo *p2)
{
  ident_ = p1;
  regratipo_ = p2;

}

RegraBlocoVar1::RegraBlocoVar1(const RegraBlocoVar1 & other)
{
  ident_ = other.ident_;
  regratipo_ = other.regratipo_->clone();

}

RegraBlocoVar1 &RegraBlocoVar1::operator=(const RegraBlocoVar1 & other)
{
  RegraBlocoVar1 tmp(other);
  swap(tmp);
  return *this;
}

void RegraBlocoVar1::swap(RegraBlocoVar1 & other)
{
  std::swap(ident_, other.ident_);
  std::swap(regratipo_, other.regratipo_);

}

RegraBlocoVar1::~RegraBlocoVar1()
{
  delete(regratipo_);

}

void RegraBlocoVar1::accept(Visitor *v)
{
  v->visitRegraBlocoVar1(this);
}

RegraBlocoVar1 *RegraBlocoVar1::clone() const
{
  return new RegraBlocoVar1(*this);
}



/********************   RegraBlocoVar2    ********************/
RegraBlocoVar2::RegraBlocoVar2(Ident p1, RegraTipo *p2, RegraBlocoVar *p3)
{
  ident_ = p1;
  regratipo_ = p2;
  regrablocovar_ = p3;

}

RegraBlocoVar2::RegraBlocoVar2(const RegraBlocoVar2 & other)
{
  ident_ = other.ident_;
  regratipo_ = other.regratipo_->clone();
  regrablocovar_ = other.regrablocovar_->clone();

}

RegraBlocoVar2 &RegraBlocoVar2::operator=(const RegraBlocoVar2 & other)
{
  RegraBlocoVar2 tmp(other);
  swap(tmp);
  return *this;
}

void RegraBlocoVar2::swap(RegraBlocoVar2 & other)
{
  std::swap(ident_, other.ident_);
  std::swap(regratipo_, other.regratipo_);
  std::swap(regrablocovar_, other.regrablocovar_);

}

RegraBlocoVar2::~RegraBlocoVar2()
{
  delete(regratipo_);
  delete(regrablocovar_);

}

void RegraBlocoVar2::accept(Visitor *v)
{
  v->visitRegraBlocoVar2(this);
}

RegraBlocoVar2 *RegraBlocoVar2::clone() const
{
  return new RegraBlocoVar2(*this);
}



/********************   RegraBlocoVar3    ********************/
RegraBlocoVar3::RegraBlocoVar3(ListaIdent *p1, RegraTipo *p2)
{
  listaident_ = p1;
  regratipo_ = p2;

}

RegraBlocoVar3::RegraBlocoVar3(const RegraBlocoVar3 & other)
{
  listaident_ = other.listaident_->clone();
  regratipo_ = other.regratipo_->clone();

}

RegraBlocoVar3 &RegraBlocoVar3::operator=(const RegraBlocoVar3 & other)
{
  RegraBlocoVar3 tmp(other);
  swap(tmp);
  return *this;
}

void RegraBlocoVar3::swap(RegraBlocoVar3 & other)
{
  std::swap(listaident_, other.listaident_);
  std::swap(regratipo_, other.regratipo_);

}

RegraBlocoVar3::~RegraBlocoVar3()
{
  delete(listaident_);
  delete(regratipo_);

}

void RegraBlocoVar3::accept(Visitor *v)
{
  v->visitRegraBlocoVar3(this);
}

RegraBlocoVar3 *RegraBlocoVar3::clone() const
{
  return new RegraBlocoVar3(*this);
}



/********************   RegraBlocoVar4    ********************/
RegraBlocoVar4::RegraBlocoVar4(ListaIdent *p1, RegraTipo *p2, RegraBlocoVar *p3)
{
  listaident_ = p1;
  regratipo_ = p2;
  regrablocovar_ = p3;

}

RegraBlocoVar4::RegraBlocoVar4(const RegraBlocoVar4 & other)
{
  listaident_ = other.listaident_->clone();
  regratipo_ = other.regratipo_->clone();
  regrablocovar_ = other.regrablocovar_->clone();

}

RegraBlocoVar4 &RegraBlocoVar4::operator=(const RegraBlocoVar4 & other)
{
  RegraBlocoVar4 tmp(other);
  swap(tmp);
  return *this;
}

void RegraBlocoVar4::swap(RegraBlocoVar4 & other)
{
  std::swap(listaident_, other.listaident_);
  std::swap(regratipo_, other.regratipo_);
  std::swap(regrablocovar_, other.regrablocovar_);

}

RegraBlocoVar4::~RegraBlocoVar4()
{
  delete(listaident_);
  delete(regratipo_);
  delete(regrablocovar_);

}

void RegraBlocoVar4::accept(Visitor *v)
{
  v->visitRegraBlocoVar4(this);
}

RegraBlocoVar4 *RegraBlocoVar4::clone() const
{
  return new RegraBlocoVar4(*this);
}



/********************   BlocoComando1    ********************/
BlocoComando1::BlocoComando1(RegraComando *p1)
{
  regracomando_ = p1;

}

BlocoComando1::BlocoComando1(const BlocoComando1 & other)
{
  regracomando_ = other.regracomando_->clone();

}

BlocoComando1 &BlocoComando1::operator=(const BlocoComando1 & other)
{
  BlocoComando1 tmp(other);
  swap(tmp);
  return *this;
}

void BlocoComando1::swap(BlocoComando1 & other)
{
  std::swap(regracomando_, other.regracomando_);

}

BlocoComando1::~BlocoComando1()
{
  delete(regracomando_);

}

void BlocoComando1::accept(Visitor *v)
{
  v->visitBlocoComando1(this);
}

BlocoComando1 *BlocoComando1::clone() const
{
  return new BlocoComando1(*this);
}



/********************   BlocoComando_    ********************/
BlocoComando_::BlocoComando_()
{

}

BlocoComando_::BlocoComando_(const BlocoComando_ & other)
{

}

BlocoComando_ &BlocoComando_::operator=(const BlocoComando_ & other)
{
  BlocoComando_ tmp(other);
  swap(tmp);
  return *this;
}

void BlocoComando_::swap(BlocoComando_ & other)
{

}

BlocoComando_::~BlocoComando_()
{

}

void BlocoComando_::accept(Visitor *v)
{
  v->visitBlocoComando_(this);
}

BlocoComando_ *BlocoComando_::clone() const
{
  return new BlocoComando_(*this);
}



/********************   RegraComando1    ********************/
RegraComando1::RegraComando1(Comando *p1)
{
  comando_ = p1;

}

RegraComando1::RegraComando1(const RegraComando1 & other)
{
  comando_ = other.comando_->clone();

}

RegraComando1 &RegraComando1::operator=(const RegraComando1 & other)
{
  RegraComando1 tmp(other);
  swap(tmp);
  return *this;
}

void RegraComando1::swap(RegraComando1 & other)
{
  std::swap(comando_, other.comando_);

}

RegraComando1::~RegraComando1()
{
  delete(comando_);

}

void RegraComando1::accept(Visitor *v)
{
  v->visitRegraComando1(this);
}

RegraComando1 *RegraComando1::clone() const
{
  return new RegraComando1(*this);
}



/********************   RegraComando2    ********************/
RegraComando2::RegraComando2(Comando *p1, RegraComando *p2)
{
  comando_ = p1;
  regracomando_ = p2;

}

RegraComando2::RegraComando2(const RegraComando2 & other)
{
  comando_ = other.comando_->clone();
  regracomando_ = other.regracomando_->clone();

}

RegraComando2 &RegraComando2::operator=(const RegraComando2 & other)
{
  RegraComando2 tmp(other);
  swap(tmp);
  return *this;
}

void RegraComando2::swap(RegraComando2 & other)
{
  std::swap(comando_, other.comando_);
  std::swap(regracomando_, other.regracomando_);

}

RegraComando2::~RegraComando2()
{
  delete(comando_);
  delete(regracomando_);

}

void RegraComando2::accept(Visitor *v)
{
  v->visitRegraComando2(this);
}

RegraComando2 *RegraComando2::clone() const
{
  return new RegraComando2(*this);
}



/********************   ComandoAtribuicao    ********************/
ComandoAtribuicao::ComandoAtribuicao(Atribuicao *p1)
{
  atribuicao_ = p1;

}

ComandoAtribuicao::ComandoAtribuicao(const ComandoAtribuicao & other)
{
  atribuicao_ = other.atribuicao_->clone();

}

ComandoAtribuicao &ComandoAtribuicao::operator=(const ComandoAtribuicao & other)
{
  ComandoAtribuicao tmp(other);
  swap(tmp);
  return *this;
}

void ComandoAtribuicao::swap(ComandoAtribuicao & other)
{
  std::swap(atribuicao_, other.atribuicao_);

}

ComandoAtribuicao::~ComandoAtribuicao()
{
  delete(atribuicao_);

}

void ComandoAtribuicao::accept(Visitor *v)
{
  v->visitComandoAtribuicao(this);
}

ComandoAtribuicao *ComandoAtribuicao::clone() const
{
  return new ComandoAtribuicao(*this);
}



/********************   ComandoIf    ********************/
ComandoIf::ComandoIf(If *p1)
{
  if_ = p1;

}

ComandoIf::ComandoIf(const ComandoIf & other)
{
  if_ = other.if_->clone();

}

ComandoIf &ComandoIf::operator=(const ComandoIf & other)
{
  ComandoIf tmp(other);
  swap(tmp);
  return *this;
}

void ComandoIf::swap(ComandoIf & other)
{
  std::swap(if_, other.if_);

}

ComandoIf::~ComandoIf()
{
  delete(if_);

}

void ComandoIf::accept(Visitor *v)
{
  v->visitComandoIf(this);
}

ComandoIf *ComandoIf::clone() const
{
  return new ComandoIf(*this);
}



/********************   ComandoWhile    ********************/
ComandoWhile::ComandoWhile(While *p1)
{
  while_ = p1;

}

ComandoWhile::ComandoWhile(const ComandoWhile & other)
{
  while_ = other.while_->clone();

}

ComandoWhile &ComandoWhile::operator=(const ComandoWhile & other)
{
  ComandoWhile tmp(other);
  swap(tmp);
  return *this;
}

void ComandoWhile::swap(ComandoWhile & other)
{
  std::swap(while_, other.while_);

}

ComandoWhile::~ComandoWhile()
{
  delete(while_);

}

void ComandoWhile::accept(Visitor *v)
{
  v->visitComandoWhile(this);
}

ComandoWhile *ComandoWhile::clone() const
{
  return new ComandoWhile(*this);
}



/********************   ComandoFor    ********************/
ComandoFor::ComandoFor(For *p1)
{
  for_ = p1;

}

ComandoFor::ComandoFor(const ComandoFor & other)
{
  for_ = other.for_->clone();

}

ComandoFor &ComandoFor::operator=(const ComandoFor & other)
{
  ComandoFor tmp(other);
  swap(tmp);
  return *this;
}

void ComandoFor::swap(ComandoFor & other)
{
  std::swap(for_, other.for_);

}

ComandoFor::~ComandoFor()
{
  delete(for_);

}

void ComandoFor::accept(Visitor *v)
{
  v->visitComandoFor(this);
}

ComandoFor *ComandoFor::clone() const
{
  return new ComandoFor(*this);
}



/********************   ComandoGoto    ********************/
ComandoGoto::ComandoGoto(Goto *p1)
{
  goto_ = p1;

}

ComandoGoto::ComandoGoto(const ComandoGoto & other)
{
  goto_ = other.goto_->clone();

}

ComandoGoto &ComandoGoto::operator=(const ComandoGoto & other)
{
  ComandoGoto tmp(other);
  swap(tmp);
  return *this;
}

void ComandoGoto::swap(ComandoGoto & other)
{
  std::swap(goto_, other.goto_);

}

ComandoGoto::~ComandoGoto()
{
  delete(goto_);

}

void ComandoGoto::accept(Visitor *v)
{
  v->visitComandoGoto(this);
}

ComandoGoto *ComandoGoto::clone() const
{
  return new ComandoGoto(*this);
}



/********************   ComandoCase    ********************/
ComandoCase::ComandoCase(Case *p1)
{
  case_ = p1;

}

ComandoCase::ComandoCase(const ComandoCase & other)
{
  case_ = other.case_->clone();

}

ComandoCase &ComandoCase::operator=(const ComandoCase & other)
{
  ComandoCase tmp(other);
  swap(tmp);
  return *this;
}

void ComandoCase::swap(ComandoCase & other)
{
  std::swap(case_, other.case_);

}

ComandoCase::~ComandoCase()
{
  delete(case_);

}

void ComandoCase::accept(Visitor *v)
{
  v->visitComandoCase(this);
}

ComandoCase *ComandoCase::clone() const
{
  return new ComandoCase(*this);
}



/********************   ComandoChamadaFuncaoEProc    ********************/
ComandoChamadaFuncaoEProc::ComandoChamadaFuncaoEProc(ChamadaFuncaoEProc *p1)
{
  chamadafuncaoeproc_ = p1;

}

ComandoChamadaFuncaoEProc::ComandoChamadaFuncaoEProc(const ComandoChamadaFuncaoEProc & other)
{
  chamadafuncaoeproc_ = other.chamadafuncaoeproc_->clone();

}

ComandoChamadaFuncaoEProc &ComandoChamadaFuncaoEProc::operator=(const ComandoChamadaFuncaoEProc & other)
{
  ComandoChamadaFuncaoEProc tmp(other);
  swap(tmp);
  return *this;
}

void ComandoChamadaFuncaoEProc::swap(ComandoChamadaFuncaoEProc & other)
{
  std::swap(chamadafuncaoeproc_, other.chamadafuncaoeproc_);

}

ComandoChamadaFuncaoEProc::~ComandoChamadaFuncaoEProc()
{
  delete(chamadafuncaoeproc_);

}

void ComandoChamadaFuncaoEProc::accept(Visitor *v)
{
  v->visitComandoChamadaFuncaoEProc(this);
}

ComandoChamadaFuncaoEProc *ComandoChamadaFuncaoEProc::clone() const
{
  return new ComandoChamadaFuncaoEProc(*this);
}



/********************   Atribuicao1    ********************/
Atribuicao1::Atribuicao1(Ident p1, Valor *p2)
{
  ident_ = p1;
  valor_ = p2;

}

Atribuicao1::Atribuicao1(const Atribuicao1 & other)
{
  ident_ = other.ident_;
  valor_ = other.valor_->clone();

}

Atribuicao1 &Atribuicao1::operator=(const Atribuicao1 & other)
{
  Atribuicao1 tmp(other);
  swap(tmp);
  return *this;
}

void Atribuicao1::swap(Atribuicao1 & other)
{
  std::swap(ident_, other.ident_);
  std::swap(valor_, other.valor_);

}

Atribuicao1::~Atribuicao1()
{
  delete(valor_);

}

void Atribuicao1::accept(Visitor *v)
{
  v->visitAtribuicao1(this);
}

Atribuicao1 *Atribuicao1::clone() const
{
  return new Atribuicao1(*this);
}



/********************   Atribuicao2    ********************/
Atribuicao2::Atribuicao2(Ident p1, ExpressaoAritmetica *p2)
{
  ident_ = p1;
  expressaoaritmetica_ = p2;

}

Atribuicao2::Atribuicao2(const Atribuicao2 & other)
{
  ident_ = other.ident_;
  expressaoaritmetica_ = other.expressaoaritmetica_->clone();

}

Atribuicao2 &Atribuicao2::operator=(const Atribuicao2 & other)
{
  Atribuicao2 tmp(other);
  swap(tmp);
  return *this;
}

void Atribuicao2::swap(Atribuicao2 & other)
{
  std::swap(ident_, other.ident_);
  std::swap(expressaoaritmetica_, other.expressaoaritmetica_);

}

Atribuicao2::~Atribuicao2()
{
  delete(expressaoaritmetica_);

}

void Atribuicao2::accept(Visitor *v)
{
  v->visitAtribuicao2(this);
}

Atribuicao2 *Atribuicao2::clone() const
{
  return new Atribuicao2(*this);
}



/********************   Atribuicao3    ********************/
Atribuicao3::Atribuicao3(Ident p1, Ident p2)
{
  ident_1 = p1;
  ident_2 = p2;

}

Atribuicao3::Atribuicao3(const Atribuicao3 & other)
{
  ident_1 = other.ident_1;
  ident_2 = other.ident_2;

}

Atribuicao3 &Atribuicao3::operator=(const Atribuicao3 & other)
{
  Atribuicao3 tmp(other);
  swap(tmp);
  return *this;
}

void Atribuicao3::swap(Atribuicao3 & other)
{
  std::swap(ident_1, other.ident_1);
  std::swap(ident_2, other.ident_2);

}

Atribuicao3::~Atribuicao3()
{

}

void Atribuicao3::accept(Visitor *v)
{
  v->visitAtribuicao3(this);
}

Atribuicao3 *Atribuicao3::clone() const
{
  return new Atribuicao3(*this);
}



/********************   Atribuicao4    ********************/
Atribuicao4::Atribuicao4(Ident p1, SubEscrito *p2, Valor *p3)
{
  ident_ = p1;
  subescrito_ = p2;
  valor_ = p3;

}

Atribuicao4::Atribuicao4(const Atribuicao4 & other)
{
  ident_ = other.ident_;
  subescrito_ = other.subescrito_->clone();
  valor_ = other.valor_->clone();

}

Atribuicao4 &Atribuicao4::operator=(const Atribuicao4 & other)
{
  Atribuicao4 tmp(other);
  swap(tmp);
  return *this;
}

void Atribuicao4::swap(Atribuicao4 & other)
{
  std::swap(ident_, other.ident_);
  std::swap(subescrito_, other.subescrito_);
  std::swap(valor_, other.valor_);

}

Atribuicao4::~Atribuicao4()
{
  delete(subescrito_);
  delete(valor_);

}

void Atribuicao4::accept(Visitor *v)
{
  v->visitAtribuicao4(this);
}

Atribuicao4 *Atribuicao4::clone() const
{
  return new Atribuicao4(*this);
}



/********************   Atribuicao5    ********************/
Atribuicao5::Atribuicao5(Ident p1, Valor *p2)
{
  ident_ = p1;
  valor_ = p2;

}

Atribuicao5::Atribuicao5(const Atribuicao5 & other)
{
  ident_ = other.ident_;
  valor_ = other.valor_->clone();

}

Atribuicao5 &Atribuicao5::operator=(const Atribuicao5 & other)
{
  Atribuicao5 tmp(other);
  swap(tmp);
  return *this;
}

void Atribuicao5::swap(Atribuicao5 & other)
{
  std::swap(ident_, other.ident_);
  std::swap(valor_, other.valor_);

}

Atribuicao5::~Atribuicao5()
{
  delete(valor_);

}

void Atribuicao5::accept(Visitor *v)
{
  v->visitAtribuicao5(this);
}

Atribuicao5 *Atribuicao5::clone() const
{
  return new Atribuicao5(*this);
}



/********************   AtribuicaoAtribuicaoStruct    ********************/
AtribuicaoAtribuicaoStruct::AtribuicaoAtribuicaoStruct(AtribuicaoStruct *p1)
{
  atribuicaostruct_ = p1;

}

AtribuicaoAtribuicaoStruct::AtribuicaoAtribuicaoStruct(const AtribuicaoAtribuicaoStruct & other)
{
  atribuicaostruct_ = other.atribuicaostruct_->clone();

}

AtribuicaoAtribuicaoStruct &AtribuicaoAtribuicaoStruct::operator=(const AtribuicaoAtribuicaoStruct & other)
{
  AtribuicaoAtribuicaoStruct tmp(other);
  swap(tmp);
  return *this;
}

void AtribuicaoAtribuicaoStruct::swap(AtribuicaoAtribuicaoStruct & other)
{
  std::swap(atribuicaostruct_, other.atribuicaostruct_);

}

AtribuicaoAtribuicaoStruct::~AtribuicaoAtribuicaoStruct()
{
  delete(atribuicaostruct_);

}

void AtribuicaoAtribuicaoStruct::accept(Visitor *v)
{
  v->visitAtribuicaoAtribuicaoStruct(this);
}

AtribuicaoAtribuicaoStruct *AtribuicaoAtribuicaoStruct::clone() const
{
  return new AtribuicaoAtribuicaoStruct(*this);
}



/********************   Atribuicao6    ********************/
Atribuicao6::Atribuicao6(Ident p1, ChamadaFuncaoEProc *p2)
{
  ident_ = p1;
  chamadafuncaoeproc_ = p2;

}

Atribuicao6::Atribuicao6(const Atribuicao6 & other)
{
  ident_ = other.ident_;
  chamadafuncaoeproc_ = other.chamadafuncaoeproc_->clone();

}

Atribuicao6 &Atribuicao6::operator=(const Atribuicao6 & other)
{
  Atribuicao6 tmp(other);
  swap(tmp);
  return *this;
}

void Atribuicao6::swap(Atribuicao6 & other)
{
  std::swap(ident_, other.ident_);
  std::swap(chamadafuncaoeproc_, other.chamadafuncaoeproc_);

}

Atribuicao6::~Atribuicao6()
{
  delete(chamadafuncaoeproc_);

}

void Atribuicao6::accept(Visitor *v)
{
  v->visitAtribuicao6(this);
}

Atribuicao6 *Atribuicao6::clone() const
{
  return new Atribuicao6(*this);
}



/********************   SubEscritoIdent    ********************/
SubEscritoIdent::SubEscritoIdent(Ident p1)
{
  ident_ = p1;

}

SubEscritoIdent::SubEscritoIdent(const SubEscritoIdent & other)
{
  ident_ = other.ident_;

}

SubEscritoIdent &SubEscritoIdent::operator=(const SubEscritoIdent & other)
{
  SubEscritoIdent tmp(other);
  swap(tmp);
  return *this;
}

void SubEscritoIdent::swap(SubEscritoIdent & other)
{
  std::swap(ident_, other.ident_);

}

SubEscritoIdent::~SubEscritoIdent()
{

}

void SubEscritoIdent::accept(Visitor *v)
{
  v->visitSubEscritoIdent(this);
}

SubEscritoIdent *SubEscritoIdent::clone() const
{
  return new SubEscritoIdent(*this);
}



/********************   SubEscritoInteger    ********************/
SubEscritoInteger::SubEscritoInteger(Integer p1)
{
  integer_ = p1;

}

SubEscritoInteger::SubEscritoInteger(const SubEscritoInteger & other)
{
  integer_ = other.integer_;

}

SubEscritoInteger &SubEscritoInteger::operator=(const SubEscritoInteger & other)
{
  SubEscritoInteger tmp(other);
  swap(tmp);
  return *this;
}

void SubEscritoInteger::swap(SubEscritoInteger & other)
{
  std::swap(integer_, other.integer_);

}

SubEscritoInteger::~SubEscritoInteger()
{

}

void SubEscritoInteger::accept(Visitor *v)
{
  v->visitSubEscritoInteger(this);
}

SubEscritoInteger *SubEscritoInteger::clone() const
{
  return new SubEscritoInteger(*this);
}



/********************   RegraTipoTipoPrimitivo    ********************/
RegraTipoTipoPrimitivo::RegraTipoTipoPrimitivo(TipoPrimitivo *p1)
{
  tipoprimitivo_ = p1;

}

RegraTipoTipoPrimitivo::RegraTipoTipoPrimitivo(const RegraTipoTipoPrimitivo & other)
{
  tipoprimitivo_ = other.tipoprimitivo_->clone();

}

RegraTipoTipoPrimitivo &RegraTipoTipoPrimitivo::operator=(const RegraTipoTipoPrimitivo & other)
{
  RegraTipoTipoPrimitivo tmp(other);
  swap(tmp);
  return *this;
}

void RegraTipoTipoPrimitivo::swap(RegraTipoTipoPrimitivo & other)
{
  std::swap(tipoprimitivo_, other.tipoprimitivo_);

}

RegraTipoTipoPrimitivo::~RegraTipoTipoPrimitivo()
{
  delete(tipoprimitivo_);

}

void RegraTipoTipoPrimitivo::accept(Visitor *v)
{
  v->visitRegraTipoTipoPrimitivo(this);
}

RegraTipoTipoPrimitivo *RegraTipoTipoPrimitivo::clone() const
{
  return new RegraTipoTipoPrimitivo(*this);
}



/********************   RegraTipoTipoDerivado    ********************/
RegraTipoTipoDerivado::RegraTipoTipoDerivado(TipoDerivado *p1)
{
  tipoderivado_ = p1;

}

RegraTipoTipoDerivado::RegraTipoTipoDerivado(const RegraTipoTipoDerivado & other)
{
  tipoderivado_ = other.tipoderivado_->clone();

}

RegraTipoTipoDerivado &RegraTipoTipoDerivado::operator=(const RegraTipoTipoDerivado & other)
{
  RegraTipoTipoDerivado tmp(other);
  swap(tmp);
  return *this;
}

void RegraTipoTipoDerivado::swap(RegraTipoTipoDerivado & other)
{
  std::swap(tipoderivado_, other.tipoderivado_);

}

RegraTipoTipoDerivado::~RegraTipoTipoDerivado()
{
  delete(tipoderivado_);

}

void RegraTipoTipoDerivado::accept(Visitor *v)
{
  v->visitRegraTipoTipoDerivado(this);
}

RegraTipoTipoDerivado *RegraTipoTipoDerivado::clone() const
{
  return new RegraTipoTipoDerivado(*this);
}



/********************   RegraTipoIdent    ********************/
RegraTipoIdent::RegraTipoIdent(Ident p1)
{
  ident_ = p1;

}

RegraTipoIdent::RegraTipoIdent(const RegraTipoIdent & other)
{
  ident_ = other.ident_;

}

RegraTipoIdent &RegraTipoIdent::operator=(const RegraTipoIdent & other)
{
  RegraTipoIdent tmp(other);
  swap(tmp);
  return *this;
}

void RegraTipoIdent::swap(RegraTipoIdent & other)
{
  std::swap(ident_, other.ident_);

}

RegraTipoIdent::~RegraTipoIdent()
{

}

void RegraTipoIdent::accept(Visitor *v)
{
  v->visitRegraTipoIdent(this);
}

RegraTipoIdent *RegraTipoIdent::clone() const
{
  return new RegraTipoIdent(*this);
}



/********************   TipoPrimitivo_int    ********************/
TipoPrimitivo_int::TipoPrimitivo_int()
{

}

TipoPrimitivo_int::TipoPrimitivo_int(const TipoPrimitivo_int & other)
{

}

TipoPrimitivo_int &TipoPrimitivo_int::operator=(const TipoPrimitivo_int & other)
{
  TipoPrimitivo_int tmp(other);
  swap(tmp);
  return *this;
}

void TipoPrimitivo_int::swap(TipoPrimitivo_int & other)
{

}

TipoPrimitivo_int::~TipoPrimitivo_int()
{

}

void TipoPrimitivo_int::accept(Visitor *v)
{
  v->visitTipoPrimitivo_int(this);
}

TipoPrimitivo_int *TipoPrimitivo_int::clone() const
{
  return new TipoPrimitivo_int(*this);
}



/********************   TipoPrimitivo_real    ********************/
TipoPrimitivo_real::TipoPrimitivo_real()
{

}

TipoPrimitivo_real::TipoPrimitivo_real(const TipoPrimitivo_real & other)
{

}

TipoPrimitivo_real &TipoPrimitivo_real::operator=(const TipoPrimitivo_real & other)
{
  TipoPrimitivo_real tmp(other);
  swap(tmp);
  return *this;
}

void TipoPrimitivo_real::swap(TipoPrimitivo_real & other)
{

}

TipoPrimitivo_real::~TipoPrimitivo_real()
{

}

void TipoPrimitivo_real::accept(Visitor *v)
{
  v->visitTipoPrimitivo_real(this);
}

TipoPrimitivo_real *TipoPrimitivo_real::clone() const
{
  return new TipoPrimitivo_real(*this);
}



/********************   TipoPrimitivo_char    ********************/
TipoPrimitivo_char::TipoPrimitivo_char()
{

}

TipoPrimitivo_char::TipoPrimitivo_char(const TipoPrimitivo_char & other)
{

}

TipoPrimitivo_char &TipoPrimitivo_char::operator=(const TipoPrimitivo_char & other)
{
  TipoPrimitivo_char tmp(other);
  swap(tmp);
  return *this;
}

void TipoPrimitivo_char::swap(TipoPrimitivo_char & other)
{

}

TipoPrimitivo_char::~TipoPrimitivo_char()
{

}

void TipoPrimitivo_char::accept(Visitor *v)
{
  v->visitTipoPrimitivo_char(this);
}

TipoPrimitivo_char *TipoPrimitivo_char::clone() const
{
  return new TipoPrimitivo_char(*this);
}



/********************   ValorInteger    ********************/
ValorInteger::ValorInteger(Integer p1)
{
  integer_ = p1;

}

ValorInteger::ValorInteger(const ValorInteger & other)
{
  integer_ = other.integer_;

}

ValorInteger &ValorInteger::operator=(const ValorInteger & other)
{
  ValorInteger tmp(other);
  swap(tmp);
  return *this;
}

void ValorInteger::swap(ValorInteger & other)
{
  std::swap(integer_, other.integer_);

}

ValorInteger::~ValorInteger()
{

}

void ValorInteger::accept(Visitor *v)
{
  v->visitValorInteger(this);
}

ValorInteger *ValorInteger::clone() const
{
  return new ValorInteger(*this);
}



/********************   ValorDouble    ********************/
ValorDouble::ValorDouble(Double p1)
{
  double_ = p1;

}

ValorDouble::ValorDouble(const ValorDouble & other)
{
  double_ = other.double_;

}

ValorDouble &ValorDouble::operator=(const ValorDouble & other)
{
  ValorDouble tmp(other);
  swap(tmp);
  return *this;
}

void ValorDouble::swap(ValorDouble & other)
{
  std::swap(double_, other.double_);

}

ValorDouble::~ValorDouble()
{

}

void ValorDouble::accept(Visitor *v)
{
  v->visitValorDouble(this);
}

ValorDouble *ValorDouble::clone() const
{
  return new ValorDouble(*this);
}



/********************   ValorChar    ********************/
ValorChar::ValorChar(Char p1)
{
  char_ = p1;

}

ValorChar::ValorChar(const ValorChar & other)
{
  char_ = other.char_;

}

ValorChar &ValorChar::operator=(const ValorChar & other)
{
  ValorChar tmp(other);
  swap(tmp);
  return *this;
}

void ValorChar::swap(ValorChar & other)
{
  std::swap(char_, other.char_);

}

ValorChar::~ValorChar()
{

}

void ValorChar::accept(Visitor *v)
{
  v->visitValorChar(this);
}

ValorChar *ValorChar::clone() const
{
  return new ValorChar(*this);
}



/********************   ValorString    ********************/
ValorString::ValorString(String p1)
{
  string_ = p1;

}

ValorString::ValorString(const ValorString & other)
{
  string_ = other.string_;

}

ValorString &ValorString::operator=(const ValorString & other)
{
  ValorString tmp(other);
  swap(tmp);
  return *this;
}

void ValorString::swap(ValorString & other)
{
  std::swap(string_, other.string_);

}

ValorString::~ValorString()
{

}

void ValorString::accept(Visitor *v)
{
  v->visitValorString(this);
}

ValorString *ValorString::clone() const
{
  return new ValorString(*this);
}



/********************   TipoDerivadoPonteiro    ********************/
TipoDerivadoPonteiro::TipoDerivadoPonteiro(Ponteiro *p1)
{
  ponteiro_ = p1;

}

TipoDerivadoPonteiro::TipoDerivadoPonteiro(const TipoDerivadoPonteiro & other)
{
  ponteiro_ = other.ponteiro_->clone();

}

TipoDerivadoPonteiro &TipoDerivadoPonteiro::operator=(const TipoDerivadoPonteiro & other)
{
  TipoDerivadoPonteiro tmp(other);
  swap(tmp);
  return *this;
}

void TipoDerivadoPonteiro::swap(TipoDerivadoPonteiro & other)
{
  std::swap(ponteiro_, other.ponteiro_);

}

TipoDerivadoPonteiro::~TipoDerivadoPonteiro()
{
  delete(ponteiro_);

}

void TipoDerivadoPonteiro::accept(Visitor *v)
{
  v->visitTipoDerivadoPonteiro(this);
}

TipoDerivadoPonteiro *TipoDerivadoPonteiro::clone() const
{
  return new TipoDerivadoPonteiro(*this);
}



/********************   TipoDerivadoVetor    ********************/
TipoDerivadoVetor::TipoDerivadoVetor(Vetor *p1)
{
  vetor_ = p1;

}

TipoDerivadoVetor::TipoDerivadoVetor(const TipoDerivadoVetor & other)
{
  vetor_ = other.vetor_->clone();

}

TipoDerivadoVetor &TipoDerivadoVetor::operator=(const TipoDerivadoVetor & other)
{
  TipoDerivadoVetor tmp(other);
  swap(tmp);
  return *this;
}

void TipoDerivadoVetor::swap(TipoDerivadoVetor & other)
{
  std::swap(vetor_, other.vetor_);

}

TipoDerivadoVetor::~TipoDerivadoVetor()
{
  delete(vetor_);

}

void TipoDerivadoVetor::accept(Visitor *v)
{
  v->visitTipoDerivadoVetor(this);
}

TipoDerivadoVetor *TipoDerivadoVetor::clone() const
{
  return new TipoDerivadoVetor(*this);
}



/********************   TipoDerivadoStruct    ********************/
TipoDerivadoStruct::TipoDerivadoStruct(Struct *p1)
{
  struct_ = p1;

}

TipoDerivadoStruct::TipoDerivadoStruct(const TipoDerivadoStruct & other)
{
  struct_ = other.struct_->clone();

}

TipoDerivadoStruct &TipoDerivadoStruct::operator=(const TipoDerivadoStruct & other)
{
  TipoDerivadoStruct tmp(other);
  swap(tmp);
  return *this;
}

void TipoDerivadoStruct::swap(TipoDerivadoStruct & other)
{
  std::swap(struct_, other.struct_);

}

TipoDerivadoStruct::~TipoDerivadoStruct()
{
  delete(struct_);

}

void TipoDerivadoStruct::accept(Visitor *v)
{
  v->visitTipoDerivadoStruct(this);
}

TipoDerivadoStruct *TipoDerivadoStruct::clone() const
{
  return new TipoDerivadoStruct(*this);
}



/********************   Ponteiro1    ********************/
Ponteiro1::Ponteiro1(TipoPrimitivo *p1)
{
  tipoprimitivo_ = p1;

}

Ponteiro1::Ponteiro1(const Ponteiro1 & other)
{
  tipoprimitivo_ = other.tipoprimitivo_->clone();

}

Ponteiro1 &Ponteiro1::operator=(const Ponteiro1 & other)
{
  Ponteiro1 tmp(other);
  swap(tmp);
  return *this;
}

void Ponteiro1::swap(Ponteiro1 & other)
{
  std::swap(tipoprimitivo_, other.tipoprimitivo_);

}

Ponteiro1::~Ponteiro1()
{
  delete(tipoprimitivo_);

}

void Ponteiro1::accept(Visitor *v)
{
  v->visitPonteiro1(this);
}

Ponteiro1 *Ponteiro1::clone() const
{
  return new Ponteiro1(*this);
}



/********************   Ponteiro2    ********************/
Ponteiro2::Ponteiro2(TipoDerivado *p1)
{
  tipoderivado_ = p1;

}

Ponteiro2::Ponteiro2(const Ponteiro2 & other)
{
  tipoderivado_ = other.tipoderivado_->clone();

}

Ponteiro2 &Ponteiro2::operator=(const Ponteiro2 & other)
{
  Ponteiro2 tmp(other);
  swap(tmp);
  return *this;
}

void Ponteiro2::swap(Ponteiro2 & other)
{
  std::swap(tipoderivado_, other.tipoderivado_);

}

Ponteiro2::~Ponteiro2()
{
  delete(tipoderivado_);

}

void Ponteiro2::accept(Visitor *v)
{
  v->visitPonteiro2(this);
}

Ponteiro2 *Ponteiro2::clone() const
{
  return new Ponteiro2(*this);
}



/********************   LVetor    ********************/
LVetor::LVetor(Integer p1, Integer p2, TipoPrimitivo *p3)
{
  integer_1 = p1;
  integer_2 = p2;
  tipoprimitivo_ = p3;

}

LVetor::LVetor(const LVetor & other)
{
  integer_1 = other.integer_1;
  integer_2 = other.integer_2;
  tipoprimitivo_ = other.tipoprimitivo_->clone();

}

LVetor &LVetor::operator=(const LVetor & other)
{
  LVetor tmp(other);
  swap(tmp);
  return *this;
}

void LVetor::swap(LVetor & other)
{
  std::swap(integer_1, other.integer_1);
  std::swap(integer_2, other.integer_2);
  std::swap(tipoprimitivo_, other.tipoprimitivo_);

}

LVetor::~LVetor()
{
  delete(tipoprimitivo_);

}

void LVetor::accept(Visitor *v)
{
  v->visitLVetor(this);
}

LVetor *LVetor::clone() const
{
  return new LVetor(*this);
}



/********************   If1    ********************/
If1::If1(ExpressaoLogica *p1, BlocoComando *p2)
{
  expressaologica_ = p1;
  blococomando_ = p2;

}

If1::If1(const If1 & other)
{
  expressaologica_ = other.expressaologica_->clone();
  blococomando_ = other.blococomando_->clone();

}

If1 &If1::operator=(const If1 & other)
{
  If1 tmp(other);
  swap(tmp);
  return *this;
}

void If1::swap(If1 & other)
{
  std::swap(expressaologica_, other.expressaologica_);
  std::swap(blococomando_, other.blococomando_);

}

If1::~If1()
{
  delete(expressaologica_);
  delete(blococomando_);

}

void If1::accept(Visitor *v)
{
  v->visitIf1(this);
}

If1 *If1::clone() const
{
  return new If1(*this);
}



/********************   If2    ********************/
If2::If2(ExpressaoLogica *p1, BlocoComando *p2, BlocoComando *p3)
{
  expressaologica_ = p1;
  blococomando_1 = p2;
  blococomando_2 = p3;

}

If2::If2(const If2 & other)
{
  expressaologica_ = other.expressaologica_->clone();
  blococomando_1 = other.blococomando_1->clone();
  blococomando_2 = other.blococomando_2->clone();

}

If2 &If2::operator=(const If2 & other)
{
  If2 tmp(other);
  swap(tmp);
  return *this;
}

void If2::swap(If2 & other)
{
  std::swap(expressaologica_, other.expressaologica_);
  std::swap(blococomando_1, other.blococomando_1);
  std::swap(blococomando_2, other.blococomando_2);

}

If2::~If2()
{
  delete(expressaologica_);
  delete(blococomando_1);
  delete(blococomando_2);

}

void If2::accept(Visitor *v)
{
  v->visitIf2(this);
}

If2 *If2::clone() const
{
  return new If2(*this);
}



/********************   LWhile    ********************/
LWhile::LWhile(ExpressaoLogica *p1, BlocoComando *p2)
{
  expressaologica_ = p1;
  blococomando_ = p2;

}

LWhile::LWhile(const LWhile & other)
{
  expressaologica_ = other.expressaologica_->clone();
  blococomando_ = other.blococomando_->clone();

}

LWhile &LWhile::operator=(const LWhile & other)
{
  LWhile tmp(other);
  swap(tmp);
  return *this;
}

void LWhile::swap(LWhile & other)
{
  std::swap(expressaologica_, other.expressaologica_);
  std::swap(blococomando_, other.blococomando_);

}

LWhile::~LWhile()
{
  delete(expressaologica_);
  delete(blococomando_);

}

void LWhile::accept(Visitor *v)
{
  v->visitLWhile(this);
}

LWhile *LWhile::clone() const
{
  return new LWhile(*this);
}



/********************   For1    ********************/
For1::For1(Atribuicao *p1, Integer p2, BlocoComando *p3)
{
  atribuicao_ = p1;
  integer_ = p2;
  blococomando_ = p3;

}

For1::For1(const For1 & other)
{
  atribuicao_ = other.atribuicao_->clone();
  integer_ = other.integer_;
  blococomando_ = other.blococomando_->clone();

}

For1 &For1::operator=(const For1 & other)
{
  For1 tmp(other);
  swap(tmp);
  return *this;
}

void For1::swap(For1 & other)
{
  std::swap(atribuicao_, other.atribuicao_);
  std::swap(integer_, other.integer_);
  std::swap(blococomando_, other.blococomando_);

}

For1::~For1()
{
  delete(atribuicao_);
  delete(blococomando_);

}

void For1::accept(Visitor *v)
{
  v->visitFor1(this);
}

For1 *For1::clone() const
{
  return new For1(*this);
}



/********************   For2    ********************/
For2::For2(Atribuicao *p1, Ident p2, BlocoComando *p3)
{
  atribuicao_ = p1;
  ident_ = p2;
  blococomando_ = p3;

}

For2::For2(const For2 & other)
{
  atribuicao_ = other.atribuicao_->clone();
  ident_ = other.ident_;
  blococomando_ = other.blococomando_->clone();

}

For2 &For2::operator=(const For2 & other)
{
  For2 tmp(other);
  swap(tmp);
  return *this;
}

void For2::swap(For2 & other)
{
  std::swap(atribuicao_, other.atribuicao_);
  std::swap(ident_, other.ident_);
  std::swap(blococomando_, other.blococomando_);

}

For2::~For2()
{
  delete(atribuicao_);
  delete(blococomando_);

}

void For2::accept(Visitor *v)
{
  v->visitFor2(this);
}

For2 *For2::clone() const
{
  return new For2(*this);
}



/********************   LGoto    ********************/
LGoto::LGoto(Ident p1)
{
  ident_ = p1;

}

LGoto::LGoto(const LGoto & other)
{
  ident_ = other.ident_;

}

LGoto &LGoto::operator=(const LGoto & other)
{
  LGoto tmp(other);
  swap(tmp);
  return *this;
}

void LGoto::swap(LGoto & other)
{
  std::swap(ident_, other.ident_);

}

LGoto::~LGoto()
{

}

void LGoto::accept(Visitor *v)
{
  v->visitLGoto(this);
}

LGoto *LGoto::clone() const
{
  return new LGoto(*this);
}



/********************   LRotulo    ********************/
LRotulo::LRotulo(Ident p1, RegraComando *p2)
{
  ident_ = p1;
  regracomando_ = p2;

}

LRotulo::LRotulo(const LRotulo & other)
{
  ident_ = other.ident_;
  regracomando_ = other.regracomando_->clone();

}

LRotulo &LRotulo::operator=(const LRotulo & other)
{
  LRotulo tmp(other);
  swap(tmp);
  return *this;
}

void LRotulo::swap(LRotulo & other)
{
  std::swap(ident_, other.ident_);
  std::swap(regracomando_, other.regracomando_);

}

LRotulo::~LRotulo()
{
  delete(regracomando_);

}

void LRotulo::accept(Visitor *v)
{
  v->visitLRotulo(this);
}

LRotulo *LRotulo::clone() const
{
  return new LRotulo(*this);
}



/********************   LStruct    ********************/
LStruct::LStruct(DefinicaoCampoStruct *p1)
{
  definicaocampostruct_ = p1;

}

LStruct::LStruct(const LStruct & other)
{
  definicaocampostruct_ = other.definicaocampostruct_->clone();

}

LStruct &LStruct::operator=(const LStruct & other)
{
  LStruct tmp(other);
  swap(tmp);
  return *this;
}

void LStruct::swap(LStruct & other)
{
  std::swap(definicaocampostruct_, other.definicaocampostruct_);

}

LStruct::~LStruct()
{
  delete(definicaocampostruct_);

}

void LStruct::accept(Visitor *v)
{
  v->visitLStruct(this);
}

LStruct *LStruct::clone() const
{
  return new LStruct(*this);
}



/********************   DefinicaoCampoStruct1    ********************/
DefinicaoCampoStruct1::DefinicaoCampoStruct1(Ident p1, RegraTipo *p2)
{
  ident_ = p1;
  regratipo_ = p2;

}

DefinicaoCampoStruct1::DefinicaoCampoStruct1(const DefinicaoCampoStruct1 & other)
{
  ident_ = other.ident_;
  regratipo_ = other.regratipo_->clone();

}

DefinicaoCampoStruct1 &DefinicaoCampoStruct1::operator=(const DefinicaoCampoStruct1 & other)
{
  DefinicaoCampoStruct1 tmp(other);
  swap(tmp);
  return *this;
}

void DefinicaoCampoStruct1::swap(DefinicaoCampoStruct1 & other)
{
  std::swap(ident_, other.ident_);
  std::swap(regratipo_, other.regratipo_);

}

DefinicaoCampoStruct1::~DefinicaoCampoStruct1()
{
  delete(regratipo_);

}

void DefinicaoCampoStruct1::accept(Visitor *v)
{
  v->visitDefinicaoCampoStruct1(this);
}

DefinicaoCampoStruct1 *DefinicaoCampoStruct1::clone() const
{
  return new DefinicaoCampoStruct1(*this);
}



/********************   DefinicaoCampoStruct2    ********************/
DefinicaoCampoStruct2::DefinicaoCampoStruct2(Ident p1, RegraTipo *p2, DefinicaoCampoStruct *p3)
{
  ident_ = p1;
  regratipo_ = p2;
  definicaocampostruct_ = p3;

}

DefinicaoCampoStruct2::DefinicaoCampoStruct2(const DefinicaoCampoStruct2 & other)
{
  ident_ = other.ident_;
  regratipo_ = other.regratipo_->clone();
  definicaocampostruct_ = other.definicaocampostruct_->clone();

}

DefinicaoCampoStruct2 &DefinicaoCampoStruct2::operator=(const DefinicaoCampoStruct2 & other)
{
  DefinicaoCampoStruct2 tmp(other);
  swap(tmp);
  return *this;
}

void DefinicaoCampoStruct2::swap(DefinicaoCampoStruct2 & other)
{
  std::swap(ident_, other.ident_);
  std::swap(regratipo_, other.regratipo_);
  std::swap(definicaocampostruct_, other.definicaocampostruct_);

}

DefinicaoCampoStruct2::~DefinicaoCampoStruct2()
{
  delete(regratipo_);
  delete(definicaocampostruct_);

}

void DefinicaoCampoStruct2::accept(Visitor *v)
{
  v->visitDefinicaoCampoStruct2(this);
}

DefinicaoCampoStruct2 *DefinicaoCampoStruct2::clone() const
{
  return new DefinicaoCampoStruct2(*this);
}



/********************   AtribuicaoStruct1    ********************/
AtribuicaoStruct1::AtribuicaoStruct1(Ident p1, Ident p2, Valor *p3)
{
  ident_1 = p1;
  ident_2 = p2;
  valor_ = p3;

}

AtribuicaoStruct1::AtribuicaoStruct1(const AtribuicaoStruct1 & other)
{
  ident_1 = other.ident_1;
  ident_2 = other.ident_2;
  valor_ = other.valor_->clone();

}

AtribuicaoStruct1 &AtribuicaoStruct1::operator=(const AtribuicaoStruct1 & other)
{
  AtribuicaoStruct1 tmp(other);
  swap(tmp);
  return *this;
}

void AtribuicaoStruct1::swap(AtribuicaoStruct1 & other)
{
  std::swap(ident_1, other.ident_1);
  std::swap(ident_2, other.ident_2);
  std::swap(valor_, other.valor_);

}

AtribuicaoStruct1::~AtribuicaoStruct1()
{
  delete(valor_);

}

void AtribuicaoStruct1::accept(Visitor *v)
{
  v->visitAtribuicaoStruct1(this);
}

AtribuicaoStruct1 *AtribuicaoStruct1::clone() const
{
  return new AtribuicaoStruct1(*this);
}



/********************   AtribuicaoStruct2    ********************/
AtribuicaoStruct2::AtribuicaoStruct2(Ident p1, Ident p2, Valor *p3, AtribuicaoStruct *p4)
{
  ident_1 = p1;
  ident_2 = p2;
  valor_ = p3;
  atribuicaostruct_ = p4;

}

AtribuicaoStruct2::AtribuicaoStruct2(const AtribuicaoStruct2 & other)
{
  ident_1 = other.ident_1;
  ident_2 = other.ident_2;
  valor_ = other.valor_->clone();
  atribuicaostruct_ = other.atribuicaostruct_->clone();

}

AtribuicaoStruct2 &AtribuicaoStruct2::operator=(const AtribuicaoStruct2 & other)
{
  AtribuicaoStruct2 tmp(other);
  swap(tmp);
  return *this;
}

void AtribuicaoStruct2::swap(AtribuicaoStruct2 & other)
{
  std::swap(ident_1, other.ident_1);
  std::swap(ident_2, other.ident_2);
  std::swap(valor_, other.valor_);
  std::swap(atribuicaostruct_, other.atribuicaostruct_);

}

AtribuicaoStruct2::~AtribuicaoStruct2()
{
  delete(valor_);
  delete(atribuicaostruct_);

}

void AtribuicaoStruct2::accept(Visitor *v)
{
  v->visitAtribuicaoStruct2(this);
}

AtribuicaoStruct2 *AtribuicaoStruct2::clone() const
{
  return new AtribuicaoStruct2(*this);
}



/********************   OperadorRelacional1    ********************/
OperadorRelacional1::OperadorRelacional1()
{

}

OperadorRelacional1::OperadorRelacional1(const OperadorRelacional1 & other)
{

}

OperadorRelacional1 &OperadorRelacional1::operator=(const OperadorRelacional1 & other)
{
  OperadorRelacional1 tmp(other);
  swap(tmp);
  return *this;
}

void OperadorRelacional1::swap(OperadorRelacional1 & other)
{

}

OperadorRelacional1::~OperadorRelacional1()
{

}

void OperadorRelacional1::accept(Visitor *v)
{
  v->visitOperadorRelacional1(this);
}

OperadorRelacional1 *OperadorRelacional1::clone() const
{
  return new OperadorRelacional1(*this);
}



/********************   OperadorRelacional2    ********************/
OperadorRelacional2::OperadorRelacional2()
{

}

OperadorRelacional2::OperadorRelacional2(const OperadorRelacional2 & other)
{

}

OperadorRelacional2 &OperadorRelacional2::operator=(const OperadorRelacional2 & other)
{
  OperadorRelacional2 tmp(other);
  swap(tmp);
  return *this;
}

void OperadorRelacional2::swap(OperadorRelacional2 & other)
{

}

OperadorRelacional2::~OperadorRelacional2()
{

}

void OperadorRelacional2::accept(Visitor *v)
{
  v->visitOperadorRelacional2(this);
}

OperadorRelacional2 *OperadorRelacional2::clone() const
{
  return new OperadorRelacional2(*this);
}



/********************   OperadorRelacional3    ********************/
OperadorRelacional3::OperadorRelacional3()
{

}

OperadorRelacional3::OperadorRelacional3(const OperadorRelacional3 & other)
{

}

OperadorRelacional3 &OperadorRelacional3::operator=(const OperadorRelacional3 & other)
{
  OperadorRelacional3 tmp(other);
  swap(tmp);
  return *this;
}

void OperadorRelacional3::swap(OperadorRelacional3 & other)
{

}

OperadorRelacional3::~OperadorRelacional3()
{

}

void OperadorRelacional3::accept(Visitor *v)
{
  v->visitOperadorRelacional3(this);
}

OperadorRelacional3 *OperadorRelacional3::clone() const
{
  return new OperadorRelacional3(*this);
}



/********************   OperadorRelacional4    ********************/
OperadorRelacional4::OperadorRelacional4()
{

}

OperadorRelacional4::OperadorRelacional4(const OperadorRelacional4 & other)
{

}

OperadorRelacional4 &OperadorRelacional4::operator=(const OperadorRelacional4 & other)
{
  OperadorRelacional4 tmp(other);
  swap(tmp);
  return *this;
}

void OperadorRelacional4::swap(OperadorRelacional4 & other)
{

}

OperadorRelacional4::~OperadorRelacional4()
{

}

void OperadorRelacional4::accept(Visitor *v)
{
  v->visitOperadorRelacional4(this);
}

OperadorRelacional4 *OperadorRelacional4::clone() const
{
  return new OperadorRelacional4(*this);
}



/********************   OperadorRelacional5    ********************/
OperadorRelacional5::OperadorRelacional5()
{

}

OperadorRelacional5::OperadorRelacional5(const OperadorRelacional5 & other)
{

}

OperadorRelacional5 &OperadorRelacional5::operator=(const OperadorRelacional5 & other)
{
  OperadorRelacional5 tmp(other);
  swap(tmp);
  return *this;
}

void OperadorRelacional5::swap(OperadorRelacional5 & other)
{

}

OperadorRelacional5::~OperadorRelacional5()
{

}

void OperadorRelacional5::accept(Visitor *v)
{
  v->visitOperadorRelacional5(this);
}

OperadorRelacional5 *OperadorRelacional5::clone() const
{
  return new OperadorRelacional5(*this);
}



/********************   OperadorRelacional6    ********************/
OperadorRelacional6::OperadorRelacional6()
{

}

OperadorRelacional6::OperadorRelacional6(const OperadorRelacional6 & other)
{

}

OperadorRelacional6 &OperadorRelacional6::operator=(const OperadorRelacional6 & other)
{
  OperadorRelacional6 tmp(other);
  swap(tmp);
  return *this;
}

void OperadorRelacional6::swap(OperadorRelacional6 & other)
{

}

OperadorRelacional6::~OperadorRelacional6()
{

}

void OperadorRelacional6::accept(Visitor *v)
{
  v->visitOperadorRelacional6(this);
}

OperadorRelacional6 *OperadorRelacional6::clone() const
{
  return new OperadorRelacional6(*this);
}



/********************   OperadorLogico1    ********************/
OperadorLogico1::OperadorLogico1()
{

}

OperadorLogico1::OperadorLogico1(const OperadorLogico1 & other)
{

}

OperadorLogico1 &OperadorLogico1::operator=(const OperadorLogico1 & other)
{
  OperadorLogico1 tmp(other);
  swap(tmp);
  return *this;
}

void OperadorLogico1::swap(OperadorLogico1 & other)
{

}

OperadorLogico1::~OperadorLogico1()
{

}

void OperadorLogico1::accept(Visitor *v)
{
  v->visitOperadorLogico1(this);
}

OperadorLogico1 *OperadorLogico1::clone() const
{
  return new OperadorLogico1(*this);
}



/********************   OperadorLogico2    ********************/
OperadorLogico2::OperadorLogico2()
{

}

OperadorLogico2::OperadorLogico2(const OperadorLogico2 & other)
{

}

OperadorLogico2 &OperadorLogico2::operator=(const OperadorLogico2 & other)
{
  OperadorLogico2 tmp(other);
  swap(tmp);
  return *this;
}

void OperadorLogico2::swap(OperadorLogico2 & other)
{

}

OperadorLogico2::~OperadorLogico2()
{

}

void OperadorLogico2::accept(Visitor *v)
{
  v->visitOperadorLogico2(this);
}

OperadorLogico2 *OperadorLogico2::clone() const
{
  return new OperadorLogico2(*this);
}



/********************   OperadorLogico3    ********************/
OperadorLogico3::OperadorLogico3()
{

}

OperadorLogico3::OperadorLogico3(const OperadorLogico3 & other)
{

}

OperadorLogico3 &OperadorLogico3::operator=(const OperadorLogico3 & other)
{
  OperadorLogico3 tmp(other);
  swap(tmp);
  return *this;
}

void OperadorLogico3::swap(OperadorLogico3 & other)
{

}

OperadorLogico3::~OperadorLogico3()
{

}

void OperadorLogico3::accept(Visitor *v)
{
  v->visitOperadorLogico3(this);
}

OperadorLogico3 *OperadorLogico3::clone() const
{
  return new OperadorLogico3(*this);
}



/********************   OperadorLogicoNegacao    ********************/
OperadorLogicoNegacao::OperadorLogicoNegacao(Negacao *p1)
{
  negacao_ = p1;

}

OperadorLogicoNegacao::OperadorLogicoNegacao(const OperadorLogicoNegacao & other)
{
  negacao_ = other.negacao_->clone();

}

OperadorLogicoNegacao &OperadorLogicoNegacao::operator=(const OperadorLogicoNegacao & other)
{
  OperadorLogicoNegacao tmp(other);
  swap(tmp);
  return *this;
}

void OperadorLogicoNegacao::swap(OperadorLogicoNegacao & other)
{
  std::swap(negacao_, other.negacao_);

}

OperadorLogicoNegacao::~OperadorLogicoNegacao()
{
  delete(negacao_);

}

void OperadorLogicoNegacao::accept(Visitor *v)
{
  v->visitOperadorLogicoNegacao(this);
}

OperadorLogicoNegacao *OperadorLogicoNegacao::clone() const
{
  return new OperadorLogicoNegacao(*this);
}



/********************   LNegacao    ********************/
LNegacao::LNegacao()
{

}

LNegacao::LNegacao(const LNegacao & other)
{

}

LNegacao &LNegacao::operator=(const LNegacao & other)
{
  LNegacao tmp(other);
  swap(tmp);
  return *this;
}

void LNegacao::swap(LNegacao & other)
{

}

LNegacao::~LNegacao()
{

}

void LNegacao::accept(Visitor *v)
{
  v->visitLNegacao(this);
}

LNegacao *LNegacao::clone() const
{
  return new LNegacao(*this);
}



/********************   OperadorAritmetico1    ********************/
OperadorAritmetico1::OperadorAritmetico1()
{

}

OperadorAritmetico1::OperadorAritmetico1(const OperadorAritmetico1 & other)
{

}

OperadorAritmetico1 &OperadorAritmetico1::operator=(const OperadorAritmetico1 & other)
{
  OperadorAritmetico1 tmp(other);
  swap(tmp);
  return *this;
}

void OperadorAritmetico1::swap(OperadorAritmetico1 & other)
{

}

OperadorAritmetico1::~OperadorAritmetico1()
{

}

void OperadorAritmetico1::accept(Visitor *v)
{
  v->visitOperadorAritmetico1(this);
}

OperadorAritmetico1 *OperadorAritmetico1::clone() const
{
  return new OperadorAritmetico1(*this);
}



/********************   OperadorAritmetico2    ********************/
OperadorAritmetico2::OperadorAritmetico2()
{

}

OperadorAritmetico2::OperadorAritmetico2(const OperadorAritmetico2 & other)
{

}

OperadorAritmetico2 &OperadorAritmetico2::operator=(const OperadorAritmetico2 & other)
{
  OperadorAritmetico2 tmp(other);
  swap(tmp);
  return *this;
}

void OperadorAritmetico2::swap(OperadorAritmetico2 & other)
{

}

OperadorAritmetico2::~OperadorAritmetico2()
{

}

void OperadorAritmetico2::accept(Visitor *v)
{
  v->visitOperadorAritmetico2(this);
}

OperadorAritmetico2 *OperadorAritmetico2::clone() const
{
  return new OperadorAritmetico2(*this);
}



/********************   OperadorAritmetico3    ********************/
OperadorAritmetico3::OperadorAritmetico3()
{

}

OperadorAritmetico3::OperadorAritmetico3(const OperadorAritmetico3 & other)
{

}

OperadorAritmetico3 &OperadorAritmetico3::operator=(const OperadorAritmetico3 & other)
{
  OperadorAritmetico3 tmp(other);
  swap(tmp);
  return *this;
}

void OperadorAritmetico3::swap(OperadorAritmetico3 & other)
{

}

OperadorAritmetico3::~OperadorAritmetico3()
{

}

void OperadorAritmetico3::accept(Visitor *v)
{
  v->visitOperadorAritmetico3(this);
}

OperadorAritmetico3 *OperadorAritmetico3::clone() const
{
  return new OperadorAritmetico3(*this);
}



/********************   OperadorAritmetico4    ********************/
OperadorAritmetico4::OperadorAritmetico4()
{

}

OperadorAritmetico4::OperadorAritmetico4(const OperadorAritmetico4 & other)
{

}

OperadorAritmetico4 &OperadorAritmetico4::operator=(const OperadorAritmetico4 & other)
{
  OperadorAritmetico4 tmp(other);
  swap(tmp);
  return *this;
}

void OperadorAritmetico4::swap(OperadorAritmetico4 & other)
{

}

OperadorAritmetico4::~OperadorAritmetico4()
{

}

void OperadorAritmetico4::accept(Visitor *v)
{
  v->visitOperadorAritmetico4(this);
}

OperadorAritmetico4 *OperadorAritmetico4::clone() const
{
  return new OperadorAritmetico4(*this);
}



/********************   LCase    ********************/
LCase::LCase(Seletor *p1, RegraSeletor *p2)
{
  seletor_ = p1;
  regraseletor_ = p2;

}

LCase::LCase(const LCase & other)
{
  seletor_ = other.seletor_->clone();
  regraseletor_ = other.regraseletor_->clone();

}

LCase &LCase::operator=(const LCase & other)
{
  LCase tmp(other);
  swap(tmp);
  return *this;
}

void LCase::swap(LCase & other)
{
  std::swap(seletor_, other.seletor_);
  std::swap(regraseletor_, other.regraseletor_);

}

LCase::~LCase()
{
  delete(seletor_);
  delete(regraseletor_);

}

void LCase::accept(Visitor *v)
{
  v->visitLCase(this);
}

LCase *LCase::clone() const
{
  return new LCase(*this);
}



/********************   RegraSeletor1    ********************/
RegraSeletor1::RegraSeletor1(Seletor *p1, Comando *p2)
{
  seletor_ = p1;
  comando_ = p2;

}

RegraSeletor1::RegraSeletor1(const RegraSeletor1 & other)
{
  seletor_ = other.seletor_->clone();
  comando_ = other.comando_->clone();

}

RegraSeletor1 &RegraSeletor1::operator=(const RegraSeletor1 & other)
{
  RegraSeletor1 tmp(other);
  swap(tmp);
  return *this;
}

void RegraSeletor1::swap(RegraSeletor1 & other)
{
  std::swap(seletor_, other.seletor_);
  std::swap(comando_, other.comando_);

}

RegraSeletor1::~RegraSeletor1()
{
  delete(seletor_);
  delete(comando_);

}

void RegraSeletor1::accept(Visitor *v)
{
  v->visitRegraSeletor1(this);
}

RegraSeletor1 *RegraSeletor1::clone() const
{
  return new RegraSeletor1(*this);
}



/********************   RegraSeletor2    ********************/
RegraSeletor2::RegraSeletor2(Seletor *p1, Comando *p2, RegraSeletor *p3)
{
  seletor_ = p1;
  comando_ = p2;
  regraseletor_ = p3;

}

RegraSeletor2::RegraSeletor2(const RegraSeletor2 & other)
{
  seletor_ = other.seletor_->clone();
  comando_ = other.comando_->clone();
  regraseletor_ = other.regraseletor_->clone();

}

RegraSeletor2 &RegraSeletor2::operator=(const RegraSeletor2 & other)
{
  RegraSeletor2 tmp(other);
  swap(tmp);
  return *this;
}

void RegraSeletor2::swap(RegraSeletor2 & other)
{
  std::swap(seletor_, other.seletor_);
  std::swap(comando_, other.comando_);
  std::swap(regraseletor_, other.regraseletor_);

}

RegraSeletor2::~RegraSeletor2()
{
  delete(seletor_);
  delete(comando_);
  delete(regraseletor_);

}

void RegraSeletor2::accept(Visitor *v)
{
  v->visitRegraSeletor2(this);
}

RegraSeletor2 *RegraSeletor2::clone() const
{
  return new RegraSeletor2(*this);
}



/********************   SeletorInteger    ********************/
SeletorInteger::SeletorInteger(Integer p1)
{
  integer_ = p1;

}

SeletorInteger::SeletorInteger(const SeletorInteger & other)
{
  integer_ = other.integer_;

}

SeletorInteger &SeletorInteger::operator=(const SeletorInteger & other)
{
  SeletorInteger tmp(other);
  swap(tmp);
  return *this;
}

void SeletorInteger::swap(SeletorInteger & other)
{
  std::swap(integer_, other.integer_);

}

SeletorInteger::~SeletorInteger()
{

}

void SeletorInteger::accept(Visitor *v)
{
  v->visitSeletorInteger(this);
}

SeletorInteger *SeletorInteger::clone() const
{
  return new SeletorInteger(*this);
}



/********************   SeletorChar    ********************/
SeletorChar::SeletorChar(Char p1)
{
  char_ = p1;

}

SeletorChar::SeletorChar(const SeletorChar & other)
{
  char_ = other.char_;

}

SeletorChar &SeletorChar::operator=(const SeletorChar & other)
{
  SeletorChar tmp(other);
  swap(tmp);
  return *this;
}

void SeletorChar::swap(SeletorChar & other)
{
  std::swap(char_, other.char_);

}

SeletorChar::~SeletorChar()
{

}

void SeletorChar::accept(Visitor *v)
{
  v->visitSeletorChar(this);
}

SeletorChar *SeletorChar::clone() const
{
  return new SeletorChar(*this);
}



/********************   SeletorIdent    ********************/
SeletorIdent::SeletorIdent(Ident p1)
{
  ident_ = p1;

}

SeletorIdent::SeletorIdent(const SeletorIdent & other)
{
  ident_ = other.ident_;

}

SeletorIdent &SeletorIdent::operator=(const SeletorIdent & other)
{
  SeletorIdent tmp(other);
  swap(tmp);
  return *this;
}

void SeletorIdent::swap(SeletorIdent & other)
{
  std::swap(ident_, other.ident_);

}

SeletorIdent::~SeletorIdent()
{

}

void SeletorIdent::accept(Visitor *v)
{
  v->visitSeletorIdent(this);
}

SeletorIdent *SeletorIdent::clone() const
{
  return new SeletorIdent(*this);
}



/********************   LChamad    ********************/
LChamad::LChamad(Ident p1, ListaIdent *p2)
{
  ident_ = p1;
  listaident_ = p2;

}

LChamad::LChamad(const LChamad & other)
{
  ident_ = other.ident_;
  listaident_ = other.listaident_->clone();

}

LChamad &LChamad::operator=(const LChamad & other)
{
  LChamad tmp(other);
  swap(tmp);
  return *this;
}

void LChamad::swap(LChamad & other)
{
  std::swap(ident_, other.ident_);
  std::swap(listaident_, other.listaident_);

}

LChamad::~LChamad()
{
  delete(listaident_);

}

void LChamad::accept(Visitor *v)
{
  v->visitLChamad(this);
}

LChamad *LChamad::clone() const
{
  return new LChamad(*this);
}



/********************   ListaIdentIdent    ********************/
ListaIdentIdent::ListaIdentIdent(Ident p1)
{
  ident_ = p1;

}

ListaIdentIdent::ListaIdentIdent(const ListaIdentIdent & other)
{
  ident_ = other.ident_;

}

ListaIdentIdent &ListaIdentIdent::operator=(const ListaIdentIdent & other)
{
  ListaIdentIdent tmp(other);
  swap(tmp);
  return *this;
}

void ListaIdentIdent::swap(ListaIdentIdent & other)
{
  std::swap(ident_, other.ident_);

}

ListaIdentIdent::~ListaIdentIdent()
{

}

void ListaIdentIdent::accept(Visitor *v)
{
  v->visitListaIdentIdent(this);
}

ListaIdentIdent *ListaIdentIdent::clone() const
{
  return new ListaIdentIdent(*this);
}



/********************   ListaIdent1    ********************/
ListaIdent1::ListaIdent1(Ident p1, ListaIdent *p2)
{
  ident_ = p1;
  listaident_ = p2;

}

ListaIdent1::ListaIdent1(const ListaIdent1 & other)
{
  ident_ = other.ident_;
  listaident_ = other.listaident_->clone();

}

ListaIdent1 &ListaIdent1::operator=(const ListaIdent1 & other)
{
  ListaIdent1 tmp(other);
  swap(tmp);
  return *this;
}

void ListaIdent1::swap(ListaIdent1 & other)
{
  std::swap(ident_, other.ident_);
  std::swap(listaident_, other.listaident_);

}

ListaIdent1::~ListaIdent1()
{
  delete(listaident_);

}

void ListaIdent1::accept(Visitor *v)
{
  v->visitListaIdent1(this);
}

ListaIdent1 *ListaIdent1::clone() const
{
  return new ListaIdent1(*this);
}



/********************   LFuncao    ********************/
LFuncao::LFuncao(Ident p1, RegraBlocoVar *p2, RegraTipo *p3, BlocoVar *p4, BlocoComando *p5)
{
  ident_ = p1;
  regrablocovar_ = p2;
  regratipo_ = p3;
  blocovar_ = p4;
  blococomando_ = p5;

}

LFuncao::LFuncao(const LFuncao & other)
{
  ident_ = other.ident_;
  regrablocovar_ = other.regrablocovar_->clone();
  regratipo_ = other.regratipo_->clone();
  blocovar_ = other.blocovar_->clone();
  blococomando_ = other.blococomando_->clone();

}

LFuncao &LFuncao::operator=(const LFuncao & other)
{
  LFuncao tmp(other);
  swap(tmp);
  return *this;
}

void LFuncao::swap(LFuncao & other)
{
  std::swap(ident_, other.ident_);
  std::swap(regrablocovar_, other.regrablocovar_);
  std::swap(regratipo_, other.regratipo_);
  std::swap(blocovar_, other.blocovar_);
  std::swap(blococomando_, other.blococomando_);

}

LFuncao::~LFuncao()
{
  delete(regrablocovar_);
  delete(regratipo_);
  delete(blocovar_);
  delete(blococomando_);

}

void LFuncao::accept(Visitor *v)
{
  v->visitLFuncao(this);
}

LFuncao *LFuncao::clone() const
{
  return new LFuncao(*this);
}



/********************   Procedimento1    ********************/
Procedimento1::Procedimento1(Ident p1, RegraBlocoVar *p2, BlocoVar *p3, BlocoComando *p4)
{
  ident_ = p1;
  regrablocovar_ = p2;
  blocovar_ = p3;
  blococomando_ = p4;

}

Procedimento1::Procedimento1(const Procedimento1 & other)
{
  ident_ = other.ident_;
  regrablocovar_ = other.regrablocovar_->clone();
  blocovar_ = other.blocovar_->clone();
  blococomando_ = other.blococomando_->clone();

}

Procedimento1 &Procedimento1::operator=(const Procedimento1 & other)
{
  Procedimento1 tmp(other);
  swap(tmp);
  return *this;
}

void Procedimento1::swap(Procedimento1 & other)
{
  std::swap(ident_, other.ident_);
  std::swap(regrablocovar_, other.regrablocovar_);
  std::swap(blocovar_, other.blocovar_);
  std::swap(blococomando_, other.blococomando_);

}

Procedimento1::~Procedimento1()
{
  delete(regrablocovar_);
  delete(blocovar_);
  delete(blococomando_);

}

void Procedimento1::accept(Visitor *v)
{
  v->visitProcedimento1(this);
}

Procedimento1 *Procedimento1::clone() const
{
  return new Procedimento1(*this);
}



/********************   Procedimento2    ********************/
Procedimento2::Procedimento2(Ident p1, BlocoVar *p2, BlocoComando *p3)
{
  ident_ = p1;
  blocovar_ = p2;
  blococomando_ = p3;

}

Procedimento2::Procedimento2(const Procedimento2 & other)
{
  ident_ = other.ident_;
  blocovar_ = other.blocovar_->clone();
  blococomando_ = other.blococomando_->clone();

}

Procedimento2 &Procedimento2::operator=(const Procedimento2 & other)
{
  Procedimento2 tmp(other);
  swap(tmp);
  return *this;
}

void Procedimento2::swap(Procedimento2 & other)
{
  std::swap(ident_, other.ident_);
  std::swap(blocovar_, other.blocovar_);
  std::swap(blococomando_, other.blococomando_);

}

Procedimento2::~Procedimento2()
{
  delete(blocovar_);
  delete(blococomando_);

}

void Procedimento2::accept(Visitor *v)
{
  v->visitProcedimento2(this);
}

Procedimento2 *Procedimento2::clone() const
{
  return new Procedimento2(*this);
}



/********************   ExpAr    ********************/
ExpAr::ExpAr(Operando *p1, RegraAritmetica *p2)
{
  operando_ = p1;
  regraaritmetica_ = p2;

}

ExpAr::ExpAr(const ExpAr & other)
{
  operando_ = other.operando_->clone();
  regraaritmetica_ = other.regraaritmetica_->clone();

}

ExpAr &ExpAr::operator=(const ExpAr & other)
{
  ExpAr tmp(other);
  swap(tmp);
  return *this;
}

void ExpAr::swap(ExpAr & other)
{
  std::swap(operando_, other.operando_);
  std::swap(regraaritmetica_, other.regraaritmetica_);

}

ExpAr::~ExpAr()
{
  delete(operando_);
  delete(regraaritmetica_);

}

void ExpAr::accept(Visitor *v)
{
  v->visitExpAr(this);
}

ExpAr *ExpAr::clone() const
{
  return new ExpAr(*this);
}



/********************   OperandoInteger    ********************/
OperandoInteger::OperandoInteger(Integer p1)
{
  integer_ = p1;

}

OperandoInteger::OperandoInteger(const OperandoInteger & other)
{
  integer_ = other.integer_;

}

OperandoInteger &OperandoInteger::operator=(const OperandoInteger & other)
{
  OperandoInteger tmp(other);
  swap(tmp);
  return *this;
}

void OperandoInteger::swap(OperandoInteger & other)
{
  std::swap(integer_, other.integer_);

}

OperandoInteger::~OperandoInteger()
{

}

void OperandoInteger::accept(Visitor *v)
{
  v->visitOperandoInteger(this);
}

OperandoInteger *OperandoInteger::clone() const
{
  return new OperandoInteger(*this);
}



/********************   OperandoDouble    ********************/
OperandoDouble::OperandoDouble(Double p1)
{
  double_ = p1;

}

OperandoDouble::OperandoDouble(const OperandoDouble & other)
{
  double_ = other.double_;

}

OperandoDouble &OperandoDouble::operator=(const OperandoDouble & other)
{
  OperandoDouble tmp(other);
  swap(tmp);
  return *this;
}

void OperandoDouble::swap(OperandoDouble & other)
{
  std::swap(double_, other.double_);

}

OperandoDouble::~OperandoDouble()
{

}

void OperandoDouble::accept(Visitor *v)
{
  v->visitOperandoDouble(this);
}

OperandoDouble *OperandoDouble::clone() const
{
  return new OperandoDouble(*this);
}



/********************   OperandoIdent    ********************/
OperandoIdent::OperandoIdent(Ident p1)
{
  ident_ = p1;

}

OperandoIdent::OperandoIdent(const OperandoIdent & other)
{
  ident_ = other.ident_;

}

OperandoIdent &OperandoIdent::operator=(const OperandoIdent & other)
{
  OperandoIdent tmp(other);
  swap(tmp);
  return *this;
}

void OperandoIdent::swap(OperandoIdent & other)
{
  std::swap(ident_, other.ident_);

}

OperandoIdent::~OperandoIdent()
{

}

void OperandoIdent::accept(Visitor *v)
{
  v->visitOperandoIdent(this);
}

OperandoIdent *OperandoIdent::clone() const
{
  return new OperandoIdent(*this);
}



/********************   RegraAritmetica1    ********************/
RegraAritmetica1::RegraAritmetica1(OperadorAritmetico *p1, Operando *p2)
{
  operadoraritmetico_ = p1;
  operando_ = p2;

}

RegraAritmetica1::RegraAritmetica1(const RegraAritmetica1 & other)
{
  operadoraritmetico_ = other.operadoraritmetico_->clone();
  operando_ = other.operando_->clone();

}

RegraAritmetica1 &RegraAritmetica1::operator=(const RegraAritmetica1 & other)
{
  RegraAritmetica1 tmp(other);
  swap(tmp);
  return *this;
}

void RegraAritmetica1::swap(RegraAritmetica1 & other)
{
  std::swap(operadoraritmetico_, other.operadoraritmetico_);
  std::swap(operando_, other.operando_);

}

RegraAritmetica1::~RegraAritmetica1()
{
  delete(operadoraritmetico_);
  delete(operando_);

}

void RegraAritmetica1::accept(Visitor *v)
{
  v->visitRegraAritmetica1(this);
}

RegraAritmetica1 *RegraAritmetica1::clone() const
{
  return new RegraAritmetica1(*this);
}



/********************   RegraAritmetica2    ********************/
RegraAritmetica2::RegraAritmetica2(OperadorAritmetico *p1, Operando *p2, RegraAritmetica *p3)
{
  operadoraritmetico_ = p1;
  operando_ = p2;
  regraaritmetica_ = p3;

}

RegraAritmetica2::RegraAritmetica2(const RegraAritmetica2 & other)
{
  operadoraritmetico_ = other.operadoraritmetico_->clone();
  operando_ = other.operando_->clone();
  regraaritmetica_ = other.regraaritmetica_->clone();

}

RegraAritmetica2 &RegraAritmetica2::operator=(const RegraAritmetica2 & other)
{
  RegraAritmetica2 tmp(other);
  swap(tmp);
  return *this;
}

void RegraAritmetica2::swap(RegraAritmetica2 & other)
{
  std::swap(operadoraritmetico_, other.operadoraritmetico_);
  std::swap(operando_, other.operando_);
  std::swap(regraaritmetica_, other.regraaritmetica_);

}

RegraAritmetica2::~RegraAritmetica2()
{
  delete(operadoraritmetico_);
  delete(operando_);
  delete(regraaritmetica_);

}

void RegraAritmetica2::accept(Visitor *v)
{
  v->visitRegraAritmetica2(this);
}

RegraAritmetica2 *RegraAritmetica2::clone() const
{
  return new RegraAritmetica2(*this);
}



/********************   ExpressaoRelacionalOperando    ********************/
ExpressaoRelacionalOperando::ExpressaoRelacionalOperando(Operando *p1)
{
  operando_ = p1;

}

ExpressaoRelacionalOperando::ExpressaoRelacionalOperando(const ExpressaoRelacionalOperando & other)
{
  operando_ = other.operando_->clone();

}

ExpressaoRelacionalOperando &ExpressaoRelacionalOperando::operator=(const ExpressaoRelacionalOperando & other)
{
  ExpressaoRelacionalOperando tmp(other);
  swap(tmp);
  return *this;
}

void ExpressaoRelacionalOperando::swap(ExpressaoRelacionalOperando & other)
{
  std::swap(operando_, other.operando_);

}

ExpressaoRelacionalOperando::~ExpressaoRelacionalOperando()
{
  delete(operando_);

}

void ExpressaoRelacionalOperando::accept(Visitor *v)
{
  v->visitExpressaoRelacionalOperando(this);
}

ExpressaoRelacionalOperando *ExpressaoRelacionalOperando::clone() const
{
  return new ExpressaoRelacionalOperando(*this);
}



/********************   ExpressaoRelacional1    ********************/
ExpressaoRelacional1::ExpressaoRelacional1(Operando *p1, RegraRelacional *p2)
{
  operando_ = p1;
  regrarelacional_ = p2;

}

ExpressaoRelacional1::ExpressaoRelacional1(const ExpressaoRelacional1 & other)
{
  operando_ = other.operando_->clone();
  regrarelacional_ = other.regrarelacional_->clone();

}

ExpressaoRelacional1 &ExpressaoRelacional1::operator=(const ExpressaoRelacional1 & other)
{
  ExpressaoRelacional1 tmp(other);
  swap(tmp);
  return *this;
}

void ExpressaoRelacional1::swap(ExpressaoRelacional1 & other)
{
  std::swap(operando_, other.operando_);
  std::swap(regrarelacional_, other.regrarelacional_);

}

ExpressaoRelacional1::~ExpressaoRelacional1()
{
  delete(operando_);
  delete(regrarelacional_);

}

void ExpressaoRelacional1::accept(Visitor *v)
{
  v->visitExpressaoRelacional1(this);
}

ExpressaoRelacional1 *ExpressaoRelacional1::clone() const
{
  return new ExpressaoRelacional1(*this);
}



/********************   ExpressaoRelacional2    ********************/
ExpressaoRelacional2::ExpressaoRelacional2(ExpressaoAritmetica *p1, RegraRelacional *p2)
{
  expressaoaritmetica_ = p1;
  regrarelacional_ = p2;

}

ExpressaoRelacional2::ExpressaoRelacional2(const ExpressaoRelacional2 & other)
{
  expressaoaritmetica_ = other.expressaoaritmetica_->clone();
  regrarelacional_ = other.regrarelacional_->clone();

}

ExpressaoRelacional2 &ExpressaoRelacional2::operator=(const ExpressaoRelacional2 & other)
{
  ExpressaoRelacional2 tmp(other);
  swap(tmp);
  return *this;
}

void ExpressaoRelacional2::swap(ExpressaoRelacional2 & other)
{
  std::swap(expressaoaritmetica_, other.expressaoaritmetica_);
  std::swap(regrarelacional_, other.regrarelacional_);

}

ExpressaoRelacional2::~ExpressaoRelacional2()
{
  delete(expressaoaritmetica_);
  delete(regrarelacional_);

}

void ExpressaoRelacional2::accept(Visitor *v)
{
  v->visitExpressaoRelacional2(this);
}

ExpressaoRelacional2 *ExpressaoRelacional2::clone() const
{
  return new ExpressaoRelacional2(*this);
}



/********************   RegraRelacional1    ********************/
RegraRelacional1::RegraRelacional1(OperadorRelacional *p1, Operando *p2)
{
  operadorrelacional_ = p1;
  operando_ = p2;

}

RegraRelacional1::RegraRelacional1(const RegraRelacional1 & other)
{
  operadorrelacional_ = other.operadorrelacional_->clone();
  operando_ = other.operando_->clone();

}

RegraRelacional1 &RegraRelacional1::operator=(const RegraRelacional1 & other)
{
  RegraRelacional1 tmp(other);
  swap(tmp);
  return *this;
}

void RegraRelacional1::swap(RegraRelacional1 & other)
{
  std::swap(operadorrelacional_, other.operadorrelacional_);
  std::swap(operando_, other.operando_);

}

RegraRelacional1::~RegraRelacional1()
{
  delete(operadorrelacional_);
  delete(operando_);

}

void RegraRelacional1::accept(Visitor *v)
{
  v->visitRegraRelacional1(this);
}

RegraRelacional1 *RegraRelacional1::clone() const
{
  return new RegraRelacional1(*this);
}



/********************   RegraRelacional2    ********************/
RegraRelacional2::RegraRelacional2(OperadorRelacional *p1, ExpressaoAritmetica *p2)
{
  operadorrelacional_ = p1;
  expressaoaritmetica_ = p2;

}

RegraRelacional2::RegraRelacional2(const RegraRelacional2 & other)
{
  operadorrelacional_ = other.operadorrelacional_->clone();
  expressaoaritmetica_ = other.expressaoaritmetica_->clone();

}

RegraRelacional2 &RegraRelacional2::operator=(const RegraRelacional2 & other)
{
  RegraRelacional2 tmp(other);
  swap(tmp);
  return *this;
}

void RegraRelacional2::swap(RegraRelacional2 & other)
{
  std::swap(operadorrelacional_, other.operadorrelacional_);
  std::swap(expressaoaritmetica_, other.expressaoaritmetica_);

}

RegraRelacional2::~RegraRelacional2()
{
  delete(operadorrelacional_);
  delete(expressaoaritmetica_);

}

void RegraRelacional2::accept(Visitor *v)
{
  v->visitRegraRelacional2(this);
}

RegraRelacional2 *RegraRelacional2::clone() const
{
  return new RegraRelacional2(*this);
}



/********************   ExpressaoLogica_falso    ********************/
ExpressaoLogica_falso::ExpressaoLogica_falso()
{

}

ExpressaoLogica_falso::ExpressaoLogica_falso(const ExpressaoLogica_falso & other)
{

}

ExpressaoLogica_falso &ExpressaoLogica_falso::operator=(const ExpressaoLogica_falso & other)
{
  ExpressaoLogica_falso tmp(other);
  swap(tmp);
  return *this;
}

void ExpressaoLogica_falso::swap(ExpressaoLogica_falso & other)
{

}

ExpressaoLogica_falso::~ExpressaoLogica_falso()
{

}

void ExpressaoLogica_falso::accept(Visitor *v)
{
  v->visitExpressaoLogica_falso(this);
}

ExpressaoLogica_falso *ExpressaoLogica_falso::clone() const
{
  return new ExpressaoLogica_falso(*this);
}



/********************   ExpressaoLogica1    ********************/
ExpressaoLogica1::ExpressaoLogica1(RegraLogico *p1)
{
  regralogico_ = p1;

}

ExpressaoLogica1::ExpressaoLogica1(const ExpressaoLogica1 & other)
{
  regralogico_ = other.regralogico_->clone();

}

ExpressaoLogica1 &ExpressaoLogica1::operator=(const ExpressaoLogica1 & other)
{
  ExpressaoLogica1 tmp(other);
  swap(tmp);
  return *this;
}

void ExpressaoLogica1::swap(ExpressaoLogica1 & other)
{
  std::swap(regralogico_, other.regralogico_);

}

ExpressaoLogica1::~ExpressaoLogica1()
{
  delete(regralogico_);

}

void ExpressaoLogica1::accept(Visitor *v)
{
  v->visitExpressaoLogica1(this);
}

ExpressaoLogica1 *ExpressaoLogica1::clone() const
{
  return new ExpressaoLogica1(*this);
}



/********************   ExpressaoLogica_verdadeiro    ********************/
ExpressaoLogica_verdadeiro::ExpressaoLogica_verdadeiro()
{

}

ExpressaoLogica_verdadeiro::ExpressaoLogica_verdadeiro(const ExpressaoLogica_verdadeiro & other)
{

}

ExpressaoLogica_verdadeiro &ExpressaoLogica_verdadeiro::operator=(const ExpressaoLogica_verdadeiro & other)
{
  ExpressaoLogica_verdadeiro tmp(other);
  swap(tmp);
  return *this;
}

void ExpressaoLogica_verdadeiro::swap(ExpressaoLogica_verdadeiro & other)
{

}

ExpressaoLogica_verdadeiro::~ExpressaoLogica_verdadeiro()
{

}

void ExpressaoLogica_verdadeiro::accept(Visitor *v)
{
  v->visitExpressaoLogica_verdadeiro(this);
}

ExpressaoLogica_verdadeiro *ExpressaoLogica_verdadeiro::clone() const
{
  return new ExpressaoLogica_verdadeiro(*this);
}



/********************   ExpressaoLogica2    ********************/
ExpressaoLogica2::ExpressaoLogica2(RegraLogico *p1)
{
  regralogico_ = p1;

}

ExpressaoLogica2::ExpressaoLogica2(const ExpressaoLogica2 & other)
{
  regralogico_ = other.regralogico_->clone();

}

ExpressaoLogica2 &ExpressaoLogica2::operator=(const ExpressaoLogica2 & other)
{
  ExpressaoLogica2 tmp(other);
  swap(tmp);
  return *this;
}

void ExpressaoLogica2::swap(ExpressaoLogica2 & other)
{
  std::swap(regralogico_, other.regralogico_);

}

ExpressaoLogica2::~ExpressaoLogica2()
{
  delete(regralogico_);

}

void ExpressaoLogica2::accept(Visitor *v)
{
  v->visitExpressaoLogica2(this);
}

ExpressaoLogica2 *ExpressaoLogica2::clone() const
{
  return new ExpressaoLogica2(*this);
}



/********************   ExpressaoLogicaExpressaoRelacional    ********************/
ExpressaoLogicaExpressaoRelacional::ExpressaoLogicaExpressaoRelacional(ExpressaoRelacional *p1)
{
  expressaorelacional_ = p1;

}

ExpressaoLogicaExpressaoRelacional::ExpressaoLogicaExpressaoRelacional(const ExpressaoLogicaExpressaoRelacional & other)
{
  expressaorelacional_ = other.expressaorelacional_->clone();

}

ExpressaoLogicaExpressaoRelacional &ExpressaoLogicaExpressaoRelacional::operator=(const ExpressaoLogicaExpressaoRelacional & other)
{
  ExpressaoLogicaExpressaoRelacional tmp(other);
  swap(tmp);
  return *this;
}

void ExpressaoLogicaExpressaoRelacional::swap(ExpressaoLogicaExpressaoRelacional & other)
{
  std::swap(expressaorelacional_, other.expressaorelacional_);

}

ExpressaoLogicaExpressaoRelacional::~ExpressaoLogicaExpressaoRelacional()
{
  delete(expressaorelacional_);

}

void ExpressaoLogicaExpressaoRelacional::accept(Visitor *v)
{
  v->visitExpressaoLogicaExpressaoRelacional(this);
}

ExpressaoLogicaExpressaoRelacional *ExpressaoLogicaExpressaoRelacional::clone() const
{
  return new ExpressaoLogicaExpressaoRelacional(*this);
}



/********************   ExpressaoLogica3    ********************/
ExpressaoLogica3::ExpressaoLogica3(ExpressaoRelacional *p1, RegraLogico *p2)
{
  expressaorelacional_ = p1;
  regralogico_ = p2;

}

ExpressaoLogica3::ExpressaoLogica3(const ExpressaoLogica3 & other)
{
  expressaorelacional_ = other.expressaorelacional_->clone();
  regralogico_ = other.regralogico_->clone();

}

ExpressaoLogica3 &ExpressaoLogica3::operator=(const ExpressaoLogica3 & other)
{
  ExpressaoLogica3 tmp(other);
  swap(tmp);
  return *this;
}

void ExpressaoLogica3::swap(ExpressaoLogica3 & other)
{
  std::swap(expressaorelacional_, other.expressaorelacional_);
  std::swap(regralogico_, other.regralogico_);

}

ExpressaoLogica3::~ExpressaoLogica3()
{
  delete(expressaorelacional_);
  delete(regralogico_);

}

void ExpressaoLogica3::accept(Visitor *v)
{
  v->visitExpressaoLogica3(this);
}

ExpressaoLogica3 *ExpressaoLogica3::clone() const
{
  return new ExpressaoLogica3(*this);
}



/********************   ExpressaoLogica4    ********************/
ExpressaoLogica4::ExpressaoLogica4(Negacao *p1, ExpressaoLogica *p2)
{
  negacao_ = p1;
  expressaologica_ = p2;

}

ExpressaoLogica4::ExpressaoLogica4(const ExpressaoLogica4 & other)
{
  negacao_ = other.negacao_->clone();
  expressaologica_ = other.expressaologica_->clone();

}

ExpressaoLogica4 &ExpressaoLogica4::operator=(const ExpressaoLogica4 & other)
{
  ExpressaoLogica4 tmp(other);
  swap(tmp);
  return *this;
}

void ExpressaoLogica4::swap(ExpressaoLogica4 & other)
{
  std::swap(negacao_, other.negacao_);
  std::swap(expressaologica_, other.expressaologica_);

}

ExpressaoLogica4::~ExpressaoLogica4()
{
  delete(negacao_);
  delete(expressaologica_);

}

void ExpressaoLogica4::accept(Visitor *v)
{
  v->visitExpressaoLogica4(this);
}

ExpressaoLogica4 *ExpressaoLogica4::clone() const
{
  return new ExpressaoLogica4(*this);
}



/********************   ExpressaoLogica5    ********************/
ExpressaoLogica5::ExpressaoLogica5(Negacao *p1, ExpressaoLogica *p2, RegraLogico *p3)
{
  negacao_ = p1;
  expressaologica_ = p2;
  regralogico_ = p3;

}

ExpressaoLogica5::ExpressaoLogica5(const ExpressaoLogica5 & other)
{
  negacao_ = other.negacao_->clone();
  expressaologica_ = other.expressaologica_->clone();
  regralogico_ = other.regralogico_->clone();

}

ExpressaoLogica5 &ExpressaoLogica5::operator=(const ExpressaoLogica5 & other)
{
  ExpressaoLogica5 tmp(other);
  swap(tmp);
  return *this;
}

void ExpressaoLogica5::swap(ExpressaoLogica5 & other)
{
  std::swap(negacao_, other.negacao_);
  std::swap(expressaologica_, other.expressaologica_);
  std::swap(regralogico_, other.regralogico_);

}

ExpressaoLogica5::~ExpressaoLogica5()
{
  delete(negacao_);
  delete(expressaologica_);
  delete(regralogico_);

}

void ExpressaoLogica5::accept(Visitor *v)
{
  v->visitExpressaoLogica5(this);
}

ExpressaoLogica5 *ExpressaoLogica5::clone() const
{
  return new ExpressaoLogica5(*this);
}



/********************   RegraLogico1    ********************/
RegraLogico1::RegraLogico1(OperadorLogico *p1, ExpressaoLogica *p2)
{
  operadorlogico_ = p1;
  expressaologica_ = p2;

}

RegraLogico1::RegraLogico1(const RegraLogico1 & other)
{
  operadorlogico_ = other.operadorlogico_->clone();
  expressaologica_ = other.expressaologica_->clone();

}

RegraLogico1 &RegraLogico1::operator=(const RegraLogico1 & other)
{
  RegraLogico1 tmp(other);
  swap(tmp);
  return *this;
}

void RegraLogico1::swap(RegraLogico1 & other)
{
  std::swap(operadorlogico_, other.operadorlogico_);
  std::swap(expressaologica_, other.expressaologica_);

}

RegraLogico1::~RegraLogico1()
{
  delete(operadorlogico_);
  delete(expressaologica_);

}

void RegraLogico1::accept(Visitor *v)
{
  v->visitRegraLogico1(this);
}

RegraLogico1 *RegraLogico1::clone() const
{
  return new RegraLogico1(*this);
}



/********************   RegraLogico2    ********************/
RegraLogico2::RegraLogico2(OperadorLogico *p1, ExpressaoLogica *p2, RegraLogico *p3)
{
  operadorlogico_ = p1;
  expressaologica_ = p2;
  regralogico_ = p3;

}

RegraLogico2::RegraLogico2(const RegraLogico2 & other)
{
  operadorlogico_ = other.operadorlogico_->clone();
  expressaologica_ = other.expressaologica_->clone();
  regralogico_ = other.regralogico_->clone();

}

RegraLogico2 &RegraLogico2::operator=(const RegraLogico2 & other)
{
  RegraLogico2 tmp(other);
  swap(tmp);
  return *this;
}

void RegraLogico2::swap(RegraLogico2 & other)
{
  std::swap(operadorlogico_, other.operadorlogico_);
  std::swap(expressaologica_, other.expressaologica_);
  std::swap(regralogico_, other.regralogico_);

}

RegraLogico2::~RegraLogico2()
{
  delete(operadorlogico_);
  delete(expressaologica_);
  delete(regralogico_);

}

void RegraLogico2::accept(Visitor *v)
{
  v->visitRegraLogico2(this);
}

RegraLogico2 *RegraLogico2::clone() const
{
  return new RegraLogico2(*this);
}







