/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <string>
#include "Printer.H"
#define INDENT_WIDTH 2


//You may wish to change render
void PrintAbsyn::render(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppend(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppend('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppend(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ' ') bufAppend(c);
  else if (c == 0) return;
  else
  {
     bufAppend(c);
     bufAppend(' ');
  }
}

void PrintAbsyn::render(String s)
{
  render(s.c_str());
}

bool allIsSpace(const char *s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return false;
  return true;
}

void PrintAbsyn::render(const char *s)
{
  if (*s) /* C string not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppend(s);
    } else {
      bufAppend(s);
      bufAppend(' ');
    }
  }
}

void PrintAbsyn::indent()
{
  int n = _n_;
  while (--n >= 0)
    bufAppend(' ');
}

void PrintAbsyn::backup()
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void PrintAbsyn::removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppend('\n');
  indent();
}

PrintAbsyn::PrintAbsyn(void)
{
  _i_ = 0; _n_ = 0;
  buf_ = 0;
  bufReset();
}

PrintAbsyn::~PrintAbsyn(void)
{
}

char *PrintAbsyn::print(Visitable *v)
{
  _i_ = 0; _n_ = 0;
  bufReset();
  v->accept(this);
  return buf_;
}

void PrintAbsyn::visitEntry(Entry *p) {} //abstract class

void PrintAbsyn::visitLEntry(LEntry *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("programa");
  visitIdent(p->ident_);
  render(';');
  _i_ = 0; p->blocodefinicoes_->accept(this);
  _i_ = 0; p->blococomando_->accept(this);
  render('.');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBlocoDefinicoes(BlocoDefinicoes *p) {} //abstract class

void PrintAbsyn::visitBlocoDefinicoes1(BlocoDefinicoes1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->blocofuncaoeproc_->accept(this);
  _i_ = 0; p->blocodefinicoes_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBlocoDefinicoes2(BlocoDefinicoes2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->blococonstante_->accept(this);
  _i_ = 0; p->blocodefinicoes_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBlocoDefinicoes3(BlocoDefinicoes3 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->blocotipo_->accept(this);
  _i_ = 0; p->blocodefinicoes_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBlocoDefinicoes4(BlocoDefinicoes4 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->blocovar_->accept(this);
  _i_ = 0; p->blocodefinicoes_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBlocoDefinicoes_(BlocoDefinicoes_ *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);


  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBlocoFuncaoEProc(BlocoFuncaoEProc *p) {} //abstract class

void PrintAbsyn::visitBlocoFuncaoEProcFuncao(BlocoFuncaoEProcFuncao *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->funcao_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBlocoFuncaoEProc1(BlocoFuncaoEProc1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->funcao_->accept(this);
  _i_ = 0; p->blocofuncaoeproc_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBlocoFuncaoEProcProcedimento(BlocoFuncaoEProcProcedimento *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->procedimento_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBlocoFuncaoEProc2(BlocoFuncaoEProc2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->procedimento_->accept(this);
  _i_ = 0; p->blocofuncaoeproc_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBlocoFuncaoEProc_(BlocoFuncaoEProc_ *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);


  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBlocoConstante(BlocoConstante *p) {} //abstract class

void PrintAbsyn::visitBlocoConstante1(BlocoConstante1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("const");
  _i_ = 0; p->regrablococonstante_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBlocoConstante_(BlocoConstante_ *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);


  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraBlocoConstante(RegraBlocoConstante *p) {} //abstract class

void PrintAbsyn::visitRegraBlocoConstante1(RegraBlocoConstante1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render('=');
  _i_ = 0; p->valor_->accept(this);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraBlocoConstante2(RegraBlocoConstante2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render('=');
  _i_ = 0; p->valor_->accept(this);
  render(';');
  _i_ = 0; p->regrablococonstante_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBlocoTipo(BlocoTipo *p) {} //abstract class

void PrintAbsyn::visitBlocoTipo1(BlocoTipo1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("tipo");
  _i_ = 0; p->regrablocotipo_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBlocoTipo_(BlocoTipo_ *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);


  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraBlocoTipo(RegraBlocoTipo *p) {} //abstract class

void PrintAbsyn::visitRegraBlocoTipo1(RegraBlocoTipo1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render('=');
  _i_ = 0; p->regratipo_->accept(this);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraBlocoTipo2(RegraBlocoTipo2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render('=');
  _i_ = 0; p->regratipo_->accept(this);
  render(';');
  _i_ = 0; p->regrablocotipo_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBlocoVar(BlocoVar *p) {} //abstract class

void PrintAbsyn::visitBlocoVar1(BlocoVar1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("var");
  _i_ = 0; p->regrablocovar_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBlocoVar_(BlocoVar_ *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);


  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraBlocoVar(RegraBlocoVar *p) {} //abstract class

void PrintAbsyn::visitRegraBlocoVar1(RegraBlocoVar1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render(':');
  _i_ = 0; p->regratipo_->accept(this);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraBlocoVar2(RegraBlocoVar2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render(':');
  _i_ = 0; p->regratipo_->accept(this);
  render(';');
  _i_ = 0; p->regrablocovar_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraBlocoVar3(RegraBlocoVar3 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->listaident_->accept(this);
  render(':');
  _i_ = 0; p->regratipo_->accept(this);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraBlocoVar4(RegraBlocoVar4 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->listaident_->accept(this);
  render(':');
  _i_ = 0; p->regratipo_->accept(this);
  render(';');
  _i_ = 0; p->regrablocovar_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBlocoComando(BlocoComando *p) {} //abstract class

void PrintAbsyn::visitBlocoComando1(BlocoComando1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("inicio");
  _i_ = 0; p->regracomando_->accept(this);
  render("fim");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBlocoComando_(BlocoComando_ *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);


  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraComando(RegraComando *p) {} //abstract class

void PrintAbsyn::visitRegraComando1(RegraComando1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->comando_->accept(this);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraComando2(RegraComando2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->comando_->accept(this);
  render(';');
  _i_ = 0; p->regracomando_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitComando(Comando *p) {} //abstract class

void PrintAbsyn::visitComandoAtribuicao(ComandoAtribuicao *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->atribuicao_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitComandoIf(ComandoIf *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->if_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitComandoWhile(ComandoWhile *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->while_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitComandoFor(ComandoFor *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->for_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitComandoGoto(ComandoGoto *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->goto_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitComandoCase(ComandoCase *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->case_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitComandoChamadaFuncaoEProc(ComandoChamadaFuncaoEProc *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->chamadafuncaoeproc_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAtribuicao(Atribuicao *p) {} //abstract class

void PrintAbsyn::visitAtribuicao1(Atribuicao1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render(":=");
  _i_ = 0; p->valor_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAtribuicao2(Atribuicao2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render(":=");
  _i_ = 0; p->expressaoaritmetica_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAtribuicao3(Atribuicao3 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_1);
  render(":=");
  visitIdent(p->ident_2);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAtribuicao4(Atribuicao4 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render('[');
  _i_ = 0; p->subescrito_->accept(this);
  render(']');
  render(":=");
  _i_ = 0; p->valor_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAtribuicao5(Atribuicao5 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render('^');
  render(":=");
  _i_ = 0; p->valor_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAtribuicaoAtribuicaoStruct(AtribuicaoAtribuicaoStruct *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->atribuicaostruct_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAtribuicao6(Atribuicao6 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render(":=");
  _i_ = 0; p->chamadafuncaoeproc_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSubEscrito(SubEscrito *p) {} //abstract class

void PrintAbsyn::visitSubEscritoIdent(SubEscritoIdent *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSubEscritoInteger(SubEscritoInteger *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitInteger(p->integer_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraTipo(RegraTipo *p) {} //abstract class

void PrintAbsyn::visitRegraTipoTipoPrimitivo(RegraTipoTipoPrimitivo *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->tipoprimitivo_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraTipoTipoDerivado(RegraTipoTipoDerivado *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->tipoderivado_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraTipoIdent(RegraTipoIdent *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTipoPrimitivo(TipoPrimitivo *p) {} //abstract class

void PrintAbsyn::visitTipoPrimitivo_int(TipoPrimitivo_int *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("int");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTipoPrimitivo_real(TipoPrimitivo_real *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("real");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTipoPrimitivo_char(TipoPrimitivo_char *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("char");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitValor(Valor *p) {} //abstract class

void PrintAbsyn::visitValorInteger(ValorInteger *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitInteger(p->integer_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitValorDouble(ValorDouble *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitDouble(p->double_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitValorChar(ValorChar *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitChar(p->char_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitValorString(ValorString *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitString(p->string_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTipoDerivado(TipoDerivado *p) {} //abstract class

void PrintAbsyn::visitTipoDerivadoPonteiro(TipoDerivadoPonteiro *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->ponteiro_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTipoDerivadoVetor(TipoDerivadoVetor *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->vetor_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTipoDerivadoStruct(TipoDerivadoStruct *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->struct_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPonteiro(Ponteiro *p) {} //abstract class

void PrintAbsyn::visitPonteiro1(Ponteiro1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('^');
  _i_ = 0; p->tipoprimitivo_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPonteiro2(Ponteiro2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('^');
  _i_ = 0; p->tipoderivado_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVetor(Vetor *p) {} //abstract class

void PrintAbsyn::visitLVetor(LVetor *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("vetor");
  render('[');
  visitInteger(p->integer_1);
  render("..");
  visitInteger(p->integer_2);
  render(']');
  render("de");
  _i_ = 0; p->tipoprimitivo_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitIf(If *p) {} //abstract class

void PrintAbsyn::visitIf1(If1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("se");
  render('(');
  _i_ = 0; p->expressaologica_->accept(this);
  render(')');
  render("entao");
  _i_ = 0; p->blococomando_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitIf2(If2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("se");
  render('(');
  _i_ = 0; p->expressaologica_->accept(this);
  render(')');
  render("entao");
  _i_ = 0; p->blococomando_1->accept(this);
  render("senao");
  _i_ = 0; p->blococomando_2->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitWhile(While *p) {} //abstract class

void PrintAbsyn::visitLWhile(LWhile *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("enquanto");
  render('(');
  _i_ = 0; p->expressaologica_->accept(this);
  render(')');
  render("faca");
  _i_ = 0; p->blococomando_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFor(For *p) {} //abstract class

void PrintAbsyn::visitFor1(For1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("para");
  _i_ = 0; p->atribuicao_->accept(this);
  render("ate");
  visitInteger(p->integer_);
  render("faca");
  _i_ = 0; p->blococomando_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFor2(For2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("para");
  _i_ = 0; p->atribuicao_->accept(this);
  render("ate");
  visitIdent(p->ident_);
  render("faca");
  _i_ = 0; p->blococomando_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitGoto(Goto *p) {} //abstract class

void PrintAbsyn::visitLGoto(LGoto *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("sovai");
  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRotulo(Rotulo *p) {} //abstract class

void PrintAbsyn::visitLRotulo(LRotulo *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render(':');
  _i_ = 0; p->regracomando_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitStruct(Struct *p) {} //abstract class

void PrintAbsyn::visitLStruct(LStruct *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("registro");
  _i_ = 0; p->definicaocampostruct_->accept(this);
  render("fim");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDefinicaoCampoStruct(DefinicaoCampoStruct *p) {} //abstract class

void PrintAbsyn::visitDefinicaoCampoStruct1(DefinicaoCampoStruct1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render(':');
  _i_ = 0; p->regratipo_->accept(this);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDefinicaoCampoStruct2(DefinicaoCampoStruct2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render(':');
  _i_ = 0; p->regratipo_->accept(this);
  render(';');
  _i_ = 0; p->definicaocampostruct_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAtribuicaoStruct(AtribuicaoStruct *p) {} //abstract class

void PrintAbsyn::visitAtribuicaoStruct1(AtribuicaoStruct1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_1);
  render('.');
  visitIdent(p->ident_2);
  render(":=");
  _i_ = 0; p->valor_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAtribuicaoStruct2(AtribuicaoStruct2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_1);
  render('.');
  visitIdent(p->ident_2);
  render(":=");
  _i_ = 0; p->valor_->accept(this);
  _i_ = 0; p->atribuicaostruct_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOperadorRelacional(OperadorRelacional *p) {} //abstract class

void PrintAbsyn::visitOperadorRelacional1(OperadorRelacional1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('>');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOperadorRelacional2(OperadorRelacional2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('<');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOperadorRelacional3(OperadorRelacional3 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("<>");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOperadorRelacional4(OperadorRelacional4 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render(">=");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOperadorRelacional5(OperadorRelacional5 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("<=");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOperadorRelacional6(OperadorRelacional6 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('=');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOperadorLogico(OperadorLogico *p) {} //abstract class

void PrintAbsyn::visitOperadorLogico1(OperadorLogico1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("&&");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOperadorLogico2(OperadorLogico2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("||");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOperadorLogico3(OperadorLogico3 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("&|");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOperadorLogicoNegacao(OperadorLogicoNegacao *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->negacao_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitNegacao(Negacao *p) {} //abstract class

void PrintAbsyn::visitLNegacao(LNegacao *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('!');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOperadorAritmetico(OperadorAritmetico *p) {} //abstract class

void PrintAbsyn::visitOperadorAritmetico1(OperadorAritmetico1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('+');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOperadorAritmetico2(OperadorAritmetico2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('-');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOperadorAritmetico3(OperadorAritmetico3 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('*');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOperadorAritmetico4(OperadorAritmetico4 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('/');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitCase(Case *p) {} //abstract class

void PrintAbsyn::visitLCase(LCase *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("caso");
  render('(');
  _i_ = 0; p->seletor_->accept(this);
  render(')');
  render("de");
  _i_ = 0; p->regraseletor_->accept(this);
  render("fim");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraSeletor(RegraSeletor *p) {} //abstract class

void PrintAbsyn::visitRegraSeletor1(RegraSeletor1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->seletor_->accept(this);
  render(':');
  _i_ = 0; p->comando_->accept(this);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraSeletor2(RegraSeletor2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->seletor_->accept(this);
  render(':');
  _i_ = 0; p->comando_->accept(this);
  render(';');
  _i_ = 0; p->regraseletor_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSeletor(Seletor *p) {} //abstract class

void PrintAbsyn::visitSeletorInteger(SeletorInteger *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitInteger(p->integer_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSeletorChar(SeletorChar *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitChar(p->char_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSeletorIdent(SeletorIdent *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitChamadaFuncaoEProc(ChamadaFuncaoEProc *p) {} //abstract class

void PrintAbsyn::visitLChamad(LChamad *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render('(');
  _i_ = 0; p->listaident_->accept(this);
  render(')');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListaIdent(ListaIdent *p) {} //abstract class

void PrintAbsyn::visitListaIdentIdent(ListaIdentIdent *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListaIdent1(ListaIdent1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render(',');
  _i_ = 0; p->listaident_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFuncao(Funcao *p) {} //abstract class

void PrintAbsyn::visitLFuncao(LFuncao *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("funcao");
  visitIdent(p->ident_);
  render('(');
  _i_ = 0; p->regrablocovar_->accept(this);
  render(')');
  render(':');
  _i_ = 0; p->regratipo_->accept(this);
  _i_ = 0; p->blocovar_->accept(this);
  _i_ = 0; p->blococomando_->accept(this);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitProcedimento(Procedimento *p) {} //abstract class

void PrintAbsyn::visitProcedimento1(Procedimento1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("procedimento");
  visitIdent(p->ident_);
  render('(');
  _i_ = 0; p->regrablocovar_->accept(this);
  render(')');
  _i_ = 0; p->blocovar_->accept(this);
  _i_ = 0; p->blococomando_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitProcedimento2(Procedimento2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("procedimento");
  visitIdent(p->ident_);
  render('(');
  render(')');
  _i_ = 0; p->blocovar_->accept(this);
  _i_ = 0; p->blococomando_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExpressaoAritmetica(ExpressaoAritmetica *p) {} //abstract class

void PrintAbsyn::visitExpAr(ExpAr *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->operando_->accept(this);
  _i_ = 0; p->regraaritmetica_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOperando(Operando *p) {} //abstract class

void PrintAbsyn::visitOperandoInteger(OperandoInteger *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitInteger(p->integer_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOperandoDouble(OperandoDouble *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitDouble(p->double_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOperandoIdent(OperandoIdent *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraAritmetica(RegraAritmetica *p) {} //abstract class

void PrintAbsyn::visitRegraAritmetica1(RegraAritmetica1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->operadoraritmetico_->accept(this);
  _i_ = 0; p->operando_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraAritmetica2(RegraAritmetica2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->operadoraritmetico_->accept(this);
  _i_ = 0; p->operando_->accept(this);
  _i_ = 0; p->regraaritmetica_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExpressaoRelacional(ExpressaoRelacional *p) {} //abstract class

void PrintAbsyn::visitExpressaoRelacionalOperando(ExpressaoRelacionalOperando *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->operando_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExpressaoRelacional1(ExpressaoRelacional1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->operando_->accept(this);
  _i_ = 0; p->regrarelacional_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExpressaoRelacional2(ExpressaoRelacional2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->expressaoaritmetica_->accept(this);
  _i_ = 0; p->regrarelacional_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraRelacional(RegraRelacional *p) {} //abstract class

void PrintAbsyn::visitRegraRelacional1(RegraRelacional1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->operadorrelacional_->accept(this);
  _i_ = 0; p->operando_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraRelacional2(RegraRelacional2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->operadorrelacional_->accept(this);
  _i_ = 0; p->expressaoaritmetica_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExpressaoLogica(ExpressaoLogica *p) {} //abstract class

void PrintAbsyn::visitExpressaoLogica_falso(ExpressaoLogica_falso *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("falso");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExpressaoLogica1(ExpressaoLogica1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("falso");
  _i_ = 0; p->regralogico_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExpressaoLogica_verdadeiro(ExpressaoLogica_verdadeiro *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("verdadeiro");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExpressaoLogica2(ExpressaoLogica2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("verdadeiro");
  _i_ = 0; p->regralogico_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExpressaoLogicaExpressaoRelacional(ExpressaoLogicaExpressaoRelacional *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->expressaorelacional_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExpressaoLogica3(ExpressaoLogica3 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->expressaorelacional_->accept(this);
  _i_ = 0; p->regralogico_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExpressaoLogica4(ExpressaoLogica4 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->negacao_->accept(this);
  _i_ = 0; p->expressaologica_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExpressaoLogica5(ExpressaoLogica5 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->negacao_->accept(this);
  _i_ = 0; p->expressaologica_->accept(this);
  _i_ = 0; p->regralogico_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraLogico(RegraLogico *p) {} //abstract class

void PrintAbsyn::visitRegraLogico1(RegraLogico1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->operadorlogico_->accept(this);
  _i_ = 0; p->expressaologica_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRegraLogico2(RegraLogico2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->operadorlogico_->accept(this);
  _i_ = 0; p->expressaologica_->accept(this);
  _i_ = 0; p->regralogico_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  render(tmp);
}

void PrintAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  render(tmp);
}

void PrintAbsyn::visitChar(Char c)
{
  char tmp[4];
  sprintf(tmp, "'%c'", c);
  render(tmp);
}

void PrintAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
  bufAppend(' ');
}

void PrintAbsyn::visitIdent(String s)
{
  render(s);
}

ShowAbsyn::ShowAbsyn(void)
{
  buf_ = 0;
  bufReset();
}

ShowAbsyn::~ShowAbsyn(void)
{
}

char *ShowAbsyn::show(Visitable *v)
{
  bufReset();
  v->accept(this);
  return buf_;
}

void ShowAbsyn::visitEntry(Entry *p) {} //abstract class

void ShowAbsyn::visitLEntry(LEntry *p)
{
  bufAppend('(');
  bufAppend("LEntry");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->blocodefinicoes_)  p->blocodefinicoes_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->blococomando_)  p->blococomando_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitBlocoDefinicoes(BlocoDefinicoes *p) {} //abstract class

void ShowAbsyn::visitBlocoDefinicoes1(BlocoDefinicoes1 *p)
{
  bufAppend('(');
  bufAppend("BlocoDefinicoes1");
  bufAppend(' ');
  bufAppend('[');
  if (p->blocofuncaoeproc_)  p->blocofuncaoeproc_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->blocodefinicoes_)  p->blocodefinicoes_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitBlocoDefinicoes2(BlocoDefinicoes2 *p)
{
  bufAppend('(');
  bufAppend("BlocoDefinicoes2");
  bufAppend(' ');
  bufAppend('[');
  if (p->blococonstante_)  p->blococonstante_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->blocodefinicoes_)  p->blocodefinicoes_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitBlocoDefinicoes3(BlocoDefinicoes3 *p)
{
  bufAppend('(');
  bufAppend("BlocoDefinicoes3");
  bufAppend(' ');
  bufAppend('[');
  if (p->blocotipo_)  p->blocotipo_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->blocodefinicoes_)  p->blocodefinicoes_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitBlocoDefinicoes4(BlocoDefinicoes4 *p)
{
  bufAppend('(');
  bufAppend("BlocoDefinicoes4");
  bufAppend(' ');
  bufAppend('[');
  if (p->blocovar_)  p->blocovar_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->blocodefinicoes_)  p->blocodefinicoes_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitBlocoDefinicoes_(BlocoDefinicoes_ *p)
{
  bufAppend("BlocoDefinicoes_");
}
void ShowAbsyn::visitBlocoFuncaoEProc(BlocoFuncaoEProc *p) {} //abstract class

void ShowAbsyn::visitBlocoFuncaoEProcFuncao(BlocoFuncaoEProcFuncao *p)
{
  bufAppend('(');
  bufAppend("BlocoFuncaoEProcFuncao");
  bufAppend(' ');
  bufAppend('[');
  if (p->funcao_)  p->funcao_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitBlocoFuncaoEProc1(BlocoFuncaoEProc1 *p)
{
  bufAppend('(');
  bufAppend("BlocoFuncaoEProc1");
  bufAppend(' ');
  bufAppend('[');
  if (p->funcao_)  p->funcao_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->blocofuncaoeproc_)  p->blocofuncaoeproc_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitBlocoFuncaoEProcProcedimento(BlocoFuncaoEProcProcedimento *p)
{
  bufAppend('(');
  bufAppend("BlocoFuncaoEProcProcedimento");
  bufAppend(' ');
  bufAppend('[');
  if (p->procedimento_)  p->procedimento_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitBlocoFuncaoEProc2(BlocoFuncaoEProc2 *p)
{
  bufAppend('(');
  bufAppend("BlocoFuncaoEProc2");
  bufAppend(' ');
  bufAppend('[');
  if (p->procedimento_)  p->procedimento_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->blocofuncaoeproc_)  p->blocofuncaoeproc_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitBlocoFuncaoEProc_(BlocoFuncaoEProc_ *p)
{
  bufAppend("BlocoFuncaoEProc_");
}
void ShowAbsyn::visitBlocoConstante(BlocoConstante *p) {} //abstract class

void ShowAbsyn::visitBlocoConstante1(BlocoConstante1 *p)
{
  bufAppend('(');
  bufAppend("BlocoConstante1");
  bufAppend(' ');
  bufAppend('[');
  if (p->regrablococonstante_)  p->regrablococonstante_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitBlocoConstante_(BlocoConstante_ *p)
{
  bufAppend("BlocoConstante_");
}
void ShowAbsyn::visitRegraBlocoConstante(RegraBlocoConstante *p) {} //abstract class

void ShowAbsyn::visitRegraBlocoConstante1(RegraBlocoConstante1 *p)
{
  bufAppend('(');
  bufAppend("RegraBlocoConstante1");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->valor_)  p->valor_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitRegraBlocoConstante2(RegraBlocoConstante2 *p)
{
  bufAppend('(');
  bufAppend("RegraBlocoConstante2");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->valor_)  p->valor_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->regrablococonstante_)  p->regrablococonstante_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitBlocoTipo(BlocoTipo *p) {} //abstract class

void ShowAbsyn::visitBlocoTipo1(BlocoTipo1 *p)
{
  bufAppend('(');
  bufAppend("BlocoTipo1");
  bufAppend(' ');
  bufAppend('[');
  if (p->regrablocotipo_)  p->regrablocotipo_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitBlocoTipo_(BlocoTipo_ *p)
{
  bufAppend("BlocoTipo_");
}
void ShowAbsyn::visitRegraBlocoTipo(RegraBlocoTipo *p) {} //abstract class

void ShowAbsyn::visitRegraBlocoTipo1(RegraBlocoTipo1 *p)
{
  bufAppend('(');
  bufAppend("RegraBlocoTipo1");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->regratipo_)  p->regratipo_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitRegraBlocoTipo2(RegraBlocoTipo2 *p)
{
  bufAppend('(');
  bufAppend("RegraBlocoTipo2");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->regratipo_)  p->regratipo_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->regrablocotipo_)  p->regrablocotipo_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitBlocoVar(BlocoVar *p) {} //abstract class

void ShowAbsyn::visitBlocoVar1(BlocoVar1 *p)
{
  bufAppend('(');
  bufAppend("BlocoVar1");
  bufAppend(' ');
  bufAppend('[');
  if (p->regrablocovar_)  p->regrablocovar_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitBlocoVar_(BlocoVar_ *p)
{
  bufAppend("BlocoVar_");
}
void ShowAbsyn::visitRegraBlocoVar(RegraBlocoVar *p) {} //abstract class

void ShowAbsyn::visitRegraBlocoVar1(RegraBlocoVar1 *p)
{
  bufAppend('(');
  bufAppend("RegraBlocoVar1");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->regratipo_)  p->regratipo_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitRegraBlocoVar2(RegraBlocoVar2 *p)
{
  bufAppend('(');
  bufAppend("RegraBlocoVar2");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->regratipo_)  p->regratipo_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->regrablocovar_)  p->regrablocovar_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitRegraBlocoVar3(RegraBlocoVar3 *p)
{
  bufAppend('(');
  bufAppend("RegraBlocoVar3");
  bufAppend(' ');
  bufAppend('[');
  if (p->listaident_)  p->listaident_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->regratipo_)  p->regratipo_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitRegraBlocoVar4(RegraBlocoVar4 *p)
{
  bufAppend('(');
  bufAppend("RegraBlocoVar4");
  bufAppend(' ');
  bufAppend('[');
  if (p->listaident_)  p->listaident_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->regratipo_)  p->regratipo_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->regrablocovar_)  p->regrablocovar_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitBlocoComando(BlocoComando *p) {} //abstract class

void ShowAbsyn::visitBlocoComando1(BlocoComando1 *p)
{
  bufAppend('(');
  bufAppend("BlocoComando1");
  bufAppend(' ');
  bufAppend('[');
  if (p->regracomando_)  p->regracomando_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitBlocoComando_(BlocoComando_ *p)
{
  bufAppend("BlocoComando_");
}
void ShowAbsyn::visitRegraComando(RegraComando *p) {} //abstract class

void ShowAbsyn::visitRegraComando1(RegraComando1 *p)
{
  bufAppend('(');
  bufAppend("RegraComando1");
  bufAppend(' ');
  bufAppend('[');
  if (p->comando_)  p->comando_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitRegraComando2(RegraComando2 *p)
{
  bufAppend('(');
  bufAppend("RegraComando2");
  bufAppend(' ');
  bufAppend('[');
  if (p->comando_)  p->comando_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->regracomando_)  p->regracomando_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitComando(Comando *p) {} //abstract class

void ShowAbsyn::visitComandoAtribuicao(ComandoAtribuicao *p)
{
  bufAppend('(');
  bufAppend("ComandoAtribuicao");
  bufAppend(' ');
  bufAppend('[');
  if (p->atribuicao_)  p->atribuicao_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitComandoIf(ComandoIf *p)
{
  bufAppend('(');
  bufAppend("ComandoIf");
  bufAppend(' ');
  bufAppend('[');
  if (p->if_)  p->if_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitComandoWhile(ComandoWhile *p)
{
  bufAppend('(');
  bufAppend("ComandoWhile");
  bufAppend(' ');
  bufAppend('[');
  if (p->while_)  p->while_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitComandoFor(ComandoFor *p)
{
  bufAppend('(');
  bufAppend("ComandoFor");
  bufAppend(' ');
  bufAppend('[');
  if (p->for_)  p->for_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitComandoGoto(ComandoGoto *p)
{
  bufAppend('(');
  bufAppend("ComandoGoto");
  bufAppend(' ');
  bufAppend('[');
  if (p->goto_)  p->goto_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitComandoCase(ComandoCase *p)
{
  bufAppend('(');
  bufAppend("ComandoCase");
  bufAppend(' ');
  bufAppend('[');
  if (p->case_)  p->case_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitComandoChamadaFuncaoEProc(ComandoChamadaFuncaoEProc *p)
{
  bufAppend('(');
  bufAppend("ComandoChamadaFuncaoEProc");
  bufAppend(' ');
  bufAppend('[');
  if (p->chamadafuncaoeproc_)  p->chamadafuncaoeproc_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitAtribuicao(Atribuicao *p) {} //abstract class

void ShowAbsyn::visitAtribuicao1(Atribuicao1 *p)
{
  bufAppend('(');
  bufAppend("Atribuicao1");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->valor_)  p->valor_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitAtribuicao2(Atribuicao2 *p)
{
  bufAppend('(');
  bufAppend("Atribuicao2");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->expressaoaritmetica_)  p->expressaoaritmetica_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitAtribuicao3(Atribuicao3 *p)
{
  bufAppend('(');
  bufAppend("Atribuicao3");
  bufAppend(' ');
  visitIdent(p->ident_1);
  bufAppend(' ');
  visitIdent(p->ident_2);
  bufAppend(')');
}
void ShowAbsyn::visitAtribuicao4(Atribuicao4 *p)
{
  bufAppend('(');
  bufAppend("Atribuicao4");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->subescrito_)  p->subescrito_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->valor_)  p->valor_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitAtribuicao5(Atribuicao5 *p)
{
  bufAppend('(');
  bufAppend("Atribuicao5");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->valor_)  p->valor_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitAtribuicaoAtribuicaoStruct(AtribuicaoAtribuicaoStruct *p)
{
  bufAppend('(');
  bufAppend("AtribuicaoAtribuicaoStruct");
  bufAppend(' ');
  bufAppend('[');
  if (p->atribuicaostruct_)  p->atribuicaostruct_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitAtribuicao6(Atribuicao6 *p)
{
  bufAppend('(');
  bufAppend("Atribuicao6");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->chamadafuncaoeproc_)  p->chamadafuncaoeproc_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitSubEscrito(SubEscrito *p) {} //abstract class

void ShowAbsyn::visitSubEscritoIdent(SubEscritoIdent *p)
{
  bufAppend('(');
  bufAppend("SubEscritoIdent");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitSubEscritoInteger(SubEscritoInteger *p)
{
  bufAppend('(');
  bufAppend("SubEscritoInteger");
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitRegraTipo(RegraTipo *p) {} //abstract class

void ShowAbsyn::visitRegraTipoTipoPrimitivo(RegraTipoTipoPrimitivo *p)
{
  bufAppend('(');
  bufAppend("RegraTipoTipoPrimitivo");
  bufAppend(' ');
  bufAppend('[');
  if (p->tipoprimitivo_)  p->tipoprimitivo_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitRegraTipoTipoDerivado(RegraTipoTipoDerivado *p)
{
  bufAppend('(');
  bufAppend("RegraTipoTipoDerivado");
  bufAppend(' ');
  bufAppend('[');
  if (p->tipoderivado_)  p->tipoderivado_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitRegraTipoIdent(RegraTipoIdent *p)
{
  bufAppend('(');
  bufAppend("RegraTipoIdent");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitTipoPrimitivo(TipoPrimitivo *p) {} //abstract class

void ShowAbsyn::visitTipoPrimitivo_int(TipoPrimitivo_int *p)
{
  bufAppend("TipoPrimitivo_int");
}
void ShowAbsyn::visitTipoPrimitivo_real(TipoPrimitivo_real *p)
{
  bufAppend("TipoPrimitivo_real");
}
void ShowAbsyn::visitTipoPrimitivo_char(TipoPrimitivo_char *p)
{
  bufAppend("TipoPrimitivo_char");
}
void ShowAbsyn::visitValor(Valor *p) {} //abstract class

void ShowAbsyn::visitValorInteger(ValorInteger *p)
{
  bufAppend('(');
  bufAppend("ValorInteger");
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitValorDouble(ValorDouble *p)
{
  bufAppend('(');
  bufAppend("ValorDouble");
  bufAppend(' ');
  visitDouble(p->double_);
  bufAppend(')');
}
void ShowAbsyn::visitValorChar(ValorChar *p)
{
  bufAppend('(');
  bufAppend("ValorChar");
  bufAppend(' ');
  visitChar(p->char_);
  bufAppend(')');
}
void ShowAbsyn::visitValorString(ValorString *p)
{
  bufAppend('(');
  bufAppend("ValorString");
  bufAppend(' ');
  visitString(p->string_);
  bufAppend(')');
}
void ShowAbsyn::visitTipoDerivado(TipoDerivado *p) {} //abstract class

void ShowAbsyn::visitTipoDerivadoPonteiro(TipoDerivadoPonteiro *p)
{
  bufAppend('(');
  bufAppend("TipoDerivadoPonteiro");
  bufAppend(' ');
  bufAppend('[');
  if (p->ponteiro_)  p->ponteiro_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitTipoDerivadoVetor(TipoDerivadoVetor *p)
{
  bufAppend('(');
  bufAppend("TipoDerivadoVetor");
  bufAppend(' ');
  bufAppend('[');
  if (p->vetor_)  p->vetor_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitTipoDerivadoStruct(TipoDerivadoStruct *p)
{
  bufAppend('(');
  bufAppend("TipoDerivadoStruct");
  bufAppend(' ');
  bufAppend('[');
  if (p->struct_)  p->struct_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitPonteiro(Ponteiro *p) {} //abstract class

void ShowAbsyn::visitPonteiro1(Ponteiro1 *p)
{
  bufAppend('(');
  bufAppend("Ponteiro1");
  bufAppend(' ');
  bufAppend('[');
  if (p->tipoprimitivo_)  p->tipoprimitivo_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitPonteiro2(Ponteiro2 *p)
{
  bufAppend('(');
  bufAppend("Ponteiro2");
  bufAppend(' ');
  bufAppend('[');
  if (p->tipoderivado_)  p->tipoderivado_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitVetor(Vetor *p) {} //abstract class

void ShowAbsyn::visitLVetor(LVetor *p)
{
  bufAppend('(');
  bufAppend("LVetor");
  bufAppend(' ');
  visitInteger(p->integer_1);
  bufAppend(' ');
  visitInteger(p->integer_2);
  bufAppend(' ');
  bufAppend('[');
  if (p->tipoprimitivo_)  p->tipoprimitivo_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitIf(If *p) {} //abstract class

void ShowAbsyn::visitIf1(If1 *p)
{
  bufAppend('(');
  bufAppend("If1");
  bufAppend(' ');
  bufAppend('[');
  if (p->expressaologica_)  p->expressaologica_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->blococomando_)  p->blococomando_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitIf2(If2 *p)
{
  bufAppend('(');
  bufAppend("If2");
  bufAppend(' ');
  bufAppend('[');
  if (p->expressaologica_)  p->expressaologica_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  p->blococomando_1->accept(this);
  bufAppend(' ');
  p->blococomando_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitWhile(While *p) {} //abstract class

void ShowAbsyn::visitLWhile(LWhile *p)
{
  bufAppend('(');
  bufAppend("LWhile");
  bufAppend(' ');
  bufAppend('[');
  if (p->expressaologica_)  p->expressaologica_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->blococomando_)  p->blococomando_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFor(For *p) {} //abstract class

void ShowAbsyn::visitFor1(For1 *p)
{
  bufAppend('(');
  bufAppend("For1");
  bufAppend(' ');
  bufAppend('[');
  if (p->atribuicao_)  p->atribuicao_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(' ');
  bufAppend('[');
  if (p->blococomando_)  p->blococomando_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFor2(For2 *p)
{
  bufAppend('(');
  bufAppend("For2");
  bufAppend(' ');
  bufAppend('[');
  if (p->atribuicao_)  p->atribuicao_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->blococomando_)  p->blococomando_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitGoto(Goto *p) {} //abstract class

void ShowAbsyn::visitLGoto(LGoto *p)
{
  bufAppend('(');
  bufAppend("LGoto");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitRotulo(Rotulo *p) {} //abstract class

void ShowAbsyn::visitLRotulo(LRotulo *p)
{
  bufAppend('(');
  bufAppend("LRotulo");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->regracomando_)  p->regracomando_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitStruct(Struct *p) {} //abstract class

void ShowAbsyn::visitLStruct(LStruct *p)
{
  bufAppend('(');
  bufAppend("LStruct");
  bufAppend(' ');
  bufAppend('[');
  if (p->definicaocampostruct_)  p->definicaocampostruct_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitDefinicaoCampoStruct(DefinicaoCampoStruct *p) {} //abstract class

void ShowAbsyn::visitDefinicaoCampoStruct1(DefinicaoCampoStruct1 *p)
{
  bufAppend('(');
  bufAppend("DefinicaoCampoStruct1");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->regratipo_)  p->regratipo_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitDefinicaoCampoStruct2(DefinicaoCampoStruct2 *p)
{
  bufAppend('(');
  bufAppend("DefinicaoCampoStruct2");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->regratipo_)  p->regratipo_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->definicaocampostruct_)  p->definicaocampostruct_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitAtribuicaoStruct(AtribuicaoStruct *p) {} //abstract class

void ShowAbsyn::visitAtribuicaoStruct1(AtribuicaoStruct1 *p)
{
  bufAppend('(');
  bufAppend("AtribuicaoStruct1");
  bufAppend(' ');
  visitIdent(p->ident_1);
  bufAppend(' ');
  visitIdent(p->ident_2);
  bufAppend(' ');
  bufAppend('[');
  if (p->valor_)  p->valor_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitAtribuicaoStruct2(AtribuicaoStruct2 *p)
{
  bufAppend('(');
  bufAppend("AtribuicaoStruct2");
  bufAppend(' ');
  visitIdent(p->ident_1);
  bufAppend(' ');
  visitIdent(p->ident_2);
  bufAppend(' ');
  bufAppend('[');
  if (p->valor_)  p->valor_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->atribuicaostruct_)  p->atribuicaostruct_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitOperadorRelacional(OperadorRelacional *p) {} //abstract class

void ShowAbsyn::visitOperadorRelacional1(OperadorRelacional1 *p)
{
  bufAppend("OperadorRelacional1");
}
void ShowAbsyn::visitOperadorRelacional2(OperadorRelacional2 *p)
{
  bufAppend("OperadorRelacional2");
}
void ShowAbsyn::visitOperadorRelacional3(OperadorRelacional3 *p)
{
  bufAppend("OperadorRelacional3");
}
void ShowAbsyn::visitOperadorRelacional4(OperadorRelacional4 *p)
{
  bufAppend("OperadorRelacional4");
}
void ShowAbsyn::visitOperadorRelacional5(OperadorRelacional5 *p)
{
  bufAppend("OperadorRelacional5");
}
void ShowAbsyn::visitOperadorRelacional6(OperadorRelacional6 *p)
{
  bufAppend("OperadorRelacional6");
}
void ShowAbsyn::visitOperadorLogico(OperadorLogico *p) {} //abstract class

void ShowAbsyn::visitOperadorLogico1(OperadorLogico1 *p)
{
  bufAppend("OperadorLogico1");
}
void ShowAbsyn::visitOperadorLogico2(OperadorLogico2 *p)
{
  bufAppend("OperadorLogico2");
}
void ShowAbsyn::visitOperadorLogico3(OperadorLogico3 *p)
{
  bufAppend("OperadorLogico3");
}
void ShowAbsyn::visitOperadorLogicoNegacao(OperadorLogicoNegacao *p)
{
  bufAppend('(');
  bufAppend("OperadorLogicoNegacao");
  bufAppend(' ');
  bufAppend('[');
  if (p->negacao_)  p->negacao_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitNegacao(Negacao *p) {} //abstract class

void ShowAbsyn::visitLNegacao(LNegacao *p)
{
  bufAppend("LNegacao");
}
void ShowAbsyn::visitOperadorAritmetico(OperadorAritmetico *p) {} //abstract class

void ShowAbsyn::visitOperadorAritmetico1(OperadorAritmetico1 *p)
{
  bufAppend("OperadorAritmetico1");
}
void ShowAbsyn::visitOperadorAritmetico2(OperadorAritmetico2 *p)
{
  bufAppend("OperadorAritmetico2");
}
void ShowAbsyn::visitOperadorAritmetico3(OperadorAritmetico3 *p)
{
  bufAppend("OperadorAritmetico3");
}
void ShowAbsyn::visitOperadorAritmetico4(OperadorAritmetico4 *p)
{
  bufAppend("OperadorAritmetico4");
}
void ShowAbsyn::visitCase(Case *p) {} //abstract class

void ShowAbsyn::visitLCase(LCase *p)
{
  bufAppend('(');
  bufAppend("LCase");
  bufAppend(' ');
  bufAppend('[');
  if (p->seletor_)  p->seletor_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->regraseletor_)  p->regraseletor_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitRegraSeletor(RegraSeletor *p) {} //abstract class

void ShowAbsyn::visitRegraSeletor1(RegraSeletor1 *p)
{
  bufAppend('(');
  bufAppend("RegraSeletor1");
  bufAppend(' ');
  bufAppend('[');
  if (p->seletor_)  p->seletor_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->comando_)  p->comando_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitRegraSeletor2(RegraSeletor2 *p)
{
  bufAppend('(');
  bufAppend("RegraSeletor2");
  bufAppend(' ');
  bufAppend('[');
  if (p->seletor_)  p->seletor_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->comando_)  p->comando_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->regraseletor_)  p->regraseletor_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitSeletor(Seletor *p) {} //abstract class

void ShowAbsyn::visitSeletorInteger(SeletorInteger *p)
{
  bufAppend('(');
  bufAppend("SeletorInteger");
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitSeletorChar(SeletorChar *p)
{
  bufAppend('(');
  bufAppend("SeletorChar");
  bufAppend(' ');
  visitChar(p->char_);
  bufAppend(')');
}
void ShowAbsyn::visitSeletorIdent(SeletorIdent *p)
{
  bufAppend('(');
  bufAppend("SeletorIdent");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitChamadaFuncaoEProc(ChamadaFuncaoEProc *p) {} //abstract class

void ShowAbsyn::visitLChamad(LChamad *p)
{
  bufAppend('(');
  bufAppend("LChamad");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->listaident_)  p->listaident_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitListaIdent(ListaIdent *p) {} //abstract class

void ShowAbsyn::visitListaIdentIdent(ListaIdentIdent *p)
{
  bufAppend('(');
  bufAppend("ListaIdentIdent");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitListaIdent1(ListaIdent1 *p)
{
  bufAppend('(');
  bufAppend("ListaIdent1");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->listaident_)  p->listaident_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFuncao(Funcao *p) {} //abstract class

void ShowAbsyn::visitLFuncao(LFuncao *p)
{
  bufAppend('(');
  bufAppend("LFuncao");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->regrablocovar_)  p->regrablocovar_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->regratipo_)  p->regratipo_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->blocovar_)  p->blocovar_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->blococomando_)  p->blococomando_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitProcedimento(Procedimento *p) {} //abstract class

void ShowAbsyn::visitProcedimento1(Procedimento1 *p)
{
  bufAppend('(');
  bufAppend("Procedimento1");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->regrablocovar_)  p->regrablocovar_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->blocovar_)  p->blocovar_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->blococomando_)  p->blococomando_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitProcedimento2(Procedimento2 *p)
{
  bufAppend('(');
  bufAppend("Procedimento2");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->blocovar_)  p->blocovar_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->blococomando_)  p->blococomando_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitExpressaoAritmetica(ExpressaoAritmetica *p) {} //abstract class

void ShowAbsyn::visitExpAr(ExpAr *p)
{
  bufAppend('(');
  bufAppend("ExpAr");
  bufAppend(' ');
  bufAppend('[');
  if (p->operando_)  p->operando_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->regraaritmetica_)  p->regraaritmetica_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitOperando(Operando *p) {} //abstract class

void ShowAbsyn::visitOperandoInteger(OperandoInteger *p)
{
  bufAppend('(');
  bufAppend("OperandoInteger");
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitOperandoDouble(OperandoDouble *p)
{
  bufAppend('(');
  bufAppend("OperandoDouble");
  bufAppend(' ');
  visitDouble(p->double_);
  bufAppend(')');
}
void ShowAbsyn::visitOperandoIdent(OperandoIdent *p)
{
  bufAppend('(');
  bufAppend("OperandoIdent");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitRegraAritmetica(RegraAritmetica *p) {} //abstract class

void ShowAbsyn::visitRegraAritmetica1(RegraAritmetica1 *p)
{
  bufAppend('(');
  bufAppend("RegraAritmetica1");
  bufAppend(' ');
  bufAppend('[');
  if (p->operadoraritmetico_)  p->operadoraritmetico_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->operando_)  p->operando_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitRegraAritmetica2(RegraAritmetica2 *p)
{
  bufAppend('(');
  bufAppend("RegraAritmetica2");
  bufAppend(' ');
  bufAppend('[');
  if (p->operadoraritmetico_)  p->operadoraritmetico_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->operando_)  p->operando_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->regraaritmetica_)  p->regraaritmetica_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitExpressaoRelacional(ExpressaoRelacional *p) {} //abstract class

void ShowAbsyn::visitExpressaoRelacionalOperando(ExpressaoRelacionalOperando *p)
{
  bufAppend('(');
  bufAppend("ExpressaoRelacionalOperando");
  bufAppend(' ');
  bufAppend('[');
  if (p->operando_)  p->operando_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitExpressaoRelacional1(ExpressaoRelacional1 *p)
{
  bufAppend('(');
  bufAppend("ExpressaoRelacional1");
  bufAppend(' ');
  bufAppend('[');
  if (p->operando_)  p->operando_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->regrarelacional_)  p->regrarelacional_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitExpressaoRelacional2(ExpressaoRelacional2 *p)
{
  bufAppend('(');
  bufAppend("ExpressaoRelacional2");
  bufAppend(' ');
  bufAppend('[');
  if (p->expressaoaritmetica_)  p->expressaoaritmetica_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->regrarelacional_)  p->regrarelacional_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitRegraRelacional(RegraRelacional *p) {} //abstract class

void ShowAbsyn::visitRegraRelacional1(RegraRelacional1 *p)
{
  bufAppend('(');
  bufAppend("RegraRelacional1");
  bufAppend(' ');
  bufAppend('[');
  if (p->operadorrelacional_)  p->operadorrelacional_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->operando_)  p->operando_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitRegraRelacional2(RegraRelacional2 *p)
{
  bufAppend('(');
  bufAppend("RegraRelacional2");
  bufAppend(' ');
  bufAppend('[');
  if (p->operadorrelacional_)  p->operadorrelacional_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->expressaoaritmetica_)  p->expressaoaritmetica_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitExpressaoLogica(ExpressaoLogica *p) {} //abstract class

void ShowAbsyn::visitExpressaoLogica_falso(ExpressaoLogica_falso *p)
{
  bufAppend("ExpressaoLogica_falso");
}
void ShowAbsyn::visitExpressaoLogica1(ExpressaoLogica1 *p)
{
  bufAppend('(');
  bufAppend("ExpressaoLogica1");
  bufAppend(' ');
  bufAppend('[');
  if (p->regralogico_)  p->regralogico_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitExpressaoLogica_verdadeiro(ExpressaoLogica_verdadeiro *p)
{
  bufAppend("ExpressaoLogica_verdadeiro");
}
void ShowAbsyn::visitExpressaoLogica2(ExpressaoLogica2 *p)
{
  bufAppend('(');
  bufAppend("ExpressaoLogica2");
  bufAppend(' ');
  bufAppend('[');
  if (p->regralogico_)  p->regralogico_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitExpressaoLogicaExpressaoRelacional(ExpressaoLogicaExpressaoRelacional *p)
{
  bufAppend('(');
  bufAppend("ExpressaoLogicaExpressaoRelacional");
  bufAppend(' ');
  bufAppend('[');
  if (p->expressaorelacional_)  p->expressaorelacional_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitExpressaoLogica3(ExpressaoLogica3 *p)
{
  bufAppend('(');
  bufAppend("ExpressaoLogica3");
  bufAppend(' ');
  bufAppend('[');
  if (p->expressaorelacional_)  p->expressaorelacional_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->regralogico_)  p->regralogico_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitExpressaoLogica4(ExpressaoLogica4 *p)
{
  bufAppend('(');
  bufAppend("ExpressaoLogica4");
  bufAppend(' ');
  bufAppend('[');
  if (p->negacao_)  p->negacao_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->expressaologica_)  p->expressaologica_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitExpressaoLogica5(ExpressaoLogica5 *p)
{
  bufAppend('(');
  bufAppend("ExpressaoLogica5");
  bufAppend(' ');
  bufAppend('[');
  if (p->negacao_)  p->negacao_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->expressaologica_)  p->expressaologica_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->regralogico_)  p->regralogico_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitRegraLogico(RegraLogico *p) {} //abstract class

void ShowAbsyn::visitRegraLogico1(RegraLogico1 *p)
{
  bufAppend('(');
  bufAppend("RegraLogico1");
  bufAppend(' ');
  bufAppend('[');
  if (p->operadorlogico_)  p->operadorlogico_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->expressaologica_)  p->expressaologica_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitRegraLogico2(RegraLogico2 *p)
{
  bufAppend('(');
  bufAppend("RegraLogico2");
  bufAppend(' ');
  bufAppend('[');
  if (p->operadorlogico_)  p->operadorlogico_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->expressaologica_)  p->expressaologica_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->regralogico_)  p->regralogico_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppend(tmp);
}
void ShowAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppend(tmp);
}
void ShowAbsyn::visitChar(Char c)
{
  bufAppend('\'');
  bufAppend(c);
  bufAppend('\'');
}
void ShowAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}
void ShowAbsyn::visitIdent(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}


