/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Visitor Design Pattern Skeleton. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "Skeleton.H"
#include <map>
#include <vector>
#include <stack>
#include <iostream>
#include <string>

using namespace std;

// key = ident; value = pair<tipo, valor>
map<string, pair<string, string> > symbolicTable;

string reservedWords[48] = {"ate","caso","char","const","de","enquanto","entao","faca","falso","fim","funcao","inicio","int","para","procedimento","programa","real","registro","se","senao","sovai","tipo","var","verdadeiro","vetor",";",":",".","=",":=","^","[","]","(",")",">","<","<>",">=","<=","&&","||","&|","!","+","-","*","/"};

stack<string> identStack;

stack<char> operatorsStack;

vector<string> errors;

void Skeleton::visitEntry(Entry *t) {} //abstract class
void Skeleton::visitBlocoDefinicoes(BlocoDefinicoes *t) {} //abstract class
void Skeleton::visitBlocoFuncaoEProc(BlocoFuncaoEProc *t) {} //abstract class
void Skeleton::visitBlocoConstante(BlocoConstante *t) {} //abstract class
void Skeleton::visitRegraBlocoConstante(RegraBlocoConstante *t) {} //abstract class
void Skeleton::visitBlocoTipo(BlocoTipo *t) {} //abstract class
void Skeleton::visitRegraBlocoTipo(RegraBlocoTipo *t) {} //abstract class
void Skeleton::visitBlocoVar(BlocoVar *t) {} //abstract class
void Skeleton::visitRegraBlocoVar(RegraBlocoVar *t) {} //abstract class
void Skeleton::visitBlocoComando(BlocoComando *t) {} //abstract class
void Skeleton::visitRegraComando(RegraComando *t) {} //abstract class
void Skeleton::visitComando(Comando *t) {} //abstract class
void Skeleton::visitAtribuicao(Atribuicao *t) {} //abstract class
void Skeleton::visitSubEscrito(SubEscrito *t) {} //abstract class
void Skeleton::visitRegraTipo(RegraTipo *t) {} //abstract class
void Skeleton::visitTipoPrimitivo(TipoPrimitivo *t) {} //abstract class
void Skeleton::visitValor(Valor *t) {} //abstract class
void Skeleton::visitTipoDerivado(TipoDerivado *t) {} //abstract class
void Skeleton::visitPonteiro(Ponteiro *t) {} //abstract class
void Skeleton::visitVetor(Vetor *t) {} //abstract class
void Skeleton::visitIf(If *t) {} //abstract class
void Skeleton::visitWhile(While *t) {} //abstract class
void Skeleton::visitFor(For *t) {} //abstract class
void Skeleton::visitGoto(Goto *t) {} //abstract class
void Skeleton::visitRotulo(Rotulo *t) {} //abstract class
void Skeleton::visitStruct(Struct *t) {} //abstract class
void Skeleton::visitDefinicaoCampoStruct(DefinicaoCampoStruct *t) {} //abstract class
void Skeleton::visitAtribuicaoStruct(AtribuicaoStruct *t) {} //abstract class
void Skeleton::visitOperadorRelacional(OperadorRelacional *t) {} //abstract class
void Skeleton::visitOperadorLogico(OperadorLogico *t) {} //abstract class
void Skeleton::visitNegacao(Negacao *t) {} //abstract class
void Skeleton::visitOperadorAritmetico(OperadorAritmetico *t) {} //abstract class
void Skeleton::visitCase(Case *t) {} //abstract class
void Skeleton::visitRegraSeletor(RegraSeletor *t) {} //abstract class
void Skeleton::visitSeletor(Seletor *t) {} //abstract class
void Skeleton::visitChamadaFuncaoEProc(ChamadaFuncaoEProc *t) {} //abstract class
void Skeleton::visitListaIdent(ListaIdent *t) {} //abstract class
void Skeleton::visitFuncao(Funcao *t) {} //abstract class
void Skeleton::visitProcedimento(Procedimento *t) {} //abstract class
void Skeleton::visitExpressaoAritmetica(ExpressaoAritmetica *t) {} //abstract class
void Skeleton::visitOperando(Operando *t) {} //abstract class
void Skeleton::visitRegraAritmetica(RegraAritmetica *t) {} //abstract class
void Skeleton::visitExpressaoRelacional(ExpressaoRelacional *t) {} //abstract class
void Skeleton::visitRegraRelacional(RegraRelacional *t) {} //abstract class
void Skeleton::visitExpressaoLogica(ExpressaoLogica *t) {} //abstract class
void Skeleton::visitRegraLogico(RegraLogico *t) {} //abstract class

void printSymbolicTable() {
  map<string, pair<string,string> >::iterator itr;
    cout << "\nTabela simbólica:\n";
    cout << "\tKEY\tELEMENT\tVALUES\n";
    for (itr = symbolicTable.begin(); itr != symbolicTable.end(); ++itr) {
        cout << '\t' << itr->first << '\t' << itr->second.first << '\t' << itr->second.second << '\n';
    }
    cout << endl;
}

void printStackIdent() {
  if (identStack.empty())
    cout << "Pilha vazia!\n";
  stack<string> new_stack;
  while (!identStack.empty())
  {
    new_stack.push(identStack.top());
    cout << new_stack.top() << ", ";
    identStack.pop();
  }
  cout << endl;
  while (!new_stack.empty())
  {
    identStack.push(new_stack.top());
    new_stack.pop();
  }
}

void printStackOperator() {
  if (operatorsStack.empty())
    cout << "Pilha vazia!\n";
  stack<char> new_stack;
  while (!operatorsStack.empty())
  {
    new_stack.push(operatorsStack.top());
    cout << new_stack.top() << ", ";
    operatorsStack.pop();
  }
  cout << endl;
  while (!new_stack.empty())
  {
    operatorsStack.push(new_stack.top());
    new_stack.pop();
  }
}

int stringToInteger(string str)
{
    int temp = 0;
    for (int i = 0; i < str.length(); i++) {
        temp = temp * 10 + (str[i] - '0');
    }
    return temp;
}

void Skeleton::visitLEntry(LEntry *l_entry)
{
  /* Code For LEntry Goes Here */

  visitIdent(l_entry->ident_);
  if (l_entry->blocodefinicoes_) l_entry->blocodefinicoes_->accept(this);
  if (l_entry->blococomando_) l_entry->blococomando_->accept(this);

  printSymbolicTable();

  cout << "erros: " << endl;
  for(int i=0; i < errors.size(); i++)
    cout << errors.at(i) << '\n';
}

void Skeleton::visitBlocoDefinicoes1(BlocoDefinicoes1 *bloco_definicoes)
{
  /* Code For BlocoDefinicoes1 Goes Here */

  if (bloco_definicoes->blocofuncaoeproc_) bloco_definicoes->blocofuncaoeproc_->accept(this);
  if (bloco_definicoes->blocodefinicoes_) bloco_definicoes->blocodefinicoes_->accept(this);

}

void Skeleton::visitBlocoDefinicoes2(BlocoDefinicoes2 *bloco_definicoes)
{
  /* Code For BlocoDefinicoes2 Goes Here */

  if (bloco_definicoes->blococonstante_) bloco_definicoes->blococonstante_->accept(this);
  if (bloco_definicoes->blocodefinicoes_) bloco_definicoes->blocodefinicoes_->accept(this);

}

void Skeleton::visitBlocoDefinicoes3(BlocoDefinicoes3 *bloco_definicoes)
{
  /* Code For BlocoDefinicoes3 Goes Here */

  if (bloco_definicoes->blocotipo_) bloco_definicoes->blocotipo_->accept(this);
  if (bloco_definicoes->blocodefinicoes_) bloco_definicoes->blocodefinicoes_->accept(this);

}

void Skeleton::visitBlocoDefinicoes4(BlocoDefinicoes4 *bloco_definicoes)
{
  /* Code For BlocoDefinicoes4 Goes Here */

  if (bloco_definicoes->blocovar_) bloco_definicoes->blocovar_->accept(this);
  if (bloco_definicoes->blocodefinicoes_) bloco_definicoes->blocodefinicoes_->accept(this);

}

void Skeleton::visitBlocoDefinicoes_(BlocoDefinicoes_ *bloco_definicoes)
{
  /* Code For BlocoDefinicoes_ Goes Here */


}

void Skeleton::visitBlocoFuncaoEProcFuncao(BlocoFuncaoEProcFuncao *bloco_funcao_e_proc_funcao)
{
  /* Code For BlocoFuncaoEProcFuncao Goes Here */

  if (bloco_funcao_e_proc_funcao->funcao_) bloco_funcao_e_proc_funcao->funcao_->accept(this);

}

void Skeleton::visitBlocoFuncaoEProc1(BlocoFuncaoEProc1 *bloco_funcao_e_proc)
{
  /* Code For BlocoFuncaoEProc1 Goes Here */

  if (bloco_funcao_e_proc->funcao_) bloco_funcao_e_proc->funcao_->accept(this);
  if (bloco_funcao_e_proc->blocofuncaoeproc_) bloco_funcao_e_proc->blocofuncaoeproc_->accept(this);

}

void Skeleton::visitBlocoFuncaoEProcProcedimento(BlocoFuncaoEProcProcedimento *bloco_funcao_e_proc_procedimento)
{
  /* Code For BlocoFuncaoEProcProcedimento Goes Here */

  if (bloco_funcao_e_proc_procedimento->procedimento_) bloco_funcao_e_proc_procedimento->procedimento_->accept(this);

}

void Skeleton::visitBlocoFuncaoEProc2(BlocoFuncaoEProc2 *bloco_funcao_e_proc)
{
  /* Code For BlocoFuncaoEProc2 Goes Here */

  if (bloco_funcao_e_proc->procedimento_) bloco_funcao_e_proc->procedimento_->accept(this);
  if (bloco_funcao_e_proc->blocofuncaoeproc_) bloco_funcao_e_proc->blocofuncaoeproc_->accept(this);

}

void Skeleton::visitBlocoFuncaoEProc_(BlocoFuncaoEProc_ *bloco_funcao_e_proc)
{
  /* Code For BlocoFuncaoEProc_ Goes Here */


}

void Skeleton::visitBlocoConstante1(BlocoConstante1 *bloco_constante)
{
  /* Code For BlocoConstante1 Goes Here */

  if (bloco_constante->regrablococonstante_) bloco_constante->regrablococonstante_->accept(this);

}

void Skeleton::visitBlocoConstante_(BlocoConstante_ *bloco_constante)
{
  /* Code For BlocoConstante_ Goes Here */


}

void Skeleton::visitRegraBlocoConstante1(RegraBlocoConstante1 *regra_bloco_constante)
{
  /* Code For RegraBlocoConstante1 Goes Here */

  visitIdent(regra_bloco_constante->ident_);
  if (regra_bloco_constante->valor_) regra_bloco_constante->valor_->accept(this);

}

void Skeleton::visitRegraBlocoConstante2(RegraBlocoConstante2 *regra_bloco_constante)
{
  /* Code For RegraBlocoConstante2 Goes Here */

  visitIdent(regra_bloco_constante->ident_);
  if (regra_bloco_constante->valor_) regra_bloco_constante->valor_->accept(this);
  if (regra_bloco_constante->regrablococonstante_) regra_bloco_constante->regrablococonstante_->accept(this);

}

void Skeleton::visitBlocoTipo1(BlocoTipo1 *bloco_tipo)
{
  /* Code For BlocoTipo1 Goes Here */

  if (bloco_tipo->regrablocotipo_) bloco_tipo->regrablocotipo_->accept(this);

}

void Skeleton::visitBlocoTipo_(BlocoTipo_ *bloco_tipo)
{
  /* Code For BlocoTipo_ Goes Here */


}

void Skeleton::visitRegraBlocoTipo1(RegraBlocoTipo1 *regra_bloco_tipo)
{
  /* Code For RegraBlocoTipo1 Goes Here */

  visitIdent(regra_bloco_tipo->ident_);
  if (regra_bloco_tipo->regratipo_) regra_bloco_tipo->regratipo_->accept(this);

}

void Skeleton::visitRegraBlocoTipo2(RegraBlocoTipo2 *regra_bloco_tipo)
{
  /* Code For RegraBlocoTipo2 Goes Here */

  visitIdent(regra_bloco_tipo->ident_);
  if (regra_bloco_tipo->regratipo_) regra_bloco_tipo->regratipo_->accept(this);
  if (regra_bloco_tipo->regrablocotipo_) regra_bloco_tipo->regrablocotipo_->accept(this);

}

void Skeleton::visitBlocoVar1(BlocoVar1 *bloco_var)
{
  /* Code For BlocoVar1 Goes Here */

  if (bloco_var->regrablocovar_) bloco_var->regrablocovar_->accept(this);

}

void Skeleton::visitBlocoVar_(BlocoVar_ *bloco_var)
{
  /* Code For BlocoVar_ Goes Here */


}

void Skeleton::visitRegraBlocoVar1(RegraBlocoVar1 *regra_bloco_var)
{
  /* Code For RegraBlocoVar1 Goes Here */
  string ident = regra_bloco_var->ident_;
  identStack.push(regra_bloco_var->ident_);

  visitIdent(regra_bloco_var->ident_);
  if (regra_bloco_var->regratipo_) regra_bloco_var->regratipo_->accept(this);

}

void Skeleton::visitRegraBlocoVar2(RegraBlocoVar2 *regra_bloco_var)
{
  /* Code For RegraBlocoVar2 Goes Here */
  string ident = regra_bloco_var->ident_;
  identStack.push(ident);

  visitIdent(regra_bloco_var->ident_);
  if (regra_bloco_var->regratipo_) regra_bloco_var->regratipo_->accept(this);

  if (regra_bloco_var->regrablocovar_) regra_bloco_var->regrablocovar_->accept(this);

}

void Skeleton::visitRegraBlocoVar3(RegraBlocoVar3 *regra_bloco_var)
{
  /* Code For RegraBlocoVar3 Goes Here */

  if (regra_bloco_var->listaident_) regra_bloco_var->listaident_->accept(this);
  if (regra_bloco_var->regratipo_) regra_bloco_var->regratipo_->accept(this);

}

void Skeleton::visitRegraBlocoVar4(RegraBlocoVar4 *regra_bloco_var)
{
  /* Code For RegraBlocoVar4 Goes Here */

  if (regra_bloco_var->listaident_) regra_bloco_var->listaident_->accept(this);
  if (regra_bloco_var->regratipo_) regra_bloco_var->regratipo_->accept(this);
  if (regra_bloco_var->regrablocovar_) regra_bloco_var->regrablocovar_->accept(this);

}

void Skeleton::visitBlocoComando1(BlocoComando1 *bloco_comando)
{
  /* Code For BlocoComando1 Goes Here */

  if (bloco_comando->regracomando_) bloco_comando->regracomando_->accept(this);

}

void Skeleton::visitBlocoComando_(BlocoComando_ *bloco_comando)
{
  /* Code For BlocoComando_ Goes Here */


}

void Skeleton::visitRegraComando1(RegraComando1 *regra_comando)
{
  /* Code For RegraComando1 Goes Here */

  if (regra_comando->comando_) regra_comando->comando_->accept(this);

}

void Skeleton::visitRegraComando2(RegraComando2 *regra_comando)
{
  /* Code For RegraComando2 Goes Here */

  if (regra_comando->comando_) regra_comando->comando_->accept(this);
  if (regra_comando->regracomando_) regra_comando->regracomando_->accept(this);

}

void Skeleton::visitComandoAtribuicao(ComandoAtribuicao *comando_atribuicao)
{
  /* Code For ComandoAtribuicao Goes Here */

  if (comando_atribuicao->atribuicao_) comando_atribuicao->atribuicao_->accept(this);

}

void Skeleton::visitComandoIf(ComandoIf *comando_if)
{
  /* Code For ComandoIf Goes Here */

  if (comando_if->if_) comando_if->if_->accept(this);

}

void Skeleton::visitComandoWhile(ComandoWhile *comando_while)
{
  /* Code For ComandoWhile Goes Here */

  if (comando_while->while_) comando_while->while_->accept(this);

}

void Skeleton::visitComandoFor(ComandoFor *comando_for)
{
  /* Code For ComandoFor Goes Here */

  if (comando_for->for_) comando_for->for_->accept(this);

}

void Skeleton::visitComandoGoto(ComandoGoto *comando_goto)
{
  /* Code For ComandoGoto Goes Here */

  if (comando_goto->goto_) comando_goto->goto_->accept(this);

}

void Skeleton::visitComandoCase(ComandoCase *comando_case)
{
  /* Code For ComandoCase Goes Here */

  if (comando_case->case_) comando_case->case_->accept(this);

}

void Skeleton::visitComandoChamadaFuncaoEProc(ComandoChamadaFuncaoEProc *comando_chamada_funcao_e_proc)
{
  /* Code For ComandoChamadaFuncaoEProc Goes Here */

  if (comando_chamada_funcao_e_proc->chamadafuncaoeproc_) comando_chamada_funcao_e_proc->chamadafuncaoeproc_->accept(this);

}

void Skeleton::visitAtribuicao1(Atribuicao1 *atribuicao)
{
  /* Code For Atribuicao1 Goes Here */

  if(symbolicTable.find(atribuicao->ident_) == symbolicTable.end()) {
    // ident inexistente na tabela simbólica
    errors.push_back("Variável indefinida - a variável " + atribuicao->ident_ + " não foi definida no bloco de variáveis.");
    return;
  }
  
  identStack.push(atribuicao->ident_);

  visitIdent(atribuicao->ident_);
  if (atribuicao->valor_) atribuicao->valor_->accept(this);

}

void Skeleton::visitAtribuicao2(Atribuicao2 *atribuicao)
{
  /* Code For Atribuicao2 Goes Here */
  if(symbolicTable.find(atribuicao->ident_) == symbolicTable.end()) {
    errors.push_back("Variável indefinida - a variável " + atribuicao->ident_ + " não foi definida no bloco de variáveis.");
    return;
  }

  visitIdent(atribuicao->ident_);
  if (atribuicao->expressaoaritmetica_) atribuicao->expressaoaritmetica_->accept(this);

  string operando1 = identStack.top();
  identStack.pop();
  string valor1 = symbolicTable.find(operando1)->second.second;
  int resExpAr = stringToInteger(valor1);

  while(!operatorsStack.empty() && !identStack.empty()) {
    string operando2 = identStack.top();
    identStack.pop();

    char operador = operatorsStack.top();
    operatorsStack.pop();

    string valor2 = symbolicTable.find(operando2)->second.second;
    int valor2Numeric = stringToInteger(valor2);

    switch (operador)
    {
    case '+':
      resExpAr += valor2Numeric;
      break;
    case '-':
      resExpAr -= valor2Numeric;
      break;
    case '*':
      resExpAr *= valor2Numeric;
      break;
    case '/':
      resExpAr /= valor2Numeric;
      break;
    default:
      break;
    }

    operando1 = operando2;
  }

  char resString[10];
  sprintf(resString, "%d", resExpAr);
  symbolicTable[atribuicao->ident_].second = resString;
}

void Skeleton::visitAtribuicao3(Atribuicao3 *atribuicao)
{
  /* Code For Atribuicao3 Goes Here */

  visitIdent(atribuicao->ident_1);
  visitIdent(atribuicao->ident_2);

  string ident1 = atribuicao->ident_1;
  string ident2 = atribuicao->ident_2;

  if(symbolicTable.find(ident1) == symbolicTable.end()) {
    errors.push_back("Variável indefinida - a variável " + atribuicao->ident_1 + " não foi definida no bloco de variáveis.");
  }

  if(symbolicTable.find(ident2) == symbolicTable.end()) {
    errors.push_back("Variável indefinida - a variável " + atribuicao->ident_2 + " não foi definida no bloco de variáveis.");
  }

  if(symbolicTable[ident2].second == "_default") {
    errors.push_back("Variável não inicializada - a variável " + atribuicao->ident_2 + " não foi inicializada no bloco de comandos.");
  }

  string tipo1 = symbolicTable[ident1].first;
  string tipo2 = symbolicTable[ident2].first;

  if(tipo1 != tipo2) {
    errors.push_back("Incompatibilidade de tipos - as variáveis " + ident1 + " e " + ident2 + " não são do mesmo tipo.");
    return;
  }

  symbolicTable[ident1].second = symbolicTable[ident2].second;
}

void Skeleton::visitAtribuicao4(Atribuicao4 *atribuicao)
{
  /* Code For Atribuicao4 Goes Here */

  visitIdent(atribuicao->ident_);
  if (atribuicao->subescrito_) atribuicao->subescrito_->accept(this);
  if (atribuicao->valor_) atribuicao->valor_->accept(this);

}

void Skeleton::visitAtribuicao5(Atribuicao5 *atribuicao)
{
  /* Code For Atribuicao5 Goes Here */

  visitIdent(atribuicao->ident_);
  if (atribuicao->valor_) atribuicao->valor_->accept(this);

}

void Skeleton::visitAtribuicaoAtribuicaoStruct(AtribuicaoAtribuicaoStruct *atribuicao_atribuicao_struct)
{
  /* Code For AtribuicaoAtribuicaoStruct Goes Here */

  if (atribuicao_atribuicao_struct->atribuicaostruct_) atribuicao_atribuicao_struct->atribuicaostruct_->accept(this);

}

void Skeleton::visitAtribuicao6(Atribuicao6 *atribuicao)
{
  /* Code For Atribuicao6 Goes Here */

  visitIdent(atribuicao->ident_);
  if (atribuicao->chamadafuncaoeproc_) atribuicao->chamadafuncaoeproc_->accept(this);

}

void Skeleton::visitSubEscritoIdent(SubEscritoIdent *sub_escrito_ident)
{
  /* Code For SubEscritoIdent Goes Here */

  visitIdent(sub_escrito_ident->ident_);

}

void Skeleton::visitSubEscritoInteger(SubEscritoInteger *sub_escrito_integer)
{
  /* Code For SubEscritoInteger Goes Here */

  visitInteger(sub_escrito_integer->integer_);

}

void Skeleton::visitRegraTipoTipoPrimitivo(RegraTipoTipoPrimitivo *regra_tipo_tipo_primitivo)
{
  /* Code For RegraTipoTipoPrimitivo Goes Here */

  if (regra_tipo_tipo_primitivo->tipoprimitivo_) regra_tipo_tipo_primitivo->tipoprimitivo_->accept(this);

}

void Skeleton::visitRegraTipoTipoDerivado(RegraTipoTipoDerivado *regra_tipo_tipo_derivado)
{
  /* Code For RegraTipoTipoDerivado Goes Here */

  if (regra_tipo_tipo_derivado->tipoderivado_) regra_tipo_tipo_derivado->tipoderivado_->accept(this);

}

void Skeleton::visitRegraTipoIdent(RegraTipoIdent *regra_tipo_ident)
{
  /* Code For RegraTipoIdent Goes Here */

  visitIdent(regra_tipo_ident->ident_);

}

void Skeleton::visitTipoPrimitivo_int(TipoPrimitivo_int *tipo_primitivo_int)
{
  /* Code For TipoPrimitivo_int Goes Here */
  string ident = identStack.top();
  identStack.pop();

  pair<string, string> values;
  values.first = "int";
  values.second = "_default";

  pair<string, pair<string,string> > key;
  key.first = ident;
  key.second = values;
  symbolicTable.insert(key);
}

void Skeleton::visitTipoPrimitivo_real(TipoPrimitivo_real *tipo_primitivo_real)
{
  /* Code For TipoPrimitivo_real Goes Here */
  string ident = identStack.top();
  identStack.pop();

  pair<string, string> values;
  values.first = "real";
  values.second = "_default";

  pair<string, pair<string,string> > key;
  key.first = ident;
  key.second = values;
  symbolicTable.insert(key);

}

void Skeleton::visitTipoPrimitivo_char(TipoPrimitivo_char *tipo_primitivo_char)
{
  /* Code For TipoPrimitivo_char Goes Here */
  string ident = identStack.top();
  identStack.pop();

  pair<string, string> values;
  values.first = "char";
  values.second = "_default";

  pair<string, pair<string,string> > key;
  key.first = ident;
  key.second = values;
  symbolicTable.insert(key);

}

void Skeleton::visitValorInteger(ValorInteger *valor_integer)
{
  /* Code For ValorInteger Goes Here */

  visitInteger(valor_integer->integer_);

}

void Skeleton::visitValorDouble(ValorDouble *valor_double)
{
  /* Code For ValorDouble Goes Here */

  visitDouble(valor_double->double_);

}

void Skeleton::visitValorChar(ValorChar *valor_char)
{
  /* Code For ValorChar Goes Here */

  visitChar(valor_char->char_);

}

void Skeleton::visitValorString(ValorString *valor_string)
{
  /* Code For ValorString Goes Here */

  visitString(valor_string->string_);

}

void Skeleton::visitTipoDerivadoPonteiro(TipoDerivadoPonteiro *tipo_derivado_ponteiro)
{
  /* Code For TipoDerivadoPonteiro Goes Here */

  if (tipo_derivado_ponteiro->ponteiro_) tipo_derivado_ponteiro->ponteiro_->accept(this);

}

void Skeleton::visitTipoDerivadoVetor(TipoDerivadoVetor *tipo_derivado_vetor)
{
  /* Code For TipoDerivadoVetor Goes Here */

  if (tipo_derivado_vetor->vetor_) tipo_derivado_vetor->vetor_->accept(this);

}

void Skeleton::visitTipoDerivadoStruct(TipoDerivadoStruct *tipo_derivado_struct)
{
  /* Code For TipoDerivadoStruct Goes Here */

  if (tipo_derivado_struct->struct_) tipo_derivado_struct->struct_->accept(this);

}

void Skeleton::visitPonteiro1(Ponteiro1 *ponteiro)
{
  /* Code For Ponteiro1 Goes Here */

  if (ponteiro->tipoprimitivo_) ponteiro->tipoprimitivo_->accept(this);

}

void Skeleton::visitPonteiro2(Ponteiro2 *ponteiro)
{
  /* Code For Ponteiro2 Goes Here */

  if (ponteiro->tipoderivado_) ponteiro->tipoderivado_->accept(this);

}

void Skeleton::visitLVetor(LVetor *l_vetor)
{
  /* Code For LVetor Goes Here */

  visitInteger(l_vetor->integer_1);
  visitInteger(l_vetor->integer_2);
  if (l_vetor->tipoprimitivo_) l_vetor->tipoprimitivo_->accept(this);

}

void Skeleton::visitIf1(If1 *if_)
{
  /* Code For If1 Goes Here */

  if (if_->expressaologica_) if_->expressaologica_->accept(this);
  if (if_->blococomando_) if_->blococomando_->accept(this);

}

void Skeleton::visitIf2(If2 *if_)
{
  /* Code For If2 Goes Here */

  if (if_->expressaologica_) if_->expressaologica_->accept(this);
  if (if_->blococomando_1) if_->blococomando_1->accept(this);
  if (if_->blococomando_2) if_->blococomando_2->accept(this);

}

void Skeleton::visitLWhile(LWhile *l_while)
{
  /* Code For LWhile Goes Here */

  if (l_while->expressaologica_) l_while->expressaologica_->accept(this);
  if (l_while->blococomando_) l_while->blococomando_->accept(this);

}

void Skeleton::visitFor1(For1 *for_)
{
  /* Code For For1 Goes Here */

  if (for_->atribuicao_) for_->atribuicao_->accept(this);
  visitInteger(for_->integer_);
  if (for_->blococomando_) for_->blococomando_->accept(this);

}

void Skeleton::visitFor2(For2 *for_)
{
  /* Code For For2 Goes Here */

  if (for_->atribuicao_) for_->atribuicao_->accept(this);
  visitIdent(for_->ident_);
  if (for_->blococomando_) for_->blococomando_->accept(this);

}

void Skeleton::visitLGoto(LGoto *l_goto)
{
  /* Code For LGoto Goes Here */

  visitIdent(l_goto->ident_);

}

void Skeleton::visitLRotulo(LRotulo *l_rotulo)
{
  /* Code For LRotulo Goes Here */

  visitIdent(l_rotulo->ident_);
  if (l_rotulo->regracomando_) l_rotulo->regracomando_->accept(this);

}

void Skeleton::visitLStruct(LStruct *l_struct)
{
  /* Code For LStruct Goes Here */

  if (l_struct->definicaocampostruct_) l_struct->definicaocampostruct_->accept(this);

}

void Skeleton::visitDefinicaoCampoStruct1(DefinicaoCampoStruct1 *definicao_campo_struct)
{
  /* Code For DefinicaoCampoStruct1 Goes Here */

  visitIdent(definicao_campo_struct->ident_);
  if (definicao_campo_struct->regratipo_) definicao_campo_struct->regratipo_->accept(this);

}

void Skeleton::visitDefinicaoCampoStruct2(DefinicaoCampoStruct2 *definicao_campo_struct)
{
  /* Code For DefinicaoCampoStruct2 Goes Here */

  visitIdent(definicao_campo_struct->ident_);
  if (definicao_campo_struct->regratipo_) definicao_campo_struct->regratipo_->accept(this);
  if (definicao_campo_struct->definicaocampostruct_) definicao_campo_struct->definicaocampostruct_->accept(this);

}

void Skeleton::visitAtribuicaoStruct1(AtribuicaoStruct1 *atribuicao_struct)
{
  /* Code For AtribuicaoStruct1 Goes Here */

  visitIdent(atribuicao_struct->ident_1);
  visitIdent(atribuicao_struct->ident_2);
  if (atribuicao_struct->valor_) atribuicao_struct->valor_->accept(this);

}

void Skeleton::visitAtribuicaoStruct2(AtribuicaoStruct2 *atribuicao_struct)
{
  /* Code For AtribuicaoStruct2 Goes Here */

  visitIdent(atribuicao_struct->ident_1);
  visitIdent(atribuicao_struct->ident_2);
  if (atribuicao_struct->valor_) atribuicao_struct->valor_->accept(this);
  if (atribuicao_struct->atribuicaostruct_) atribuicao_struct->atribuicaostruct_->accept(this);

}

void Skeleton::visitOperadorRelacional1(OperadorRelacional1 *operador_relacional)
{
  /* Code For OperadorRelacional1 Goes Here */


}

void Skeleton::visitOperadorRelacional2(OperadorRelacional2 *operador_relacional)
{
  /* Code For OperadorRelacional2 Goes Here */


}

void Skeleton::visitOperadorRelacional3(OperadorRelacional3 *operador_relacional)
{
  /* Code For OperadorRelacional3 Goes Here */


}

void Skeleton::visitOperadorRelacional4(OperadorRelacional4 *operador_relacional)
{
  /* Code For OperadorRelacional4 Goes Here */


}

void Skeleton::visitOperadorRelacional5(OperadorRelacional5 *operador_relacional)
{
  /* Code For OperadorRelacional5 Goes Here */


}

void Skeleton::visitOperadorRelacional6(OperadorRelacional6 *operador_relacional)
{
  /* Code For OperadorRelacional6 Goes Here */


}

void Skeleton::visitOperadorLogico1(OperadorLogico1 *operador_logico)
{
  /* Code For OperadorLogico1 Goes Here */


}

void Skeleton::visitOperadorLogico2(OperadorLogico2 *operador_logico)
{
  /* Code For OperadorLogico2 Goes Here */


}

void Skeleton::visitOperadorLogico3(OperadorLogico3 *operador_logico)
{
  /* Code For OperadorLogico3 Goes Here */


}

void Skeleton::visitOperadorLogicoNegacao(OperadorLogicoNegacao *operador_logico_negacao)
{
  /* Code For OperadorLogicoNegacao Goes Here */

  if (operador_logico_negacao->negacao_) operador_logico_negacao->negacao_->accept(this);

}

void Skeleton::visitLNegacao(LNegacao *l_negacao)
{
  /* Code For LNegacao Goes Here */


}

void Skeleton::visitOperadorAritmetico1(OperadorAritmetico1 *operador_aritmetico)
{
  /* Code For OperadorAritmetico1 Goes Here */
  operatorsStack.push('+');

}

void Skeleton::visitOperadorAritmetico2(OperadorAritmetico2 *operador_aritmetico)
{
  /* Code For OperadorAritmetico2 Goes Here */
  operatorsStack.push('-');

}

void Skeleton::visitOperadorAritmetico3(OperadorAritmetico3 *operador_aritmetico)
{
  /* Code For OperadorAritmetico3 Goes Here */
  operatorsStack.push('*');

}

void Skeleton::visitOperadorAritmetico4(OperadorAritmetico4 *operador_aritmetico)
{
  /* Code For OperadorAritmetico4 Goes Here */
  operatorsStack.push('/');

}

void Skeleton::visitLCase(LCase *l_case)
{
  /* Code For LCase Goes Here */

  if (l_case->seletor_) l_case->seletor_->accept(this);
  if (l_case->regraseletor_) l_case->regraseletor_->accept(this);

}

void Skeleton::visitRegraSeletor1(RegraSeletor1 *regra_seletor)
{
  /* Code For RegraSeletor1 Goes Here */

  if (regra_seletor->seletor_) regra_seletor->seletor_->accept(this);
  if (regra_seletor->comando_) regra_seletor->comando_->accept(this);

}

void Skeleton::visitRegraSeletor2(RegraSeletor2 *regra_seletor)
{
  /* Code For RegraSeletor2 Goes Here */

  if (regra_seletor->seletor_) regra_seletor->seletor_->accept(this);
  if (regra_seletor->comando_) regra_seletor->comando_->accept(this);
  if (regra_seletor->regraseletor_) regra_seletor->regraseletor_->accept(this);

}

void Skeleton::visitSeletorInteger(SeletorInteger *seletor_integer)
{
  /* Code For SeletorInteger Goes Here */

  visitInteger(seletor_integer->integer_);

}

void Skeleton::visitSeletorChar(SeletorChar *seletor_char)
{
  /* Code For SeletorChar Goes Here */

  visitChar(seletor_char->char_);

}

void Skeleton::visitSeletorIdent(SeletorIdent *seletor_ident)
{
  /* Code For SeletorIdent Goes Here */

  visitIdent(seletor_ident->ident_);

}

void Skeleton::visitLChamad(LChamad *l_chamad)
{
  /* Code For LChamad Goes Here */

  visitIdent(l_chamad->ident_);
  if (l_chamad->listaident_) l_chamad->listaident_->accept(this);

}

void Skeleton::visitListaIdentIdent(ListaIdentIdent *lista_ident_ident)
{
  /* Code For ListaIdentIdent Goes Here */

  visitIdent(lista_ident_ident->ident_);

}

void Skeleton::visitListaIdent1(ListaIdent1 *lista_ident)
{
  /* Code For ListaIdent1 Goes Here */

  visitIdent(lista_ident->ident_);
  if (lista_ident->listaident_) lista_ident->listaident_->accept(this);

}

void Skeleton::visitLFuncao(LFuncao *l_funcao)
{
  /* Code For LFuncao Goes Here */

  visitIdent(l_funcao->ident_);
  if (l_funcao->regrablocovar_) l_funcao->regrablocovar_->accept(this);
  if (l_funcao->regratipo_) l_funcao->regratipo_->accept(this);
  if (l_funcao->blocovar_) l_funcao->blocovar_->accept(this);
  if (l_funcao->blococomando_) l_funcao->blococomando_->accept(this);

}

void Skeleton::visitProcedimento1(Procedimento1 *procedimento)
{
  /* Code For Procedimento1 Goes Here */

  visitIdent(procedimento->ident_);
  if (procedimento->regrablocovar_) procedimento->regrablocovar_->accept(this);
  if (procedimento->blocovar_) procedimento->blocovar_->accept(this);
  if (procedimento->blococomando_) procedimento->blococomando_->accept(this);

}

void Skeleton::visitProcedimento2(Procedimento2 *procedimento)
{
  /* Code For Procedimento2 Goes Here */

  visitIdent(procedimento->ident_);
  if (procedimento->blocovar_) procedimento->blocovar_->accept(this);
  if (procedimento->blococomando_) procedimento->blococomando_->accept(this);

}

void Skeleton::visitExpAr(ExpAr *exp_ar)
{
  /* Code For ExpAr Goes Here */

  if (exp_ar->operando_) exp_ar->operando_->accept(this);
  if (exp_ar->regraaritmetica_) exp_ar->regraaritmetica_->accept(this);

}

void Skeleton::visitOperandoInteger(OperandoInteger *operando_integer)
{
  /* Code For OperandoInteger Goes Here */
  char operandoString[10];
  sprintf(operandoString, "%d", operando_integer->integer_);
  identStack.push(operandoString);

  pair<string, string> values;
  values.first = "int";
  values.second = operandoString;

  pair<string, pair<string,string> > key;
  key.first = identStack.top();
  key.second = values;
  symbolicTable.insert(key);

  // visitInteger(operando_integer->integer_);

}

void Skeleton::visitOperandoDouble(OperandoDouble *operando_double)
{
  /* Code For OperandoDouble Goes Here */

  visitDouble(operando_double->double_);

}

void Skeleton::visitOperandoIdent(OperandoIdent *operando_ident)
{
  /* Code For OperandoIdent Goes Here */
  if(symbolicTable.find(operando_ident->ident_) == symbolicTable.end()) {
    errors.push_back("Variável indefinida - a variável " + operando_ident->ident_ + " não foi definida no bloco de variáveis.");
  }

  if(symbolicTable[operando_ident->ident_].second == "_default") {
    errors.push_back("Variável não inicializada - a variável " + operando_ident->ident_ + " não foi inicializada no bloco de comandos.");
    return;
  }

  identStack.push(operando_ident->ident_);

  visitIdent(operando_ident->ident_);

}

void Skeleton::visitRegraAritmetica1(RegraAritmetica1 *regra_aritmetica)
{
  /* Code For RegraAritmetica1 Goes Here */

  if (regra_aritmetica->operadoraritmetico_) regra_aritmetica->operadoraritmetico_->accept(this);
  if (regra_aritmetica->operando_) regra_aritmetica->operando_->accept(this);

}

void Skeleton::visitRegraAritmetica2(RegraAritmetica2 *regra_aritmetica)
{
  /* Code For RegraAritmetica2 Goes Here */

  if (regra_aritmetica->operadoraritmetico_) regra_aritmetica->operadoraritmetico_->accept(this);
  if (regra_aritmetica->operando_) regra_aritmetica->operando_->accept(this);
  if (regra_aritmetica->regraaritmetica_) regra_aritmetica->regraaritmetica_->accept(this);

}

void Skeleton::visitExpressaoRelacionalOperando(ExpressaoRelacionalOperando *expressao_relacional_operando)
{
  /* Code For ExpressaoRelacionalOperando Goes Here */

  if (expressao_relacional_operando->operando_) expressao_relacional_operando->operando_->accept(this);

}

void Skeleton::visitExpressaoRelacional1(ExpressaoRelacional1 *expressao_relacional)
{
  /* Code For ExpressaoRelacional1 Goes Here */

  if (expressao_relacional->operando_) expressao_relacional->operando_->accept(this);
  if (expressao_relacional->regrarelacional_) expressao_relacional->regrarelacional_->accept(this);

}

void Skeleton::visitExpressaoRelacional2(ExpressaoRelacional2 *expressao_relacional)
{
  /* Code For ExpressaoRelacional2 Goes Here */

  if (expressao_relacional->expressaoaritmetica_) expressao_relacional->expressaoaritmetica_->accept(this);
  if (expressao_relacional->regrarelacional_) expressao_relacional->regrarelacional_->accept(this);

}

void Skeleton::visitRegraRelacional1(RegraRelacional1 *regra_relacional)
{
  /* Code For RegraRelacional1 Goes Here */

  if (regra_relacional->operadorrelacional_) regra_relacional->operadorrelacional_->accept(this);
  if (regra_relacional->operando_) regra_relacional->operando_->accept(this);

}

void Skeleton::visitRegraRelacional2(RegraRelacional2 *regra_relacional)
{
  /* Code For RegraRelacional2 Goes Here */

  if (regra_relacional->operadorrelacional_) regra_relacional->operadorrelacional_->accept(this);
  if (regra_relacional->expressaoaritmetica_) regra_relacional->expressaoaritmetica_->accept(this);

}

void Skeleton::visitExpressaoLogica_falso(ExpressaoLogica_falso *expressao_logica_falso)
{
  /* Code For ExpressaoLogica_falso Goes Here */


}

void Skeleton::visitExpressaoLogica1(ExpressaoLogica1 *expressao_logica)
{
  /* Code For ExpressaoLogica1 Goes Here */

  if (expressao_logica->regralogico_) expressao_logica->regralogico_->accept(this);

}

void Skeleton::visitExpressaoLogica_verdadeiro(ExpressaoLogica_verdadeiro *expressao_logica_verdadeiro)
{
  /* Code For ExpressaoLogica_verdadeiro Goes Here */


}

void Skeleton::visitExpressaoLogica2(ExpressaoLogica2 *expressao_logica)
{
  /* Code For ExpressaoLogica2 Goes Here */

  if (expressao_logica->regralogico_) expressao_logica->regralogico_->accept(this);

}

void Skeleton::visitExpressaoLogicaExpressaoRelacional(ExpressaoLogicaExpressaoRelacional *expressao_logica_expressao_relacional)
{
  /* Code For ExpressaoLogicaExpressaoRelacional Goes Here */

  if (expressao_logica_expressao_relacional->expressaorelacional_) expressao_logica_expressao_relacional->expressaorelacional_->accept(this);

}

void Skeleton::visitExpressaoLogica3(ExpressaoLogica3 *expressao_logica)
{
  /* Code For ExpressaoLogica3 Goes Here */

  if (expressao_logica->expressaorelacional_) expressao_logica->expressaorelacional_->accept(this);
  if (expressao_logica->regralogico_) expressao_logica->regralogico_->accept(this);

}

void Skeleton::visitExpressaoLogica4(ExpressaoLogica4 *expressao_logica)
{
  /* Code For ExpressaoLogica4 Goes Here */

  if (expressao_logica->negacao_) expressao_logica->negacao_->accept(this);
  if (expressao_logica->expressaologica_) expressao_logica->expressaologica_->accept(this);

}

void Skeleton::visitExpressaoLogica5(ExpressaoLogica5 *expressao_logica)
{
  /* Code For ExpressaoLogica5 Goes Here */

  if (expressao_logica->negacao_) expressao_logica->negacao_->accept(this);
  if (expressao_logica->expressaologica_) expressao_logica->expressaologica_->accept(this);
  if (expressao_logica->regralogico_) expressao_logica->regralogico_->accept(this);

}

void Skeleton::visitRegraLogico1(RegraLogico1 *regra_logico)
{
  /* Code For RegraLogico1 Goes Here */

  if (regra_logico->operadorlogico_) regra_logico->operadorlogico_->accept(this);
  if (regra_logico->expressaologica_) regra_logico->expressaologica_->accept(this);

}

void Skeleton::visitRegraLogico2(RegraLogico2 *regra_logico)
{
  /* Code For RegraLogico2 Goes Here */

  if (regra_logico->operadorlogico_) regra_logico->operadorlogico_->accept(this);
  if (regra_logico->expressaologica_) regra_logico->expressaologica_->accept(this);
  if (regra_logico->regralogico_) regra_logico->regralogico_->accept(this);

}



void Skeleton::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
  string ident = identStack.top();
  identStack.pop();

  string tipo = symbolicTable.find(ident)->second.first;

  if(tipo != "int") {
    errors.push_back("Incompatibilidade de tipos - a variável " + ident + " não é do tipo Integer.");
    return;
  }

  char valor[10];
  sprintf(valor, "%d", x);
  symbolicTable[ident].second = valor;
}

void Skeleton::visitChar(Char x)
{
  /* Code for Char Goes Here */
  string ident = identStack.top();
  identStack.pop();

  string tipo = symbolicTable.find(ident)->second.first;

  if(tipo != "char") {
    errors.push_back("Incompatibilidade de tipos - a variável " + ident + " não é do tipo Char.");
    return;
  }

  char valor[10];
  sprintf(valor, "%d", x);
  symbolicTable[ident].second = valor;
}

void Skeleton::visitDouble(Double x)
{
  /* Code for Double Goes Here */
  string ident = identStack.top();
  identStack.pop();

  string tipo = symbolicTable.find(ident)->second.first;

  if(tipo != "real") {
    errors.push_back("Incompatibilidade de tipos - a variável " + ident + " não é do tipo Real.");
    return;
  }

  char valor[10];
  sprintf(valor, "%d", x);
  symbolicTable[ident].second = valor;
}

void Skeleton::visitString(String x)
{
  /* Code for String Goes Here */
}

void Skeleton::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}



